export const NIFTY_50_STOCKS = [
    'ADANIENT.NS', 'ADANIPORTS.NS', 'APOLLOHOSP.NS', 'ASIANPAINT.NS', 'AXISBANK.NS',
    'BAJAJ-AUTO.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BHARTIARTL.NS', 'BPCL.NS',
    'BRITANNIA.NS', 'CIPLA.NS', 'COALINDIA.NS', 'DIVISLAB.NS', 'DRREDDY.NS',
    'EICHERMOT.NS', 'GRASIM.NS', 'HCLTECH.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS',
    'HEROMOTOCO.NS', 'HINDALCO.NS', 'HINDUNILVR.NS', 'ICICIBANK.NS', 'ITC.NS',
    'INDUSINDBK.NS', 'INFY.NS', 'JSWSTEEL.NS', 'KOTAKBANK.NS', 'LT.NS',
    'LTIM.NS', 'M&M.NS', 'MARUTI.NS', 'NESTLEIND.NS', 'NTPC.NS',
    'ONGC.NS', 'POWERGRID.NS', 'RELIANCE.NS', 'SBILIFE.NS', 'SBIN.NS',
    'SUNPHARMA.NS', 'TATACONSUM.NS', 'TATAMOTORS.NS', 'TATASTEEL.NS', 'TCS.NS',
    'TECHM.NS', 'TITAN.NS', 'ULTRACEMCO.NS', 'UPL.NS', 'WIPRO.NS'
];

export const NIFTY_MIDCAP_100_STOCKS = [
    'AIAENG.NS', 'APLAPOLLO.NS', 'ABBOTINDIA.NS', 'ADANIENSOL.NS', 'ABFRL.NS',
    'ABCAPITAL.NS', 'ALKEM.NS', 'ASHOKLEY.NS', 'ASTRAL.NS', 'AUROPHARMA.NS',
    'AU_BANK.NS', 'BALKRISIND.NS', 'BANDHANBNK.NS', 'BANKINDIA.NS', 'BATAINDIA.NS',
    'BERGEPAINT.NS', 'BEL.NS', 'BHARATFORG.NS', 'BHEL.NS', 'BOSCHLTD.NS',
    'CANBK.NS', 'COFORGE.NS', 'CONCOR.NS', 'CUMMINSIND.NS', 'DALBHARAT.NS',
    'DEEPAKNTR.NS', 'DELHIVERY.NS', 'DEVYANI.NS', 'DIXON.NS', 'LALPATHLAB.NS',
    'ESCORTS.NS', 'EXIDEIND.NS', 'FEDERALBNK.NS', 'FORTIS.NS', 'GMRINFRA.NS',
    'GLENMARK.NS', 'GODREJCP.NS', 'GODREJPROP.NS', 'GUJGASLTD.NS', 'HAL.NS',
    'HAVELLS.NS', 'HINDZINC.NS', 'HONAUT.NS', 'IDFCFIRSTB.NS', 'INDIANB.NS',
    'INDHOTEL.NS', 'IGL.NS', 'INDUSTOWER.NS', 'IPCALAB.NS', 'JINDALSTEL.NS',
    'JSL.NS', 'JSWENERGY.NS', 'JUBLFOOD.NS', 'KPRMILL.NS', 'KEI.NS',
    'KAYNES.NS', 'KALYANKJIL.NS', 'KPITTECH.NS', 'L&TFH.NS', 'LICHSGFIN.NS',
    'LUPIN.NS', 'MRF.NS', 'M&MFIN.NS', 'MARICO.NS', 'MAXHEALTH.NS',
    'METROBRAND.NS', 'MPHASIS.NS', 'MUTHOOTFIN.NS', 'NHPC.NS', 'NMDC.NS',
    'NAVINFLUOR.NS', 'OBEROIRLTY.NS', 'OFSS.NS', 'OIL.NS', 'PAYTM.NS',
    'PERSISTENT.NS', 'PETRONET.NS', 'PIIND.NS', 'POLYCAB.NS', 'POONAWALLA.NS',
    'PFC.NS', 'PRESTIGE.NS', 'PNB.NS', 'RECLTD.NS', 'RVNL.NS',
    'SAIL.NS', 'SCHAEFFLER.NS', 'SHRIRAMFIN.NS', 'SJVN.NS', 'SKFINDIA.NS',
    'SONACOMS.NS', 'SRF.NS', 'SUNDARMFIN.NS', 'SUPREMEIND.NS', 'SUZLON.NS',
    'TATACOMM.NS', 'TATAELXSI.NS', 'TATAWCF.NS', 'TATACHEM.NS', 'TATAPOWER.NS',
    'THERMAX.NS', 'TIINDIA.NS', 'TORNTPHARM.NS', 'TORNTPOWER.NS', 'TRENT.NS',
    'TVSMOTOR.NS', 'UNIONBANK.NS', 'UNOMINDA.NS', 'UBL.NS', 'VBL.NS',
    'VEDL.NS', 'VOLTAS.NS', 'WHIRLPOOL.NS', 'YESBANK.NS', 'ZEEL.NS',
    'ZOMATO.NS', 'ZYDUSLIFE.NS'
];

export const TRACKED_STOCKS = [...new Set([...NIFTY_50_STOCKS, ...NIFTY_MIDCAP_100_STOCKS])];
