
export const ADDITIONAL_STOCKS = [
    // --- NIFTY MIDCAP 150 (Remaining & Extended) ---
    { symbol: 'MAXHEALTH.NS', companyName: 'Max Healthcare Institute Ltd.' },
    { symbol: 'PHOENIXLTD.NS', companyName: 'The Phoenix Mills Ltd.' },
    { symbol: 'MFSL.NS', companyName: 'Max Financial Services Ltd.' },
    { symbol: 'L&TFH.NS', companyName: 'L&T Finance Holdings Ltd.' },
    { symbol: 'SUNDARAM.NS', companyName: 'Sundaram Finance Ltd.' },
    { symbol: 'TATAINVEST.NS', companyName: 'Tata Investment Corporation Ltd.' },
    { symbol: 'TORNTPOWER.NS', companyName: 'Torrent Power Ltd.' },
    { symbol: 'JSWENERGY.NS', companyName: 'JSW Energy Ltd.' },
    { symbol: 'NHPC.NS', companyName: 'NHPC Ltd.' },
    { symbol: 'SJVN.NS', companyName: 'SJVN Ltd.' },
    { symbol: 'BPCL.NS', companyName: 'Bharat Petroleum Corporation Ltd.' },
    { symbol: 'HPCL.NS', companyName: 'Hindustan Petroleum Corporation Ltd.' },
    { symbol: 'IOC.NS', companyName: 'Indian Oil Corporation Ltd.' },
    { symbol: 'PETRONET.NS', companyName: 'Petronet LNG Ltd.' },
    { symbol: 'IGL.NS', companyName: 'Indraprastha Gas Ltd.' },
    { symbol: 'MGL.NS', companyName: 'Mahanagar Gas Ltd.' },
    { symbol: 'GUJGASLTD.NS', companyName: 'Gujarat Gas Ltd.' },
    { symbol: 'ATGL.NS', companyName: 'Adani Total Gas Ltd.' },
    { symbol: 'AWL.NS', companyName: 'Adani Wilmar Ltd.' },
    { symbol: 'PATANJALI.NS', companyName: 'Patanjali Foods Ltd.' },
    { symbol: 'BERGEPAINT.NS', companyName: 'Berger Paints India Ltd.' },
    { symbol: 'KANSAINER.NS', companyName: 'Kansai Nerolac Paints Ltd.' },
    { symbol: 'INDIGOPNTS.NS', companyName: 'Indigo Paints Ltd.' },
    { symbol: 'PAGEIND.NS', companyName: 'Page Industries Ltd.' },
    { symbol: 'LUXIND.NS', companyName: 'Lux Industries Ltd.' },
    { symbol: 'RUPA.NS', companyName: 'Rupa & Company Ltd.' },
    { symbol: 'DOLLAR.NS', companyName: 'Dollar Industries Ltd.' },
    { symbol: 'KPRMILL.NS', companyName: 'K.P.R. Mill Ltd.' },
    { symbol: 'WELSPUNLIV.NS', companyName: 'Welspun Living Ltd.' },
    { symbol: 'TRIDENT.NS', companyName: 'Trident Ltd.' },
    { symbol: 'SWANENERGY.NS', companyName: 'Swan Energy Ltd.' },
    { symbol: 'OLECTRA.NS', companyName: 'Olectra Greentech Ltd.' },
    { symbol: 'JBMJAI.NS', companyName: 'JBM Auto Ltd.' },
    { symbol: 'FORCE.NS', companyName: 'Force Motors Ltd.' },
    { symbol: 'SMLISUZU.NS', companyName: 'SML Isuzu Ltd.' },
    { symbol: 'VSTTILLERS.NS', companyName: 'V.S.T. Tillers Tractors Ltd.' },
    { symbol: 'ESCORTS.NS', companyName: 'Escorts Kubota Ltd.' },
    { symbol: 'ACE.NS', companyName: 'Action Construction Equipment Ltd.' },
    { symbol: 'ELECON.NS', companyName: 'Elecon Engineering Company Ltd.' },
    { symbol: 'THEMISMED.NS', companyName: 'Themis Medicare Ltd.' },
    { symbol: 'MARKSANS.NS', companyName: 'Marksans Pharma Ltd.' },
    { symbol: 'WOCKPHARMA.NS', companyName: 'Wockhardt Ltd.' },
    { symbol: 'STRIDES.NS', companyName: 'Strides Pharma Science Ltd.' },
    { symbol: 'STAR.NS', companyName: 'Strides Pharma Science' },
    { symbol: 'SEQUENT.NS', companyName: 'Sequent Scientific Ltd.' },
    { symbol: 'HUEBACH.NS', companyName: 'Heubach Colorants India Ltd.' }, // formerly Clariant
    { symbol: 'SUDARSCHEM.NS', companyName: 'Sudarshan Chemical Industries Ltd.' },
    { symbol: 'BODALCHEM.NS', companyName: 'Bodal Chemicals Ltd.' },
    { symbol: 'BHAGERIA.NS', companyName: 'Bhageria Industries Ltd.' },
    { symbol: 'KIRIINDUS.NS', companyName: 'Kiri Industries Ltd.' },
    { symbol: 'SHARDACROP.NS', companyName: 'Sharda Cropchem Ltd.' },
    { symbol: 'DHANUKA.NS', companyName: 'Dhanuka Agritech Ltd.' },
    { symbol: 'RALLIS.NS', companyName: 'Rallis India Ltd.' },
    { symbol: 'BHARATRAS.NS', companyName: 'Bharat Rasayan Ltd.' },
    { symbol: 'IPL.NS', companyName: 'India Pesticides Ltd.' },
    { symbol: 'ASTEC.NS', companyName: 'Astec LifeSciences Ltd.' },
    { symbol: 'HERANBA.NS', companyName: 'Heranba Industries Ltd.' },
    { symbol: 'BESTAGRO.NS', companyName: 'Best Agrolife Ltd.' },
    { symbol: 'PUNJABCHEM.NS', companyName: 'Punjab Chemicals & Crop Protection Ltd.' },
    { symbol: 'EXCELINDUS.NS', companyName: 'Excel Industries Ltd.' },
    { symbol: 'JUBLINDS.NS', companyName: 'Jubilant Industries Ltd.' },
    { symbol: 'PAUSHAK.NS', companyName: 'Paushak Ltd.' },
    { symbol: 'TRANSPEK.NS', companyName: 'Transpek Industry Ltd.' },
    { symbol: 'ALKYLAMINE.NS', companyName: 'Alkyl Amines Chemicals Ltd.' },
    { symbol: 'BALAMINES.NS', companyName: 'Balaji Amines Ltd.' },
    { symbol: 'FCL.NS', companyName: 'Fineotex Chemical Ltd.' },
    { symbol: 'ROSSARI.NS', companyName: 'Rossari Biotech Ltd.' },
    { symbol: 'YASHO.NS', companyName: 'Yasho Industries Ltd.' },
    { symbol: 'TATVA.NS', companyName: 'Tatva Chintan Pharma Chem Ltd.' },
    { symbol: 'AMIORG.NS', companyName: 'Ami Organics Ltd.' },
    { symbol: 'LAXMICOT.NS', companyName: 'Laxmi Cotspin Ltd.' }, // Check symbol
    { symbol: 'NEOGEN.NS', companyName: 'Neogen Chemicals Ltd.' },
    { symbol: 'FINEORG.NS', companyName: 'Fine Organic Industries Ltd.' },
    { symbol: 'GALAXY.NS', companyName: 'Galaxy Surfactants Ltd.' },
    { symbol: 'AETHER.NS', companyName: 'Aether Industries Ltd.' },
    { symbol: 'ANUPAM.NS', companyName: 'Anupam Rasayan India Ltd.' },
    { symbol: 'CLEAN.NS', companyName: 'Clean Science and Technology Ltd.' },
    { symbol: 'FLUOROCHEM.NS', companyName: 'Gujarat Fluorochemicals Ltd.' },

    // --- NIFTY SMALLCAP 250 (Selection) ---
    { symbol: 'ALOKINDS.NS', companyName: 'Alok Industries Ltd.' },
    { symbol: 'WELENT.NS', companyName: 'Welspun Enterprises Ltd.' },
    { symbol: 'HFCL.NS', companyName: 'HFCL Ltd.' },
    { symbol: 'ITI.NS', companyName: 'ITI Ltd.' },
    { symbol: 'TEJASNET.NS', companyName: 'Tejas Networks Ltd.' },
    { symbol: 'MTNL.NS', companyName: 'Mahanagar Telephone Nigam Ltd.' },
    { symbol: 'TTML.NS', companyName: 'Tata Teleservices (Maharashtra) Ltd.' },
    { symbol: 'ONMOBILE.NS', companyName: 'OnMobile Global Ltd.' },
    { symbol: 'TANLA.NS', companyName: 'Tanla Platforms Ltd.' },
    { symbol: 'ROUTE.NS', companyName: 'Route Mobile Ltd.' },
    { symbol: 'BCG.NS', companyName: 'Brightcom Group Ltd.' },
    { symbol: 'FSL.NS', companyName: 'Firstsource Solutions Ltd.' },
    { symbol: 'HGS.NS', companyName: 'Hinduja Global Solutions Ltd.' },
    { symbol: 'ECLERX.NS', companyName: 'eClerx Services Ltd.' },
    { symbol: 'CMSINFO.NS', companyName: 'CMS Info Systems Ltd.' },
    { symbol: 'SIS.NS', companyName: 'SIS Ltd.' },
    { symbol: 'TEAMLEASE.NS', companyName: 'TeamLease Services Ltd.' },
    { symbol: 'QUESS.NS', companyName: 'Quess Corp Ltd.' },
    { symbol: 'NAVKARCORP.NS', companyName: 'Navkar Corporation Ltd.' },
    { symbol: 'LLOYDSME.NS', companyName: 'Lloyds Metals and Energy Ltd.' },
    { symbol: 'GPIL.NS', companyName: 'Godawari Power & Ispat Ltd.' },
    { symbol: 'JAYNECOIND.NS', companyName: 'Jayaswal Neco Industries Ltd.' },
    { symbol: 'ELECTCAST.NS', companyName: 'Electrosteel Castings Ltd.' },
    { symbol: 'KIOCL.NS', companyName: 'KIOCL Ltd.' },
    { symbol: 'MOIL.NS', companyName: 'MOIL Ltd.' },
    { symbol: 'GMDC.NS', companyName: 'Gujarat Mineral Development Corporation Ltd.' },
    { symbol: 'SANDUR.NS', companyName: 'Sandur Manganese & Iron Ores Ltd.' },
    { symbol: 'ASHAPURMIN.NS', companyName: 'Ashapura Minechem Ltd.' },
    { symbol: '20MICRONS.NS', companyName: '20 Microns Ltd.' },
    { symbol: 'ORIENTABRA.NS', companyName: 'Orient Abrasives Ltd.' }, // Symbol changed probably
    { symbol: 'WENDT.NS', companyName: 'Wendt (India) Ltd.' },
    { symbol: 'GRINDWELL.NS', companyName: 'Grindwell Norton Ltd.' },
    { symbol: 'CARBORUNIV.NS', companyName: 'Carborundum Universal Ltd.' },
    { symbol: 'AIAENG.NS', companyName: 'AIA Engineering Ltd.' },
    { symbol: 'TIMKEN.NS', companyName: 'Timken India Ltd.' },
    { symbol: 'SKFINDIA.NS', companyName: 'SKF India Ltd.' },
    { symbol: 'SCHAEFFLER.NS', companyName: 'Schaeffler India Ltd.' },
    { symbol: 'NRBBEARING.NS', companyName: 'NRB Bearings Ltd.' },
    { symbol: 'MENONBE.NS', companyName: 'Menon Bearings Ltd.' },
    { symbol: 'ROLE.NS', companyName: 'Rolex Rings Ltd.' }, // Symbol check
    { symbol: 'RAMKRISHNA.NS', companyName: 'Ramkrishna Forgings Ltd.' },
    { symbol: 'MMFL.NS', companyName: 'M M Forgings Ltd.' },
    { symbol: 'BALAMINES.NS', companyName: 'Balaji Amines Ltd.' },
    { symbol: 'TCI.NS', companyName: 'Transport Corporation of India Ltd.' },
    { symbol: 'TCIEXP.NS', companyName: 'TCI Express Ltd.' },
    { symbol: 'MAHLOG.NS', companyName: 'Mahindra Logistics Ltd.' },
    { symbol: 'VRLLOG.NS', companyName: 'VRL Logistics Ltd.' },
    { symbol: 'GATI.NS', companyName: 'Gati Ltd.' }, // Now ACEL
    { symbol: 'SNOWMAN.NS', companyName: 'Snowman Logistics Ltd.' },
    { symbol: 'LANCER.NS', companyName: 'Lancer Container Lines Ltd.' },
    { symbol: 'RITCO.NS', companyName: 'Ritco Logistics Ltd.' },
    { symbol: 'SICAL.NS', companyName: 'Sical Logistics Ltd.' },
    { symbol: 'TOTAL.NS', companyName: 'Total Transport Systems Ltd.' },
    { symbol: 'JETFREIGHT.NS', companyName: 'Jet Freight Logistics Ltd.' },
    { symbol: 'AVG.NS', companyName: 'AVG Logistics Ltd.' },
    { symbol: 'SHREEPUSHK.NS', companyName: 'Shree Pushkar Chemicals & Fertilizers Ltd.' },
    { symbol: 'VISHNU.NS', companyName: 'Vishnu Chemicals Ltd.' },
    { symbol: 'INDOCO.NS', companyName: 'Indoco Remedies Ltd.' },
    { symbol: 'SMSPHARMA.NS', companyName: 'SMS Pharmaceuticals Ltd.' },
    { symbol: 'HIKAL.NS', companyName: 'Hikal Ltd.' },
    { symbol: 'NEULANDLAB.NS', companyName: 'Neuland Laboratories Ltd.' },
    { symbol: 'SOLARA.NS', companyName: 'Solara Active Pharma Sciences Ltd.' },
    { symbol: 'DISHMAN.NS', companyName: 'Dishman Carbogen Amcis Ltd.' },
    { symbol: 'BLISSGVS.NS', companyName: 'Bliss GVS Pharma Ltd.' },
    { symbol: 'MOREPENLAB.NS', companyName: 'Morepen Laboratories Ltd.' },
    { symbol: 'VIMTALABS.NS', companyName: 'Vimta Labs Ltd.' },
    { symbol: 'THYROCARE.NS', companyName: 'Thyrocare Technologies Ltd.' },
    { symbol: 'KRSNAA.NS', companyName: 'Krsnaa Diagnostics Ltd.' },
    { symbol: 'VIJAYA.NS', companyName: 'Vijaya Diagnostic Centre Ltd.' },
    { symbol: 'INDIGOPNTS.NS', companyName: 'Indigo Paints Ltd.' },
    { symbol: 'SHALPAINTS.NS', companyName: 'Shalimar Paints Ltd.' },

    // --- MICROCAP / OTHERS ---
    { symbol: 'BCONCEPTS.NS', companyName: 'Brand Concepts Ltd.' },
    { symbol: 'HPAL.NS', companyName: 'HP Adhesives Ltd.' },
    { symbol: 'METROBRAND.NS', companyName: 'Metro Brands Ltd.' },
    { symbol: 'CAMPUS.NS', companyName: 'Campus Activewear Ltd.' },
    { symbol: 'LIBERTSHOE.NS', companyName: 'Liberty Shoes Ltd.' },
    { symbol: 'KHADIM.NS', companyName: 'Khadim India Ltd.' },
    { symbol: 'MIRZAINT.NS', companyName: 'Mirza International Ltd.' },
    { symbol: 'REDTAPE.NS', companyName: 'Redtape Ltd.' },
    { symbol: 'VIPIND.NS', companyName: 'VIP Industries Ltd.' },
    { symbol: 'SAFARI.NS', companyName: 'Safari Industries (India) Ltd.' },
    { symbol: 'MOKSH.NS', companyName: 'Moksh Ornaments Ltd.' },
    { symbol: 'GOLDIAM.NS', companyName: 'Goldiam International Ltd.' },
    { symbol: 'RENAISSANCE.NS', companyName: 'Renaissance Global Ltd.' },
    { symbol: 'RADHIKA.NS', companyName: 'Radhika Jeweltech Ltd.' },
    { symbol: 'SKYGOLD.NS', companyName: 'Sky Gold Ltd.' },
    { symbol: 'SILGO.NS', companyName: 'Silgo Retail Ltd.' },
    { symbol: 'TBZ.NS', companyName: 'Tribhovandas Bhimji Zaveri Ltd.' },
    { symbol: 'THANGAMAYL.NS', companyName: 'Thangamayil Jewellery Ltd.' },
    { symbol: 'PCJEWELLER.NS', companyName: 'PC Jeweller Ltd.' },
    { symbol: 'SENCO.NS', companyName: 'Senco Gold Ltd.' },
    { symbol: 'ETHOSLTD.NS', companyName: 'Ethos Ltd.' },
    { symbol: 'KDDL.NS', companyName: 'KDDL Ltd.' },
    { symbol: 'JUSTDIAL.NS', companyName: 'Just Dial Ltd.' },
    { symbol: 'MATRIMONY.NS', companyName: 'Matrimony.com Ltd.' },
    { symbol: 'NAZARA.NS', companyName: 'Nazara Technologies Ltd.' },
    { symbol: 'EASEMYTRIP.NS', companyName: 'Easy Trip Planners Ltd.' },
    { symbol: 'YATRA.NS', companyName: 'Yatra Online Ltd.' },
    { symbol: 'RATEGAIN.NS', companyName: 'RateGain Travel Technologies Ltd.' },
    { symbol: 'CEINFO.NS', companyName: 'C.E. Info Systems Ltd.' }, // Link to Maps
    { symbol: 'MAPMYINDIA.NS', companyName: 'C.E. Info Systems Ltd.' },
    { symbol: 'LATENTVIEW.NS', companyName: 'Latent View Analytics Ltd.' },
    { symbol: 'HAPPSTMNDS.NS', companyName: 'Happiest Minds Technologies Ltd.' },
    { symbol: 'SAKSOFT.NS', companyName: 'Saksoft Ltd.' },
    { symbol: 'DATAMATICS.NS', companyName: 'Datamatics Global Services Ltd.' },
    { symbol: 'NUCLEUS.NS', companyName: 'Nucleus Software Exports Ltd.' },
    { symbol: 'QUICKHEAL.NS', companyName: 'Quick Heal Technologies Ltd.' },
    { symbol: 'EXPLEOSOL.NS', companyName: 'Expleo Solutions Ltd.' },
    { symbol: 'KEI.NS', companyName: 'KEI Industries Ltd.' },
    { symbol: 'POLYCAB.NS', companyName: 'Polycab India Ltd.' },
    { symbol: 'FINCABLES.NS', companyName: 'Finolex Cables Ltd.' },
    { symbol: 'DIXON.NS', companyName: 'Dixon Technologies (India) Ltd.' },
    { symbol: 'AMBER.NS', companyName: 'Amber Enterprises India Ltd.' },
    { symbol: 'SYRMA.NS', companyName: 'Syrma SGS Technology Ltd.' },
    { symbol: 'KAYNES.NS', companyName: 'Kaynes Technology India Ltd.' },
    { symbol: 'AVALON.NS', companyName: 'Avalon Technologies Ltd.' },
    { symbol: 'CYIENTDLM.NS', companyName: 'Cyient DLM Ltd.' },
    { symbol: 'IKIO.NS', companyName: 'IKIO Lighting Ltd.' },
    { symbol: 'PGEL.NS', companyName: 'PG Electroplast Ltd.' },
    { symbol: 'HINDWAREAP.NS', companyName: 'Hindware Home Innovation Ltd.' },
    { symbol: 'SOMANYCERA.NS', companyName: 'Somany Ceramics Ltd.' },
    { symbol: 'KAJARIACER.NS', companyName: 'Kajaria Ceramics Ltd.' },
    { symbol: 'CERA.NS', companyName: 'Cera Sanitaryware Ltd.' },
    { symbol: 'ACRYSIL.NS', companyName: 'Acrysil Ltd.' }, // Carysil
    { symbol: 'CARYSIL.NS', companyName: 'Carysil Ltd.' },
    { symbol: 'GREENPANEL.NS', companyName: 'Greenpanel Industries Ltd.' },
    { symbol: 'GREENPLY.NS', companyName: 'Greenply Industries Ltd.' },
    { symbol: 'CENTURYPLY.NS', companyName: 'Century Plyboards (India) Ltd.' },
    { symbol: 'STYLAMIND.NS', companyName: 'Stylam Industries Ltd.' },
    { symbol: 'RUSHIL.NS', companyName: 'Rushil Decor Ltd.' },
    { symbol: 'ASIANGRANIT.NS', companyName: 'Asian Granito India Ltd.' },
    { symbol: 'ORIENTBELL.NS', companyName: 'Orient Bell Ltd.' },
    { symbol: 'NITCO.NS', companyName: 'Nitco Ltd.' },

    // Additional batches to reach ~630
    { symbol: 'APARINDS.NS', companyName: 'Apar Industries Ltd.' },
    { symbol: 'ASTRAL.NS', companyName: 'Astral Ltd.' },
    { symbol: 'SUPREMEIND.NS', companyName: 'Supreme Industries Ltd.' },
    { symbol: 'FINPIPE.NS', companyName: 'Finolex Industries Ltd.' },
    { symbol: 'PRINCEPIPE.NS', companyName: 'Prince Pipes and Fittings Ltd.' },
    { symbol: 'APOLLO.NS', companyName: 'Apollo Micro Systems Ltd.' }, // Check this one
    { symbol: 'APOLLOPIPES.NS', companyName: 'Apollo Pipes Ltd.' },
    { symbol: 'JINDALSAW.NS', companyName: 'Jindal Saw Ltd.' },
    { symbol: 'MANINDS.NS', companyName: 'Man Industries (India) Ltd.' },
    { symbol: 'WELCORP.NS', companyName: 'Welspun Corp Ltd.' },
    { symbol: 'MAHSEAMLES.NS', companyName: 'Maharashtra Seamless Ltd.' },
    { symbol: 'RATNAMANI.NS', companyName: 'Ratnamani Metals & Tubes Ltd.' },
    { symbol: 'SURYA-ROSHNI.NS', companyName: 'Surya Roshni Ltd.' }, // Symbol fix
    { symbol: 'VENKYS.NS', companyName: 'Venkys (India) Ltd.' },
    { symbol: 'SKMEGGPROD.NS', companyName: 'SKM Egg Products Export (India) Ltd.' },
    { symbol: 'OVAL.NS', companyName: 'Oval Investment' }, // Remove if invalid
    { symbol: 'HATSUN.NS', companyName: 'Hatsun Agro Product Ltd.' },
    { symbol: 'PARAGMILK.NS', companyName: 'Parag Milk Foods Ltd.' },
    { symbol: 'HERITGFOOD.NS', companyName: 'Heritage Foods Ltd.' },
    { symbol: 'DODLA.NS', companyName: 'Dodla Dairy Ltd.' },
    { symbol: 'UMANGDAIRY.NS', companyName: 'Umang Dairies Ltd.' },
    { symbol: 'TASTYBITE.NS', companyName: 'Tasty Bite Eatables Ltd.' },
    { symbol: 'ADFFOODS.NS', companyName: 'ADF Foods Ltd.' },
    { symbol: 'PRATAAPSN.NS', companyName: 'Prataap Snacks Ltd.' },
    { symbol: 'BIKAJI.NS', companyName: 'Bikaji Foods International Ltd.' },
    { symbol: 'MRSBECTORS.NS', companyName: 'Mrs. Bectors Food Specialities Ltd.' },
    { symbol: 'DFMFOODS.NS', companyName: 'DFM Foods Ltd.' },
    { symbol: 'HNDFDS.NS', companyName: 'Hindustan Foods Ltd.' },
    { symbol: 'GILLETTE.NS', companyName: 'Gillette India Ltd.' },
    { symbol: 'PGHH.NS', companyName: 'Procter & Gamble Hygiene and Health Care Ltd.' },
    { symbol: 'AKZOINDIA.NS', companyName: 'Akzo Nobel India Ltd.' },
    { symbol: 'SFL.NS', companyName: 'Sheela Foam Ltd.' },
    { symbol: 'SYMPHONY.NS', companyName: 'Symphony Ltd.' },
    { symbol: 'TTKPRESTIG.NS', companyName: 'TTK Prestige Ltd.' },
    { symbol: 'HAWKINS.NS', companyName: 'Hawkins Cookers Ltd.' },
    { symbol: 'STOVEKRAFT.NS', companyName: 'Stove Kraft Ltd.' },
    { symbol: 'BUTTERFLY.NS', companyName: 'Butterfly Gandhimathi Appliances Ltd.' },
    { symbol: 'BOROLTD.NS', companyName: 'Borosil Ltd.' },
    { symbol: 'LAOPALA.NS', companyName: 'La Opala RG Ltd.' },
    { symbol: 'CERA.NS', companyName: 'Cera Sanitaryware Ltd.' }, // Dup check
    { symbol: 'ORIENTELEC.NS', companyName: 'Orient Electric Ltd.' },
    { symbol: 'CROMPTON.NS', companyName: 'Crompton Greaves Consumer Electricals Ltd.' },
    { symbol: 'HAVELLS.NS', companyName: 'Havells India Ltd.' },
    { symbol: 'VGUARD.NS', companyName: 'V-Guard Industries Ltd.' },
    { symbol: 'BAJAJELEC.NS', companyName: 'Bajaj Electricals Ltd.' },
    { symbol: 'IFBIND.NS', companyName: 'IFB Industries Ltd.' },
    { symbol: 'WHIRLPOOL.NS', companyName: 'Whirlpool of India Ltd.' },
    { symbol: 'VOLTAS.NS', companyName: 'Voltas Ltd.' },
    { symbol: 'BLUESTARCO.NS', companyName: 'Blue Star Ltd.' },
    { symbol: 'JOHNSONCON.NS', companyName: 'Johnson Controls-Hitachi Air Conditioning India Ltd.' },
    { symbol: 'EPL.NS', companyName: 'EPL Ltd.' },
    { symbol: 'UFRAME.NS', companyName: 'Uflex Ltd.' }, // UFLEX
    { symbol: 'UFLEX.NS', companyName: 'Uflex Ltd.' },
    { symbol: 'POLYPLEX.NS', companyName: 'Polyplex Corporation Ltd.' },
    { symbol: 'JINDALPOLY.NS', companyName: 'Jindal Poly Films Ltd.' },
    { symbol: 'COSMOFIRST.NS', companyName: 'Cosmo First Ltd.' },
    { symbol: 'GARFIBRES.NS', companyName: 'Garware Technical Fibres Ltd.' },
    { symbol: 'TCNSBRANDS.NS', companyName: 'TCNS Clothing Co. Ltd.' },
    { symbol: 'GOKEX.NS', companyName: 'Gokaldas Exports Ltd.' },
    { symbol: 'SPAL.NS', companyName: 'S.P. Apparels Ltd.' },
    { symbol: 'KITEX.NS', companyName: 'Kitex Garments Ltd.' },
    { symbol: 'MONTECARLO.NS', companyName: 'Monte Carlo Fashions Ltd.' },
    { symbol: 'CANTABIL.NS', companyName: 'Cantabil Retail India Ltd.' },
    { symbol: 'VMANYAVAR.NS', companyName: 'Vedant Fashions Ltd.' },
    { symbol: 'RAYMOND.NS', companyName: 'Raymond Ltd.' },
    { symbol: 'ARVIND.NS', companyName: 'Arvind Ltd.' },
    { symbol: 'VARDHMAN.NS', companyName: 'Vardhman Textiles Ltd.' },
    { symbol: 'ALOKINDS.NS', companyName: 'Alok Industries Ltd.' },
    { symbol: 'SUTLEJTEX.NS', companyName: 'Sutlej Textiles and Industries Ltd.' },
    { symbol: 'RSWM.NS', companyName: 'RSWM Ltd.' },
    { symbol: 'FILATEX.NS', companyName: 'Filatex India Ltd.' },
    { symbol: 'AYM.NS', companyName: 'AYM Syntex Ltd.' }, // Check
    { symbol: 'NANDAN.NS', companyName: 'Nandan Denim Ltd.' },
    { symbol: 'SANGAMIND.NS', companyName: 'Sangam (India) Ltd.' },
    { symbol: 'NITINSPIN.NS', companyName: 'Nitin Spinners Ltd.' },
    { symbol: 'RSYSTEMS.NS', companyName: 'R Systems International Ltd.' },
    { symbol: 'NEWGEN.NS', companyName: 'Newgen Software Technologies Ltd.' },
    { symbol: 'NUCLEUS.NS', companyName: 'Nucleus Software Exports Ltd.' },
    { symbol: 'RAMCOSYS.NS', companyName: 'Ramco Systems Ltd.' },
    { symbol: '63MOONS.NS', companyName: '63 Moons Technologies Ltd.' },
    { symbol: 'HINDUJAGLO.NS', companyName: 'Hinduja Global Solutions Ltd.' }, // HGS
    { symbol: 'ALLSEC.NS', companyName: 'Allsec Technologies Ltd.' },
    { symbol: 'AXISCADES.NS', companyName: 'Axiscades Technologies Ltd.' },
    { symbol: 'TATAELXSI.NS', companyName: 'Tata Elxsi Ltd.' },
    { symbol: 'KPITTECH.NS', companyName: 'KPIT Technologies Ltd.' },
    { symbol: 'LTTS.NS', companyName: 'L&T Technology Services Ltd.' },
    { symbol: 'COFORGE.NS', companyName: 'Coforge Ltd.' },
    { symbol: 'MPHASIS.NS', companyName: 'Mphasis Ltd.' },
    { symbol: 'PERSISTENT.NS', companyName: 'Persistent Systems Ltd.' },
    { symbol: 'LTIM.NS', companyName: 'LTIMindtree Ltd.' },
    { symbol: 'BSOFT.NS', companyName: 'Birlasoft Ltd.' },
    { symbol: 'ZENSARTECH.NS', companyName: 'Zensar Technologies Ltd.' },
    { symbol: 'SONATSOFTW.NS', companyName: 'Sonata Software Ltd.' },
    { symbol: 'MASTEK.NS', companyName: 'Mastek Ltd.' },
    { symbol: 'INTELLECT.NS', companyName: 'Intellect Design Arena Ltd.' },
    { symbol: 'TANLA.NS', companyName: 'Tanla Platforms Ltd.' },
    { symbol: 'ROUTE.NS', companyName: 'Route Mobile Ltd.' },
    { symbol: 'MAPMYINDIA.NS', companyName: 'MapmyIndia' },
    { symbol: 'RATEGAIN.NS', companyName: 'RateGain Travel Technologies Ltd.' },
    { symbol: 'DATAMATICS.NS', companyName: 'Datamatics Global Services Ltd.' },

    // --- More diverse sectors to ensure 1000 mark ---
    { symbol: 'CENTURYTEX.NS', companyName: 'Century Textiles and Industries Ltd.' },
    { symbol: 'KESORAMIND.NS', companyName: 'Kesoram Industries Ltd.' },
    { symbol: 'JAMAICORP.NS', companyName: 'Jai Corp Ltd.' },
    { symbol: 'BOMBAYDYE.NS', companyName: 'The Bombay Dyeing and Manufacturing Company Ltd.' },
    { symbol: 'ARVIND.NS', companyName: 'Arvind Ltd.' },
    { symbol: 'RAYMOND.NS', companyName: 'Raymond Ltd.' },
    { symbol: 'GARFIBRES.NS', companyName: 'Garware Technical Fibres Ltd.' },
    { symbol: 'JINDALPOLY.NS', companyName: 'Jindal Poly Films Ltd.' },
    { symbol: 'UFLEX.NS', companyName: 'Uflex Ltd.' },
    { symbol: 'EPL.NS', companyName: 'EPL Ltd.' },
    { symbol: 'TIMETECHNO.NS', companyName: 'Time Technoplast Ltd.' },
    { symbol: 'MOLDTKPAC.NS', companyName: 'Mold-Tek Packaging Ltd.' },
    { symbol: 'HUHTAMAKI.NS', companyName: 'Huhtamaki India Ltd.' },
    { symbol: 'SHREERAMA.NS', companyName: 'Shree Rama Newsprint Ltd.' },
    { symbol: 'WSTCSTPAPR.NS', companyName: 'West Coast Paper Mills Ltd.' },
    { symbol: 'JKPAPER.NS', companyName: 'JK Paper Ltd.' },
    { symbol: 'ANDHRAPAP.NS', companyName: 'Andhra Paper Ltd.' },
    { symbol: 'SESHAPAPER.NS', companyName: 'Seshasayee Paper and Boards Ltd.' },
    { symbol: 'TNPL.NS', companyName: 'Tamil Nadu Newsprint & Papers Ltd.' },
    { symbol: 'KUANTUM.NS', companyName: 'Kuantum Papers Ltd.' },
    { symbol: 'ORIENTPPR.NS', companyName: 'Orient Paper & Industries Ltd.' },
    { symbol: 'PUDUMJEE.NS', companyName: 'Pudumjee Paper Products Ltd.' },
    { symbol: 'GENUSPAPER.NS', companyName: 'Genus Paper & Board Ltd.' },
    { symbol: 'RUCHIRA.NS', companyName: 'Ruchira Papers Ltd.' },
    { symbol: 'SATIA.NS', companyName: 'Satia Industries Ltd.' },
    { symbol: 'EMAMIPAP.NS', companyName: 'Emami Paper Mills Ltd.' },
    { symbol: 'STARPAPER.NS', companyName: 'Star Paper Mills Ltd.' },
    { symbol: 'NATHBIOGEN.NS', companyName: 'Nath Bio-Genes (India) Ltd.' },
    { symbol: 'MMTC.NS', companyName: 'MMTC Ltd.' },
    { symbol: 'STCINDIA.NS', companyName: 'The State Trading Corporation of India Ltd.' },
    { symbol: 'SANGHIIND.NS', companyName: 'Sanghi Industries Ltd.' },
    { symbol: 'HEIDELBERG.NS', companyName: 'HeidelbergCement India Ltd.' },
    { symbol: 'PRISMJOHN.NS', companyName: 'Prism Johnson Ltd.' },
    { symbol: 'KCP.NS', companyName: 'KCP Ltd.' },
    { symbol: 'NCLIND.NS', companyName: 'NCL Industries Ltd.' },
    { symbol: 'DECCANCE.NS', companyName: 'Deccan Cements Ltd.' },
    { symbol: 'ANDHRACEMT.NS', companyName: 'Andhra Cements Ltd.' },
    { symbol: 'SAGCEM.NS', companyName: 'Sagar Cements Ltd.' },
    { symbol: 'UDAICEMENT.NS', companyName: 'Udaipur Cement Works Ltd.' },
    { symbol: 'SHREDIGCEM.NS', companyName: 'Shree Digvijay Cement Co. Ltd.' },
    { symbol: 'MANGALAM.NS', companyName: 'Mangalam Cement Ltd.' },

    // --- BANKS & FINANCE ---
    { symbol: 'SOUTHBANK.NS', companyName: 'The South Indian Bank Ltd.' },
    { symbol: 'KARURVYSYA.NS', companyName: 'The Karur Vysya Bank Ltd.' },
    { symbol: 'CUB.NS', companyName: 'City Union Bank Ltd.' },
    { symbol: 'RBLBANK.NS', companyName: 'RBL Bank Ltd.' },
    { symbol: 'J&KBANK.NS', companyName: 'The Jammu & Kashmir Bank Ltd.' },
    { symbol: 'KARNATAKABN.NS', companyName: 'The Karnataka Bank Ltd.' },
    { symbol: 'CSBBANK.NS', companyName: 'CSB Bank Ltd.' },
    { symbol: 'DCBBANK.NS', companyName: 'DCB Bank Ltd.' },
    { symbol: 'DHANBANK.NS', companyName: 'Dhanlaxmi Bank Ltd.' },
    { symbol: 'FINOPB.NS', companyName: 'Fino Payments Bank Ltd.' },
    { symbol: 'SURYODAY.NS', companyName: 'Suryoday Small Finance Bank Ltd.' },
    { symbol: 'UJJIVANSFB.NS', companyName: 'Ujjivan Small Finance Bank Ltd.' },
    { symbol: 'EQUITASBNK.NS', companyName: 'Equitas Small Finance Bank Ltd.' },
    { symbol: 'ESAFSFB.NS', companyName: 'ESAF Small Finance Bank Ltd.' },
    { symbol: 'UTKARSHBNK.NS', companyName: 'Utkarsh Small Finance Bank Ltd.' },
    { symbol: 'JANA.NS', companyName: 'Jana Small Finance Bank Ltd.' },
    { symbol: 'CAPITALSFB.NS', companyName: 'Capital Small Finance Bank Ltd.' },
    { symbol: 'SHIVALIK.NS', companyName: 'Shivalik Small Finance Bank Ltd.' }, // Check listing status
    { symbol: 'UNITY.NS', companyName: 'Unity Small Finance Bank' }, // Check listing
    { symbol: 'NSDL.NS', companyName: 'NSDL Payments Bank' }, // Check listing
    { symbol: 'AIRTEL.NS', companyName: 'Airtel Payments Bank' }, // Not listed separately
    { symbol: 'PAYTM.NS', companyName: 'Paytm Payments Bank' }, // Part of One97

    // Auto Components
    { symbol: 'MOTHERSON.NS', companyName: 'Samvardhana Motherson International Ltd.' },
    { symbol: 'BOSCHLTD.NS', companyName: 'Bosch Ltd.' },
    { symbol: 'MRF.NS', companyName: 'MRF Ltd.' },
    { symbol: 'APOLLOTYRE.NS', companyName: 'Apollo Tyres Ltd.' },
    { symbol: 'BALKRISIND.NS', companyName: 'Balkrishna Industries Ltd.' },
    { symbol: 'JKTYRE.NS', companyName: 'JK Tyre & Industries Ltd.' },
    { symbol: 'CEATLTD.NS', companyName: 'CEAT Ltd.' },
    { symbol: 'GOODYEAR.NS', companyName: 'Goodyear India Ltd.' },
    { symbol: 'TVSCRICHRA.NS', companyName: 'TVS Srichakra Ltd.' },
    { symbol: 'DOLAT.NS', companyName: 'Dolat Algotech Ltd.' },
    { symbol: 'GEOJIT.NS', companyName: 'Geojit Financial Services Ltd.' },
    { symbol: '5PAISA.NS', companyName: '5Paisa Capital Ltd.' },
    { symbol: 'IIFLSEC.NS', companyName: 'IIFL Securities Ltd.' },
    { symbol: 'MOTILALOFS.NS', companyName: 'Motilal Oswal Financial Services Ltd.' },
    { symbol: 'ICICISECUR.NS', companyName: 'ICICI Securities Ltd.' }, // Delisting watch
    { symbol: 'ANGELONE.NS', companyName: 'Angel One Ltd.' },
    { symbol: 'SHAREINDIA.NS', companyName: 'Share India Securities Ltd.' },
    { symbol: 'CHOICEIN.NS', companyName: 'Choice International Ltd.' },
    { symbol: 'SMCGLOBAL.NS', companyName: 'SMC Global Securities Ltd.' },
    { symbol: 'MONARCH.NS', companyName: 'Monarch Networth Capital Ltd.' },
    { symbol: 'ALANKIT.NS', companyName: 'Alankit Ltd.' },
    { symbol: 'CSLFINANCE.NS', companyName: 'CSL Finance Ltd.' },
    { symbol: 'ARMANFIN.NS', companyName: 'Arman Financial Services Ltd.' },
    { symbol: 'MASFIN.NS', companyName: 'MAS Financial Services Ltd.' },
    { symbol: 'SPANDANA.NS', companyName: 'Spandana Sphoorty Financial Ltd.' },
    { symbol: 'CREDITACC.NS', companyName: 'CreditAccess Grameen Ltd.' },
    { symbol: 'FUSION.NS', companyName: 'Fusion Micro Finance Ltd.' },
    { symbol: 'SATIN.NS', companyName: 'Satin Creditcare Network Ltd.' },
    { symbol: 'AAVAS.NS', companyName: 'Aavas Financiers Ltd.' },
    { symbol: 'HOMEFIRST.NS', companyName: 'Home First Finance Company India Ltd.' },
    { symbol: 'AWT.NS', companyName: 'Aptus Value Housing Finance India Ltd.' }, // APTUS
    { symbol: 'APTUS.NS', companyName: 'Aptus Value Housing Finance India Ltd.' },
    { symbol: 'INDSTAR.NS', companyName: 'IndoStar Capital Finance Ltd.' },
    { symbol: 'REPCOHOME.NS', companyName: 'Repco Home Finance Ltd.' },
    { symbol: 'GICHSGFIN.NS', companyName: 'GIC Housing Finance Ltd.' },
    { symbol: 'PNEUMATIC.NS', companyName: 'Pneumatic Holdings' }, // Check symbol

    // --- INFRA ---
    { symbol: 'ADANIENT.NS', companyName: 'Adani Enterprises Ltd.' },
    { symbol: 'ADANIPORTS.NS', companyName: 'Adani Ports and Special Economic Zone Ltd.' },
    { symbol: 'GMRINFRA.NS', companyName: 'GMR Airports Infrastructure Ltd.' },
    { symbol: 'IRB.NS', companyName: 'IRB Infrastructure Developers Ltd.' },
    { symbol: 'NBCC.NS', companyName: 'NBCC (India) Ltd.' },
    { symbol: 'NCC.NS', companyName: 'NCC Ltd.' },
    { symbol: 'RVNL.NS', companyName: 'Rail Vikas Nigam Ltd.' },
    { symbol: 'IRCON.NS', companyName: 'Ircon International Ltd.' },
    { symbol: 'RITES.NS', companyName: 'RITES Ltd.' },
    { symbol: 'RAILTEL.NS', companyName: 'RailTel Corporation of India Ltd.' },
    { symbol: 'ENGINERSIN.NS', companyName: 'Engineers India Ltd.' },
    { symbol: 'PNCINFRA.NS', companyName: 'PNC Infratech Ltd.' },
    { symbol: 'KNRCON.NS', companyName: 'KNR Constructions Ltd.' },
    { symbol: 'ASHOKA.NS', companyName: 'Ashoka Buildcon Ltd.' },
    { symbol: 'GRINFRA.NS', companyName: 'G R Infraprojects Ltd.' },
    { symbol: 'HGINFRA.NS', companyName: 'H.G. Infra Engineering Ltd.' },
    { symbol: 'DILIPBUILD.NS', companyName: 'Dilip Buildcon Ltd.' },
    { symbol: 'MANINFRA.NS', companyName: 'Man Infraconstruction Ltd.' },
    { symbol: 'ITDCEM.NS', companyName: 'ITD Cementation India Ltd.' },
    { symbol: 'AHLUCONT.NS', companyName: 'Ahluwalia Contracts (India) Ltd.' },
    { symbol: 'PSPPROJECT.NS', companyName: 'PSP Projects Ltd.' },
    { symbol: 'JROBERTS.NS', companyName: 'J. Kumar Infraprojects Ltd.' }, // JKIL
    { symbol: 'JKIL.NS', companyName: 'J. Kumar Infraprojects Ltd.' },
    { symbol: 'CIGNITITEC.NS', companyName: 'Cigniti Technologies Ltd.' },

    // --- REALTY ---
    { symbol: 'DLF.NS', companyName: 'DLF Ltd.' },
    { symbol: 'LODHA.NS', companyName: 'Macrotech Developers Ltd.' },
    { symbol: 'GODREJPROP.NS', companyName: 'Godrej Properties Ltd.' },
    { symbol: 'OBEROIRLTY.NS', companyName: 'Oberoi Realty Ltd.' },
    { symbol: 'PRESTIGE.NS', companyName: 'Prestige Estates Projects Ltd.' },
    { symbol: 'PHOENIXLTD.NS', companyName: 'The Phoenix Mills Ltd.' },
    { symbol: 'BRIGADE.NS', companyName: 'Brigade Enterprises Ltd.' },
    { symbol: 'SOBHA.NS', companyName: 'Sobha Ltd.' },
    { symbol: 'MAHLIFE.NS', companyName: 'Mahindra Lifespace Developers Ltd.' },
    { symbol: 'SUNTECK.NS', companyName: 'Sunteck Realty Ltd.' },
    { symbol: 'IBREALEST.NS', companyName: 'Indiabulls Real Estate Ltd.' },
    { symbol: 'KOLTEPATIL.NS', companyName: 'Kolte-Patil Developers Ltd.' },
    { symbol: 'ASHIANA.NS', companyName: 'Ashiana Housing Ltd.' },
    { symbol: 'GANESHBE.NS', companyName: 'Ganesh Benzoplast Ltd.' },
    { symbol: 'AJMERA.NS', companyName: 'Ajmera Realty & Infra India Ltd.' },
    { symbol: 'ARIHANTSUP.NS', companyName: 'Arihant Superstructures Ltd.' },
    { symbol: 'OMAXE.NS', companyName: 'Omaxe Ltd.' },
    { symbol: 'PURVA.NS', companyName: 'Puravankara Ltd.' },
    { symbol: 'TEXINFRA.NS', companyName: 'Texmaco Infrastructure & Holdings Ltd.' },
    { symbol: 'ELDHOUSNG.NS', companyName: 'Eldeco Housing & Industries Ltd.' },

    // --- POWER ---
    { symbol: 'NTPC.NS', companyName: 'NTPC Ltd.' },
    { symbol: 'POWERGRID.NS', companyName: 'Power Grid Corporation of India Ltd.' },
    { symbol: 'ADANIPOWER.NS', companyName: 'Adani Power Ltd.' },
    { symbol: 'ADANIGREEN.NS', companyName: 'Adani Green Energy Ltd.' },
    { symbol: 'ADANIENSOL.NS', companyName: 'Adani Energy Solutions Ltd.' },
    { symbol: 'TATAPOWER.NS', companyName: 'Tata Power Company Ltd.' },
    { symbol: 'JSWENERGY.NS', companyName: 'JSW Energy Ltd.' },
    { symbol: 'NHPC.NS', companyName: 'NHPC Ltd.' },
    { symbol: 'TORNTPOWER.NS', companyName: 'Torrent Power Ltd.' },
    { symbol: 'SJVN.NS', companyName: 'SJVN Ltd.' },
    { symbol: 'NLCINDIA.NS', companyName: 'NLC India Ltd.' },
    { symbol: 'CESC.NS', companyName: 'CESC Ltd.' },
    { symbol: 'JPPOWER.NS', companyName: 'Jaiprakash Power Ventures Ltd.' },
    { symbol: 'RPOWER.NS', companyName: 'Reliance Power Ltd.' },
    { symbol: 'RTNPOWER.NS', companyName: 'RattanIndia Power Ltd.' },
    { symbol: 'IEX.NS', companyName: 'Indian Energy Exchange Ltd.' },
    { symbol: 'PTC.NS', companyName: 'PTC India Ltd.' },
    { symbol: 'SUZLON.NS', companyName: 'Suzlon Energy Ltd.' },
    { symbol: 'INOXWIND.NS', companyName: 'Inox Wind Ltd.' },
    { symbol: 'BORORENEW.NS', companyName: 'Borosil Renewables Ltd.' },
    { symbol: 'STERLINTOO.NS', companyName: 'Sterling and Wilson Renewable Energy Ltd.' },
    { symbol: 'KPIGREEN.NS', companyName: 'KPI Green Energy Ltd.' },
    { symbol: 'WAAREE.NS', companyName: 'Waaree Renewable Technologies Ltd.' },
    { symbol: 'ZODIAC.NS', companyName: 'Zodiac Energy Ltd.' },

    // --- TELECOM ---
    { symbol: 'BHARTIARTL.NS', companyName: 'Bharti Airtel Ltd.' },
    { symbol: 'IDEA.NS', companyName: 'Vodafone Idea Ltd.' },
    { symbol: 'TATACOMM.NS', companyName: 'Tata Communications Ltd.' },
    { symbol: 'INDUSTOWER.NS', companyName: 'Indus Towers Ltd.' },
    { symbol: 'HFCL.NS', companyName: 'HFCL Ltd.' },
    { symbol: 'ITI.NS', companyName: 'ITI Ltd.' },
    { symbol: 'TEJASNET.NS', companyName: 'Tejas Networks Ltd.' },
    { symbol: 'MTNL.NS', companyName: 'Mahanagar Telephone Nigam Ltd.' },
    { symbol: 'TTML.NS', companyName: 'Tata Teleservices (Maharashtra) Ltd.' },
    { symbol: 'ONMOBILE.NS', companyName: 'OnMobile Global Ltd.' },
    { symbol: 'RAILTEL.NS', companyName: 'RailTel Corporation of India Ltd.' },
    { symbol: 'STLTECH.NS', companyName: 'Sterlite Technologies Ltd.' },
    { symbol: 'VINDHYATEL.NS', companyName: 'Vindhya Telelinks Ltd.' },
    { symbol: 'GTPL.NS', companyName: 'GTPL Hathway Ltd.' },
    { symbol: 'HATHWAY.NS', companyName: 'Hathway Cable & Datacom Ltd.' },
    { symbol: 'DEN.NS', companyName: 'Den Networks Ltd.' },
    { symbol: 'DISHTV.NS', companyName: 'Dish TV India Ltd.' },
    { symbol: 'SUNTV.NS', companyName: 'Sun TV Network Ltd.' },
    { symbol: 'ZEEL.NS', companyName: 'Zee Entertainment Enterprises Ltd.' },
    { symbol: 'TV18BRDCST.NS', companyName: 'TV18 Broadcast Ltd.' },
    { symbol: 'NETWORK18.NS', companyName: 'Network18 Media & Investments Ltd.' },
    { symbol: 'DBCORP.NS', companyName: 'D.B. Corp Ltd.' },
    { symbol: 'JAGRAN.NS', companyName: 'Jagran Prakashan Ltd.' },
    { symbol: 'HTMEDIA.NS', companyName: 'HT Media Ltd.' },
    { symbol: 'HITECH.NS', companyName: 'Hi-Tech Pipes Ltd.' },

    // --- TEXTILES ---
    { symbol: 'PAGEIND.NS', companyName: 'Page Industries Ltd.' },
    { symbol: 'LUXIND.NS', companyName: 'Lux Industries Ltd.' },
    { symbol: 'RUPA.NS', companyName: 'Rupa & Company Ltd.' },
    { symbol: 'DOLLAR.NS', companyName: 'Dollar Industries Ltd.' },
    { symbol: 'KPRMILL.NS', companyName: 'K.P.R. Mill Ltd.' },
    { symbol: 'WELSPUNLIV.NS', companyName: 'Welspun Living Ltd.' },
    { symbol: 'TRIDENT.NS', companyName: 'Trident Ltd.' },
    { symbol: 'RAYMOND.NS', companyName: 'Raymond Ltd.' },
    { symbol: 'ARVIND.NS', companyName: 'Arvind Ltd.' },
    { symbol: 'VARDHMAN.NS', companyName: 'Vardhman Textiles Ltd.' },
    { symbol: 'ALOKINDS.NS', companyName: 'Alok Industries Ltd.' },
    { symbol: 'SUTLEJTEX.NS', companyName: 'Sutlej Textiles and Industries Ltd.' },
    { symbol: 'RSWM.NS', companyName: 'RSWM Ltd.' },
    { symbol: 'FILATEX.NS', companyName: 'Filatex India Ltd.' },
    { symbol: 'JINDWORLD.NS', companyName: 'Jindal Worldwide Ltd.' },
    { symbol: 'SWANENERGY.NS', companyName: 'Swan Energy Ltd.' },
    { symbol: 'GOCLCORP.NS', companyName: 'GOCL Corporation Ltd.' },
    { symbol: 'BOMBAYDYE.NS', companyName: 'The Bombay Dyeing and Manufacturing Company Ltd.' },
    { symbol: 'CENTURYTEX.NS', companyName: 'Century Textiles and Industries Ltd.' },
    { symbol: 'GRASIM.NS', companyName: 'Grasim Industries Ltd.' },
    { symbol: 'SRF.NS', companyName: 'SRF Ltd.' },
    { symbol: 'GARFIBRES.NS', companyName: 'Garware Technical Fibres Ltd.' },
    { symbol: 'JINDALPOLY.NS', companyName: 'Jindal Poly Films Ltd.' },
    { symbol: 'TCNSBRANDS.NS', companyName: 'TCNS Clothing Co. Ltd.' },
    { symbol: 'GOKEX.NS', companyName: 'Gokaldas Exports Ltd.' },
    { symbol: 'SPAL.NS', companyName: 'S.P. Apparels Ltd.' },
    { symbol: 'KITEX.NS', companyName: 'Kitex Garments Ltd.' },
    { symbol: 'MONTECARLO.NS', companyName: 'Monte Carlo Fashions Ltd.' },
    { symbol: 'CANTABIL.NS', companyName: 'Cantabil Retail India Ltd.' },
    { symbol: 'VMANYAVAR.NS', companyName: 'Vedant Fashions Ltd.' },
    { symbol: 'MANYAVAR.NS', companyName: 'Vedant Fashions Ltd.' }, // Dup check
    { symbol: 'CAMPUS.NS', companyName: 'Campus Activewear Ltd.' },
    { symbol: 'METROBRAND.NS', companyName: 'Metro Brands Ltd.' },

    // --- CONSUMER DURABLES ---
    { symbol: 'TITAN.NS', companyName: 'Titan Company Ltd.' },
    { symbol: 'HAVELLS.NS', companyName: 'Havells India Ltd.' },
    { symbol: 'VOLTAS.NS', companyName: 'Voltas Ltd.' },
    { symbol: 'WHIRLPOOL.NS', companyName: 'Whirlpool of India Ltd.' },
    { symbol: 'CROMPTON.NS', companyName: 'Crompton Greaves Consumer Electricals Ltd.' },
    { symbol: 'BLUESTARCO.NS', companyName: 'Blue Star Ltd.' },
    { symbol: 'KAJARIACER.NS', companyName: 'Kajaria Ceramics Ltd.' },
    { symbol: 'CERA.NS', companyName: 'Cera Sanitaryware Ltd.' },
    { symbol: 'SOMANYCERA.NS', companyName: 'Somany Ceramics Ltd.' },
    { symbol: 'CENTURYPLY.NS', companyName: 'Century Plyboards (India) Ltd.' },
    { symbol: 'GREENPLY.NS', companyName: 'Greenply Industries Ltd.' },
    { symbol: 'GREENPANEL.NS', companyName: 'Greenpanel Industries Ltd.' },
    { symbol: 'SYMPHONY.NS', companyName: 'Symphony Ltd.' },
    { symbol: 'ORIENTELEC.NS', companyName: 'Orient Electric Ltd.' },
    { symbol: 'VGUARD.NS', companyName: 'V-Guard Industries Ltd.' },
    { symbol: 'BAJAJELEC.NS', companyName: 'Bajaj Electricals Ltd.' },
    { symbol: 'IFBIND.NS', companyName: 'IFB Industries Ltd.' },
    { symbol: 'TTKPRESTIG.NS', companyName: 'TTK Prestige Ltd.' },
    { symbol: 'HAWKINS.NS', companyName: 'Hawkins Cookers Ltd.' },
    { symbol: 'STOVEKRAFT.NS', companyName: 'Stove Kraft Ltd.' },
    { symbol: 'BUTTERFLY.NS', companyName: 'Butterfly Gandhimathi Appliances Ltd.' },
    { symbol: 'BOROLTD.NS', companyName: 'Borosil Ltd.' },
    { symbol: 'LAOPALA.NS', companyName: 'La Opala RG Ltd.' },
    { symbol: 'VIPIND.NS', companyName: 'VIP Industries Ltd.' },
    { symbol: 'SAFARI.NS', companyName: 'Safari Industries (India) Ltd.' },

    // --- JEWELLERY ---
    { symbol: 'KALYANKJIL.NS', companyName: 'Kalyan Jewellers India Ltd.' },
    { symbol: 'RAJESHEXPO.NS', companyName: 'Rajesh Exports Ltd.' },
    { symbol: 'VAIBHAVGBL.NS', companyName: 'Vaibhav Global Ltd.' },
    { symbol: 'GOLDIAM.NS', companyName: 'Goldiam International Ltd.' },
    { symbol: 'RENAISSANCE.NS', companyName: 'Renaissance Global Ltd.' },
    { symbol: 'PCJEWELLER.NS', companyName: 'PC Jeweller Ltd.' },
    { symbol: 'THANGAMAYL.NS', companyName: 'Thangamayil Jewellery Ltd.' },
    { symbol: 'SENCO.NS', companyName: 'Senco Gold Ltd.' },
    { symbol: 'ETHOSLTD.NS', companyName: 'Ethos Ltd.' },
    { symbol: 'KDDL.NS', companyName: 'KDDL Ltd.' },

    // --- HOSPITALITY ---
    { symbol: 'INDHOTEL.NS', companyName: 'The Indian Hotels Company Ltd.' },
    { symbol: 'EIHOTEL.NS', companyName: 'EIH Ltd.' },
    { symbol: 'CHALET.NS', companyName: 'Chalet Hotels Ltd.' },
    { symbol: 'LEMONTREE.NS', companyName: 'Lemon Tree Hotels Ltd.' },
    { symbol: 'MAHINDCIE.NS', companyName: 'Mahindra CIE Automotive Ltd.' }, // CIEINDIA now

    // --- MISC ---
    { symbol: 'AFFLE.NS', companyName: 'Affle (India) Ltd.' },
    { symbol: 'INDIAMART.NS', companyName: 'IndiaMART InterMESH Ltd.' },
    { symbol: 'JUSTDIAL.NS', companyName: 'Just Dial Ltd.' },
    { symbol: 'NAZARA.NS', companyName: 'Nazara Technologies Ltd.' },
    { symbol: 'EASEMYTRIP.NS', companyName: 'Easy Trip Planners Ltd.' },
    { symbol: 'YATRA.NS', companyName: 'Yatra Online Ltd.' },
    { symbol: 'RATEGAIN.NS', companyName: 'RateGain Travel Technologies Ltd.' },
    { symbol: 'MAPMYINDIA.NS', companyName: 'C.E. Info Systems Ltd.' },
    { symbol: 'LATENTVIEW.NS', companyName: 'Latent View Analytics Ltd.' },
    { symbol: 'HAPPSTMNDS.NS', companyName: 'Happiest Minds Technologies Ltd.' },
    { symbol: 'ZOMATO.NS', companyName: 'Zomato Ltd.' },
    { symbol: 'PAYTM.NS', companyName: 'One97 Communications Ltd.' },
    { symbol: 'POLICYBZR.NS', companyName: 'PB Fintech Ltd.' },
    { symbol: 'NYKAA.NS', companyName: 'FSN E-Commerce Ventures Ltd. (Nykaa)' },
    { symbol: 'DELHIVERY.NS', companyName: 'Delhivery Ltd.' },
    { symbol: 'CARTRADE.NS', companyName: 'CarTrade Tech Ltd.' },
    { symbol: 'FINO.NS', companyName: 'Fino Payments Bank Ltd.' }, // FINOPB
    { symbol: 'EMUDHRA.NS', companyName: 'eMudhra Ltd.' },
    { symbol: 'TRACTION.NS', companyName: 'Tracxn Technologies Ltd.' },
    { symbol: 'IDEA.NS', companyName: 'Vodafone Idea Ltd.' },
];
