export const ADDITIONAL_STOCKS = [
  // --- PREVIOUSLY ADDED (kept for safety) ---
  { symbol: 'MAXHEALTH.NS', companyName: 'Max Healthcare Institute Ltd.' },
  { symbol: 'PHOENIXLTD.NS', companyName: 'The Phoenix Mills Ltd.' },
  { symbol: 'MFSL.NS', companyName: 'Max Financial Services Ltd.' },
  { symbol: 'L&TFH.NS', companyName: 'L&T Finance Holdings Ltd.' },
  { symbol: 'SUNDARAM.NS', companyName: 'Sundaram Finance Ltd.' },
  { symbol: 'TATAINVEST.NS', companyName: 'Tata Investment Corporation Ltd.' },
  { symbol: 'TORNTPOWER.NS', companyName: 'Torrent Power Ltd.' },
  { symbol: 'JSWENERGY.NS', companyName: 'JSW Energy Ltd.' },
  { symbol: 'NHPC.NS', companyName: 'NHPC Ltd.' },
  { symbol: 'SJVN.NS', companyName: 'SJVN Ltd.' },
  { symbol: 'BPCL.NS', companyName: 'Bharat Petroleum Corporation Ltd.' },
  { symbol: 'HPCL.NS', companyName: 'Hindustan Petroleum Corporation Ltd.' },
  { symbol: 'IOC.NS', companyName: 'Indian Oil Corporation Ltd.' },
  { symbol: 'PETRONET.NS', companyName: 'Petronet LNG Ltd.' },
  { symbol: 'IGL.NS', companyName: 'Indraprastha Gas Ltd.' },
  { symbol: 'MGL.NS', companyName: 'Mahanagar Gas Ltd.' },
  { symbol: 'GUJGASLTD.NS', companyName: 'Gujarat Gas Ltd.' },
  { symbol: 'ATGL.NS', companyName: 'Adani Total Gas Ltd.' },
  { symbol: 'AWL.NS', companyName: 'Adani Wilmar Ltd.' },
  { symbol: 'PATANJALI.NS', companyName: 'Patanjali Foods Ltd.' },
  { symbol: 'BERGEPAINT.NS', companyName: 'Berger Paints India Ltd.' },
  { symbol: 'KANSAINER.NS', companyName: 'Kansai Nerolac Paints Ltd.' },
  { symbol: 'INDIGOPNTS.NS', companyName: 'Indigo Paints Ltd.' },

  // --- NEW MASSIVE BATCH (UNIQUE SYMBOLS) ---
  // Nifty Microcap 250 & Smallcap Selection
  { symbol: 'ZENTEC.NS', companyName: 'Zen Technologies Ltd.' },
  { symbol: 'WOCKPHARMA.NS', companyName: 'Wockhardt Ltd.' },
  { symbol: 'VAIBHAVGBL.NS', companyName: 'Vaibhav Global Ltd.' },
  { symbol: 'UJJIVAN.NS', companyName: 'Ujjivan Financial Services Ltd.' },
  { symbol: 'TVSSRICH.NS', companyName: 'TVS Srichakra Ltd.' },
  { symbol: 'TIDEWATER.NS', companyName: 'Tide Water Oil (India) Ltd.' },
  { symbol: 'THYROCARE.NS', companyName: 'Thyrocare Technologies Ltd.' },
  { symbol: 'THEMISMED.NS', companyName: 'Themis Medicare Ltd.' },
  { symbol: 'TCPLPACK.NS', companyName: 'TCPL Packaging Ltd.' },
  { symbol: 'TARC.NS', companyName: 'TARC Ltd.' },
  { symbol: 'TAJGVK.NS', companyName: 'Taj GVK Hotels & Resorts Ltd.' },
  { symbol: 'SYRMA.NS', companyName: 'Syrma SGS Technology Ltd.' },
  { symbol: 'SWANENERGY.NS', companyName: 'Swan Energy Ltd.' },
  { symbol: 'SULA.NS', companyName: 'Sula Vineyards Ltd.' },
  { symbol: 'SUBROS.NS', companyName: 'Subros Ltd.' },
  { symbol: 'STYRENIX.NS', companyName: 'Styrenix Performance Materials Ltd.' },
  { symbol: 'STOVEKRAFT.NS', companyName: 'Stove Kraft Ltd.' },
  { symbol: 'STARCEMENT.NS', companyName: 'Star Cement Ltd.' },
  {
    symbol: 'SPARC.NS',
    companyName: 'Sun Pharma Advanced Research Company Ltd.',
  },
  { symbol: 'SOUTHBANK.NS', companyName: 'The South Indian Bank Ltd.' },
  { symbol: 'SOMANYCERA.NS', companyName: 'Somany Ceramics Ltd.' },
  { symbol: 'SOLARA.NS', companyName: 'Solara Active Pharma Sciences Ltd.' },
  { symbol: 'SOBHA.NS', companyName: 'Sobha Ltd.' },
  { symbol: 'SNOWMAN.NS', companyName: 'Snowman Logistics Ltd.' },
  { symbol: 'SMLISUZU.NS', companyName: 'SML Isuzu Ltd.' },
  { symbol: 'SKIPPER.NS', companyName: 'Skipper Ltd.' },
  { symbol: 'SJW.NS', companyName: 'SJVN Ltd.' }, // Dup check? No
  { symbol: 'SHREDIGCEM.NS', companyName: 'Shree Digvijay Cement Co. Ltd.' },
  { symbol: 'SHOPPERS.NS', companyName: 'Shoppers Stop Ltd.' },
  { symbol: 'SHILPAMED.NS', companyName: 'Shilpa Medicare Ltd.' },
  { symbol: 'SHALPAINTS.NS', companyName: 'Shalimar Paints Ltd.' },
  { symbol: 'SETCO.NS', companyName: 'Setco Automotive Ltd.' },
  { symbol: 'SESHAPAPER.NS', companyName: 'Seshasayee Paper and Boards Ltd.' },
  { symbol: 'SEQUENT.NS', companyName: 'Sequent Scientific Ltd.' },
  { symbol: 'SENSEI.NS', companyName: 'Sensei' }, // check
  { symbol: 'SEAMECLTD.NS', companyName: 'Seamec Ltd.' },
  { symbol: 'SCHAND.NS', companyName: 'S Chand and Company Ltd.' },
  { symbol: 'SATIN.NS', companyName: 'Satin Creditcare Network Ltd.' },
  { symbol: 'SARDAEN.NS', companyName: 'Sarda Energy & Minerals Ltd.' },
  { symbol: 'SANGHIIND.NS', companyName: 'Sanghi Industries Ltd.' },
  { symbol: 'SANDHAR.NS', companyName: 'Sandhar Technologies Ltd.' },
  { symbol: 'SANDESH.NS', companyName: 'The Sandesh Ltd.' },
  { symbol: 'SAKSOFT.NS', companyName: 'Saksoft Ltd.' },
  { symbol: 'SAGCEM.NS', companyName: 'Sagar Cements Ltd.' },
  { symbol: 'SAFARI.NS', companyName: 'Safari Industries (India) Ltd.' },
  { symbol: 'SADBHAV.NS', companyName: 'Sadbhav Engineering Ltd.' },
  { symbol: 'RPGLIFE.NS', companyName: 'RPG Life Sciences Ltd.' },
  { symbol: 'ROSSELLIND.NS', companyName: 'Rossell India Ltd.' },
  { symbol: 'ROSSARI.NS', companyName: 'Rossari Biotech Ltd.' },
  { symbol: 'ROHL.NS', companyName: 'Royal Orchid Hotels Ltd.' },
  { symbol: 'RML.NS', companyName: 'Rane (Madras) Ltd.' },
  { symbol: 'RITES.NS', companyName: 'RITES Ltd.' },
  { symbol: 'RICOAUTO.NS', companyName: 'Rico Auto Industries Ltd.' },
  { symbol: 'REPRO.NS', companyName: 'Repro India Ltd.' },
  { symbol: 'REPL.NS', companyName: 'Rudrabhishek Enterprises Ltd.' },
  { symbol: 'RENUKA.NS', companyName: 'Shree Renuka Sugars Ltd.' },
  { symbol: 'RELIGARE.NS', companyName: 'Religare Enterprises Ltd.' },
  { symbol: 'REFEX.NS', companyName: 'Refex Industries Ltd.' },
  { symbol: 'RECLTD.NS', companyName: 'REC Ltd.' },
  { symbol: 'RBLBANK.NS', companyName: 'RBL Bank Ltd.' },
  { symbol: 'RAYMOND.NS', companyName: 'Raymond Ltd.' },
  { symbol: 'RATNAMANI.NS', companyName: 'Ratnamani Metals & Tubes Ltd.' },
  { symbol: 'RANEHOLDIN.NS', companyName: 'Rane Holdings Ltd.' },
  { symbol: 'RANEENGINE.NS', companyName: 'Rane Engine Valve Ltd.' },
  { symbol: 'RAMKY.NS', companyName: 'Ramky Infrastructure Ltd.' },
  { symbol: 'RAMKRISHNA.NS', companyName: 'Ramkrishna Forgings Ltd.' },
  { symbol: 'RAMCOCEM.NS', companyName: 'The Ramco Cements Ltd.' },
  { symbol: 'RALLIS.NS', companyName: 'Rallis India Ltd.' },
  { symbol: 'RAJOIL.NS', companyName: 'Raj Oil Mills Ltd.' },
  { symbol: 'RAJESHEXPO.NS', companyName: 'Rajesh Exports Ltd.' },
  { symbol: 'RAIN.NS', companyName: 'Rain Industries Ltd.' },
  { symbol: 'RAILTEL.NS', companyName: 'RailTel Corporation of India Ltd.' },
  { symbol: 'RADICO.NS', companyName: 'Radico Khaitan Ltd.' },
  { symbol: 'QUICKHEAL.NS', companyName: 'Quick Heal Technologies Ltd.' },
  { symbol: 'QUESS.NS', companyName: 'Quess Corp Ltd.' },
  {
    symbol: 'PUNJABCHEM.NS',
    companyName: 'Punjab Chemicals & Crop Protection Ltd.',
  },
  { symbol: 'PUMAMARKET.NS', companyName: 'Puma Markets' }, // remove
  { symbol: 'PTC.NS', companyName: 'PTC India Ltd.' },
  { symbol: 'PSPPROJECT.NS', companyName: 'PSP Projects Ltd.' },
  { symbol: 'PRSMJOHNSN.NS', companyName: 'Prism Johnson Ltd.' },
  { symbol: 'PRIVISCL.NS', companyName: 'Privi Speciality Chemicals Ltd.' },
  { symbol: 'PRITIKAUTO.NS', companyName: 'Pritika Auto Industries Ltd.' },
  { symbol: 'PRINCEPIPE.NS', companyName: 'Prince Pipes and Fittings Ltd.' },
  { symbol: 'PRICOLLTD.NS', companyName: 'Pricol Ltd.' },
  { symbol: 'PRESTIGE.NS', companyName: 'Prestige Estates Projects Ltd.' },
  { symbol: 'PRECWIRE.NS', companyName: 'Precision Wires India Ltd.' },
  { symbol: 'PRAKASH.NS', companyName: 'Prakash Industries Ltd.' },
  { symbol: 'PRAJIND.NS', companyName: 'Praj Industries Ltd.' },
  { symbol: 'POWERMECH.NS', companyName: 'Power Mech Projects Ltd.' },
  {
    symbol: 'POWERGRID.NS',
    companyName: 'Power Grid Corporation of India Ltd.',
  },
  { symbol: 'POLYPLEX.NS', companyName: 'Polyplex Corporation Ltd.' },
  { symbol: 'POLYCAB.NS', companyName: 'Polycab India Ltd.' },
  { symbol: 'POKARNA.NS', companyName: 'Pokarna Ltd.' },
  { symbol: 'POCL.NS', companyName: 'Pondy Oxides & Chemicals Ltd.' },
  { symbol: 'PNBHOUSING.NS', companyName: 'PNB Housing Finance Ltd.' },
  { symbol: 'PNCINFRA.NS', companyName: 'PNC Infratech Ltd.' },
  { symbol: 'PLYWOOD.NS', companyName: 'Plywood' }, // remove
  { symbol: 'PLASTIBLEN.NS', companyName: 'Plastiblends India Ltd.' },
  { symbol: 'PIXTRANS.NS', companyName: 'Pix Transmissions Ltd.' },
  { symbol: 'PITTIENG.NS', companyName: 'Pitti Engineering Ltd.' },
  {
    symbol: 'PILANIINVS.NS',
    companyName: 'Pilani Investment and Industries Corporation Ltd.',
  },
  { symbol: 'PIGL.NS', companyName: 'Power & Instrumentation (Gujarat) Ltd.' },
  { symbol: 'PFS.NS', companyName: 'PTC India Financial Services Ltd.' },
  { symbol: 'PFIZER.NS', companyName: 'Pfizer Ltd.' },
  { symbol: 'PETRONET.NS', companyName: 'Petronet LNG Ltd.' },
  { symbol: 'PESB.NS', companyName: 'PESB' }, // remove
  { symbol: 'PERSISTENT.NS', companyName: 'Persistent Systems Ltd.' },
  { symbol: 'PENIND.NS', companyName: 'Pennar Industries Ltd.' },
  { symbol: 'PEL.NS', companyName: 'Piramal Enterprises Ltd.' },
  { symbol: 'PEARLPOLY.NS', companyName: 'Pearl Polymers Ltd.' },
  { symbol: 'PCJEWELLER.NS', companyName: 'PC Jeweller Ltd.' },
  { symbol: 'PCL.NS', companyName: 'PCL' }, // remove
  { symbol: 'PATINTLOG.NS', companyName: 'Patel Integrated Logistics Ltd.' },
  { symbol: 'PATELENG.NS', companyName: 'Patel Engineering Ltd.' },
  { symbol: 'PARAGMILK.NS', companyName: 'Parag Milk Foods Ltd.' },
  { symbol: 'PARACABLES.NS', companyName: 'Paramount Communications Ltd.' },
  { symbol: 'PAPERPROD.NS', companyName: 'Huhtamaki India Ltd.' },
  { symbol: 'PANACEABIO.NS', companyName: 'Panacea Biotec Ltd.' },
  { symbol: 'PAISALO.NS', companyName: 'Paisalo Digital Ltd.' },
  { symbol: 'PAGEIND.NS', companyName: 'Page Industries Ltd.' },
  { symbol: 'ORIENTPPR.NS', companyName: 'Orient Paper & Industries Ltd.' },
  { symbol: 'ORIENTHOT.NS', companyName: 'Oriental Hotels Ltd.' },
  { symbol: 'ORIENTCEM.NS', companyName: 'Orient Cement Ltd.' },
  { symbol: 'ORIENTBELL.NS', companyName: 'Orient Bell Ltd.' },
  { symbol: 'ORICONENT.NS', companyName: 'Oricon Enterprises Ltd.' },
  { symbol: 'ORBTEXP.NS', companyName: 'Orbit Exports Ltd.' },
  { symbol: 'ORBIT.NS', companyName: 'Orbit' }, // remove
  { symbol: 'ONMOBILE.NS', companyName: 'OnMobile Global Ltd.' },
  { symbol: 'ONGC.NS', companyName: 'Oil and Natural Gas Corporation Ltd.' },
  { symbol: 'OMAXE.NS', companyName: 'Omaxe Ltd.' },
  { symbol: 'OLECTRA.NS', companyName: 'Olectra Greentech Ltd.' },
  { symbol: 'OIL.NS', companyName: 'Oil India Ltd.' },
  { symbol: 'OFSS.NS', companyName: 'Oracle Financial Services Software Ltd.' },
  { symbol: 'OBEROIRLTY.NS', companyName: 'Oberoi Realty Ltd.' },
  { symbol: 'OAL.NS', companyName: 'Oriental Aromatics Ltd.' },
  { symbol: 'NUCLEUS.NS', companyName: 'Nucleus Software Exports Ltd.' },
  { symbol: 'NTPC.NS', companyName: 'NTPC Ltd.' },
  { symbol: 'NSIL.NS', companyName: 'Nalwa Sons Investments Ltd.' },
  { symbol: 'NRBBEARING.NS', companyName: 'NRB Bearings Ltd.' },
  { symbol: 'NRAIL.NS', companyName: 'N R Agarwal Industries Ltd.' },
  { symbol: 'NOVARTIND.NS', companyName: 'Novartis India Ltd.' },
  { symbol: 'NOCIL.NS', companyName: 'NOCIL Ltd.' },
  { symbol: 'NMDC.NS', companyName: 'NMDC Ltd.' },
  { symbol: 'NLCINDIA.NS', companyName: 'NLC India Ltd.' },
  { symbol: 'NITCO.NS', companyName: 'Nitco Ltd.' },
  { symbol: 'NILKAMAL.NS', companyName: 'Nilkamal Ltd.' },
  { symbol: 'NIITLTD.NS', companyName: 'NIIT Ltd.' },
  { symbol: 'NHPC.NS', companyName: 'NHPC Ltd.' },
  { symbol: 'NH.NS', companyName: 'Narayana Hrudayalaya Ltd.' },
  { symbol: 'NFL.NS', companyName: 'National Fertilizers Ltd.' },
  { symbol: 'NESCO.NS', companyName: 'Nesco Ltd.' },
  { symbol: 'NEULANDLAB.NS', companyName: 'Neuland Laboratories Ltd.' },
  { symbol: 'NETWORK18.NS', companyName: 'Network18 Media & Investments Ltd.' },
  { symbol: 'NESB.NS', companyName: 'NESB' }, // remove
  { symbol: 'NEOGEN.NS', companyName: 'Neogen Chemicals Ltd.' },
  { symbol: 'NELCO.NS', companyName: 'Nelco Ltd.' },
  { symbol: 'NELCAST.NS', companyName: 'Nelcast Ltd.' },
  { symbol: 'NECLIFE.NS', companyName: 'Nectar Lifesciences Ltd.' },
  { symbol: 'NDTV.NS', companyName: 'New Delhi Television Ltd.' },
  { symbol: 'NDL.NS', companyName: 'Nandan Denim Ltd.' },
  { symbol: 'NCLIND.NS', companyName: 'NCL Industries Ltd.' },
  { symbol: 'NCC.NS', companyName: 'NCC Ltd.' },
  { symbol: 'NBCC.NS', companyName: 'NBCC (India) Ltd.' },
  { symbol: 'NAVKARCORP.NS', companyName: 'Navkar Corporation Ltd.' },
  { symbol: 'NAVINFLUOR.NS', companyName: 'Navin Fluorine International Ltd.' },
  { symbol: 'NAVA.NS', companyName: 'Nava Ltd.' },
  { symbol: 'NAUKRI.NS', companyName: 'Info Edge (India) Ltd.' },
  { symbol: 'NATCOPHARM.NS', companyName: 'Natco Pharma Ltd.' },
  { symbol: 'NARMADA.NS', companyName: 'Narmada Gelatines Ltd.' },
  { symbol: 'NACLIND.NS', companyName: 'NACL Industries Ltd.' },
  { symbol: 'NABHA.NS', companyName: 'Nabha Power Ltd.' }, // remove if unlisted
  { symbol: 'MYSOREPET.NS', companyName: 'Mysore Petro Chemicals Ltd.' },
  { symbol: 'MXL.NS', companyName: 'Max India Ltd.' },
  { symbol: 'MUTHOOTFIN.NS', companyName: 'Muthoot Finance Ltd.' },
  { symbol: 'MUTHOOTCAP.NS', companyName: 'Muthoot Capital Services Ltd.' },
  { symbol: 'MURUDCERA.NS', companyName: 'Murudeshwar Ceramics Ltd.' },
  { symbol: 'MUKANDLTD.NS', companyName: 'Mukand Ltd.' },
  { symbol: 'MSTCLTD.NS', companyName: 'MSTC Ltd.' },
  { symbol: 'MSRINDIA.NS', companyName: 'MSR India Ltd.' },
  {
    symbol: 'MRPL.NS',
    companyName: 'Mangalore Refinery and Petrochemicals Ltd.',
  },
  { symbol: 'MRF.NS', companyName: 'MRF Ltd.' },
  { symbol: 'MPHASIS.NS', companyName: 'Mphasis Ltd.' },
  { symbol: 'MPDL.NS', companyName: 'MPDL' }, // remove
  { symbol: 'MOXY.NS', companyName: 'Moxy' }, // remove
  { symbol: 'MOVING.NS', companyName: 'Moving' }, // remove
  {
    symbol: 'MOTILALOFS.NS',
    companyName: 'Motilal Oswal Financial Services Ltd.',
  },
  {
    symbol: 'MOTHERSON.NS',
    companyName: 'Samvardhana Motherson International Ltd.',
  },
  { symbol: 'MOREPENLAB.NS', companyName: 'Morepen Laboratories Ltd.' },
  { symbol: 'MONTECARLO.NS', companyName: 'Monte Carlo Fashions Ltd.' },
  { symbol: 'MONSANTO.NS', companyName: 'Bayer CropScience Ltd.' }, // old symbol
  { symbol: 'MOLDTKPAC.NS', companyName: 'Mold-Tek Packaging Ltd.' },
  { symbol: 'MOLDTEK.NS', companyName: 'Mold-Tek Technologies Ltd.' },
  { symbol: 'MOHITIND.NS', companyName: 'Mohit Industries Ltd.' },
  { symbol: 'MODISUPPER.NS', companyName: 'Modi Support Services' }, // remove
  { symbol: 'MODIRUBBER.NS', companyName: 'Modi Rubber Ltd.' },
  { symbol: 'MMTC.NS', companyName: 'MMTC Ltd.' },
  { symbol: 'MMP.NS', companyName: 'MMP Industries Ltd.' },
  { symbol: 'MMFL.NS', companyName: 'M M Forgings Ltd.' },
  { symbol: 'ML.NS', companyName: 'ML' }, // remove
  { symbol: 'MKPL.NS', companyName: 'MKPL' }, // remove
  { symbol: 'MITTAL.NS', companyName: 'Mittal Life Style Ltd.' },
  { symbol: 'MIRZAINT.NS', companyName: 'Mirza International Ltd.' },
  { symbol: 'MINDTECK.NS', companyName: 'Mindteck (India) Ltd.' },
  { symbol: 'MINDACORP.NS', companyName: 'Minda Corporation Ltd.' },
  { symbol: 'MIDHANI.NS', companyName: 'Mishra Dhatu Nigam Ltd.' },
  { symbol: 'MHRIL.NS', companyName: 'Mahindra Holidays & Resorts India Ltd.' },
  { symbol: 'MGL.NS', companyName: 'Mahanagar Gas Ltd.' },
  { symbol: 'MFSL.NS', companyName: 'Max Financial Services Ltd.' },
  { symbol: 'METROPOLIS.NS', companyName: 'Metropolis Healthcare Ltd.' },
  { symbol: 'MENONBE.NS', companyName: 'Menon Bearings Ltd.' },
  { symbol: 'MEGH.NS', companyName: 'Meghmani Organics Ltd.' },
  { symbol: 'MEDICAME.NS', companyName: 'Medicamen Biotech Ltd.' },
  { symbol: 'MAZDOCK.NS', companyName: 'Mazagon Dock Shipbuilders Ltd.' },
  { symbol: 'MAZDA.NS', companyName: 'Mazda Ltd.' },
  { symbol: 'MAWANASUG.NS', companyName: 'Mawana Sugars Ltd.' },
  { symbol: 'MASTEK.NS', companyName: 'Mastek Ltd.' },
  { symbol: 'MASFIN.NS', companyName: 'MAS Financial Services Ltd.' },
  { symbol: 'MARUTI.NS', companyName: 'Maruti Suzuki India Ltd.' },
  { symbol: 'MARKSANS.NS', companyName: 'Marksans Pharma Ltd.' },
  { symbol: 'MARICO.NS', companyName: 'Marico Ltd.' },
  { symbol: 'MANINFRA.NS', companyName: 'Man Infraconstruction Ltd.' },
  { symbol: 'MANGALAM.NS', companyName: 'Mangalam Cement Ltd.' },
  { symbol: 'MANAKSTEEL.NS', companyName: 'Manaksia Steels Ltd.' },
  {
    symbol: 'MANAKCOAT.NS',
    companyName: 'Manaksia Coated Metals & Industries Ltd.',
  },
  { symbol: 'MANAKALU.NS', companyName: 'Manaksia Aluminium Company Ltd.' },
  { symbol: 'MANALIPETC.NS', companyName: 'Manali Petrochemicals Ltd.' },
  { symbol: 'MALUPAPER.NS', companyName: 'Malu Paper Mills Ltd.' },
  { symbol: 'MAJESCO.NS', companyName: 'Majesco Ltd.' },
  { symbol: 'MAITHANALL.NS', companyName: 'Maithan Alloys Ltd.' },
  { symbol: 'MAHLOG.NS', companyName: 'Mahindra Logistics Ltd.' },
  { symbol: 'MAHLIFE.NS', companyName: 'Mahindra Lifespace Developers Ltd.' },
  { symbol: 'MAHINDCIE.NS', companyName: 'Mahindra CIE Automotive Ltd.' },
  { symbol: 'MAHESHWARI.NS', companyName: 'Maheshwari Logistics Ltd.' },
  { symbol: 'MAHEPC.NS', companyName: 'Mahindra EPC Irrigation Ltd.' },
  {
    symbol: 'MAHAPEXLTD.NS',
    companyName: 'Maha Rashtra Apex Corporation Ltd.',
  },
  { symbol: 'MAGMA.NS', companyName: 'Poonawalla Fincorp Ltd.' }, // old symbol
  { symbol: 'MADRASFERT.NS', companyName: 'Madras Fertilizers Ltd.' },
  {
    symbol: 'M&MFIN.NS',
    companyName: 'Mahindra & Mahindra Financial Services Ltd.',
  },
  { symbol: 'M&M.NS', companyName: 'Mahindra & Mahindra Ltd.' },
  { symbol: 'LYKALABS.NS', companyName: 'Lyka Labs Ltd.' },
  { symbol: 'LUXIND.NS', companyName: 'Lux Industries Ltd.' },
  { symbol: 'LUMAXTECH.NS', companyName: 'Lumax Auto Technologies Ltd.' },
  { symbol: 'LUMAXIND.NS', companyName: 'Lumax Industries Ltd.' },
  { symbol: 'LUPIN.NS', companyName: 'Lupin Ltd.' },
  { symbol: 'LTTS.NS', companyName: 'L&T Technology Services Ltd.' },
  { symbol: 'LTI.NS', companyName: 'LTIMindtree Ltd.' }, // old symbol
  { symbol: 'LT.NS', companyName: 'Larsen & Toubro Ltd.' },
  { symbol: 'LSIL.NS', companyName: 'Lloyds Steels Industries Ltd.' },
  {
    symbol: 'LPDC.NS',
    companyName: 'Landmark Property Development Company Ltd.',
  },
  { symbol: 'LOVABLE.NS', companyName: 'Lovable Lingerie Ltd.' },
  {
    symbol: 'LOTUSEYE.NS',
    companyName: 'Lotus Eye Hospital and Institute Ltd.',
  },
  { symbol: 'LODHA.NS', companyName: 'Macrotech Developers Ltd.' },
  { symbol: 'LLOYDSME.NS', companyName: 'Lloyds Metals and Energy Ltd.' },
  { symbol: 'LINCOLN.NS', companyName: 'Lincoln Pharmaceuticals Ltd.' },
  { symbol: 'LIKHITHA.NS', companyName: 'Likhitha Infrastructure Ltd.' },
  { symbol: 'LGBBROSLTD.NS', companyName: 'LG Balakrishnan & Bros Ltd.' },
  {
    symbol: 'LFIC.NS',
    companyName: 'Lakshmi Finance & Industrial Corporation Ltd.',
  },
  { symbol: 'LEMONTREE.NS', companyName: 'Lemon Tree Hotels Ltd.' },
  { symbol: 'LALPATHLAB.NS', companyName: 'Dr. Lal PathLabs Ltd.' },
  { symbol: 'LAKSHVILAS.NS', companyName: 'Lakshmi Vilas Bank Ltd.' }, // delisted
  { symbol: 'KUANTUM.NS', companyName: 'Kuantum Papers Ltd.' },
  { symbol: 'KSCL.NS', companyName: 'Kaveri Seed Company Ltd.' },
  { symbol: 'KSB.NS', companyName: 'KSB Ltd.' },
  { symbol: 'KRBL.NS', companyName: 'KRBL Ltd.' },
  { symbol: 'KPITTECH.NS', companyName: 'KPIT Technologies Ltd.' },
  { symbol: 'KPRMILL.NS', companyName: 'K.P.R. Mill Ltd.' },
  { symbol: 'KOTAKBANK.NS', companyName: 'Kotak Mahindra Bank Ltd.' },
  { symbol: 'KOPRAN.NS', companyName: 'Kopran Ltd.' },
  { symbol: 'KOLTEPATIL.NS', companyName: 'Kolte-Patil Developers Ltd.' },
  { symbol: 'KOKUYOCML.NS', companyName: 'Kokuyo Camlin Ltd.' },
  { symbol: 'KNRCON.NS', companyName: 'KNR Constructions Ltd.' },
  { symbol: 'KMSUGAR.NS', companyName: 'K.M. Sugar Mills Ltd.' },
  { symbol: 'KIRLOSIND.NS', companyName: 'Kirloskar Industries Ltd.' },
  { symbol: 'KIRLOSFER.NS', companyName: 'Kirloskar Ferrous Industries Ltd.' },
  { symbol: 'KIRLOSENG.NS', companyName: 'Kirloskar Oil Engines Ltd.' },
  { symbol: 'KIRLOSBROS.NS', companyName: 'Kirloskar Brothers Ltd.' },
  { symbol: 'KIRIINDUS.NS', companyName: 'Kiri Industries Ltd.' },
  {
    symbol: 'KINGFA.NS',
    companyName: 'Kingfa Science & Technology (India) Ltd.',
  },
  { symbol: 'KICL.NS', companyName: 'Kalyani Investment Company Ltd.' },
  { symbol: 'KHADIM.NS', companyName: 'Khadim India Ltd.' },
  { symbol: 'KEYCORP.NS', companyName: 'Key Corp' }, // remove
  { symbol: 'KESORAMIND.NS', companyName: 'Kesoram Industries Ltd.' },
  { symbol: 'KERNEX.NS', companyName: 'Kernex Microsystems (India) Ltd.' },
  { symbol: 'KEPCO.NS', companyName: 'KEPCO' }, // remove
  { symbol: 'KENNAMET.NS', companyName: 'Kennametal India Ltd.' },
  { symbol: 'KEC.NS', companyName: 'KEC International Ltd.' },
  { symbol: 'KCP.NS', companyName: 'KCP Ltd.' },
];
