export const NIFTY_100 = [
    { symbol: 'RELIANCE.NS', companyName: 'Reliance Industries Ltd.' },
    { symbol: 'TCS.NS', companyName: 'Tata Consultancy Services Ltd.' },
    { symbol: 'HDFCBANK.NS', companyName: 'HDFC Bank Ltd.' },
    { symbol: 'ICICIBANK.NS', companyName: 'ICICI Bank Ltd.' },
    { symbol: 'INFY.NS', companyName: 'Infosys Ltd.' },
    { symbol: 'BHARTIARTL.NS', companyName: 'Bharti Airtel Ltd.' },
    { symbol: 'ITC.NS', companyName: 'ITC Ltd.' },
    { symbol: 'SBIN.NS', companyName: 'State Bank of India' },
    { symbol: 'LICI.NS', companyName: 'Life Insurance Corporation of India' },
    { symbol: 'LT.NS', companyName: 'Larsen & Toubro Ltd.' },
    { symbol: 'HINDUNILVR.NS', companyName: 'Hindustan Unilever Ltd.' },
    { symbol: 'BAJFINANCE.NS', companyName: 'Bajaj Finance Ltd.' },
    { symbol: 'HCLTECH.NS', companyName: 'HCL Technologies Ltd.' },
    { symbol: 'KOTAKBANK.NS', companyName: 'Kotak Mahindra Bank Ltd.' },
    { symbol: 'M&M.NS', companyName: 'Mahindra & Mahindra Ltd.' },
    { symbol: 'ADANIENT.NS', companyName: 'Adani Enterprises Ltd.' },
    { symbol: 'SUNPHARMA.NS', companyName: 'Sun Pharmaceutical Industries Ltd.' },
    { symbol: 'MARUTI.NS', companyName: 'Maruti Suzuki India Ltd.' },
    { symbol: 'TITAN.NS', companyName: 'Titan Company Ltd.' },
    { symbol: 'AXISBANK.NS', companyName: 'Axis Bank Ltd.' },
    { symbol: 'ULTRACEMCO.NS', companyName: 'UltraTech Cement Ltd.' },
    { symbol: 'TATAMOTORS.NS', companyName: 'Tata Motors Ltd.' },
    { symbol: 'ASIANPAINT.NS', companyName: 'Asian Paints Ltd.' },
    { symbol: 'NTPC.NS', companyName: 'NTPC Ltd.' },
    { symbol: 'ADANIPORTS.NS', companyName: 'Adani Ports and Special Economic Zone Ltd.' },
    { symbol: 'POWERGRID.NS', companyName: 'Power Grid Corporation of India Ltd.' },
    { symbol: 'ONGC.NS', companyName: 'Oil & Natural Gas Corporation Ltd.' },
    { symbol: 'WIPRO.NS', companyName: 'Wipro Ltd.' },
    { symbol: 'COALINDIA.NS', companyName: 'Coal India Ltd.' },
    { symbol: 'NESTLEIND.NS', companyName: 'Nestle India Ltd.' },
    { symbol: 'BAJAJFINSV.NS', companyName: 'Bajaj Finserv Ltd.' },
    { symbol: 'JSWSTEEL.NS', companyName: 'JSW Steel Ltd.' },
    { symbol: 'ADANIGREEN.NS', companyName: 'Adani Green Energy Ltd.' },
    { symbol: 'TATASTEEL.NS', companyName: 'Tata Steel Ltd.' },
    { symbol: 'GRASIM.NS', companyName: 'Grasim Industries Ltd.' },
    { symbol: 'TECHM.NS', companyName: 'Tech Mahindra Ltd.' },
    { symbol: 'HDFCLIFE.NS', companyName: 'HDFC Life Insurance Company Ltd.' },
    { symbol: 'INDUSINDBK.NS', companyName: 'IndusInd Bank Ltd.' },
    { symbol: 'LTIM.NS', companyName: 'LTIMindtree Ltd.' },
    { symbol: 'HINDALCO.NS', companyName: 'Hindalco Industries Ltd.' },
    { symbol: 'DIVISLAB.NS', companyName: 'Divi\'s Laboratories Ltd.' },
    { symbol: 'ADANIPOWER.NS', companyName: 'Adani Power Ltd.' },
    { symbol: 'CIPLA.NS', companyName: 'Cipla Ltd.' },
    { symbol: 'EICHERMOT.NS', companyName: 'Eicher Motors Ltd.' },
    { symbol: 'BPCL.NS', companyName: 'Bharat Petroleum Corporation Ltd.' },
    { symbol: 'SBIW.NS', companyName: 'SBI Cards and Payment Services Ltd.' },
    { symbol: 'BRITANNIA.NS', companyName: 'Britannia Industries Ltd.' },
    { symbol: 'APOLLOHOSP.NS', companyName: 'Apollo Hospitals Enterprise Ltd.' },
    { symbol: 'HAL.NS', companyName: 'Hindustan Aeronautics Ltd.' },
    { symbol: 'TATACONSUM.NS', companyName: 'Tata Consumer Products Ltd.' },
    { symbol: 'MNM.NS', companyName: 'Mahindra & Mahindra Ltd.' }, // Duplicate check usually needed but symbols differ
    { symbol: 'DMART.NS', companyName: 'Avenue Supermarts Ltd.' },
    { symbol: 'VBL.NS', companyName: 'Varun Beverages Ltd.' },
    { symbol: 'DLF.NS', companyName: 'DLF Ltd.' },
    { symbol: 'SIEMENS.NS', companyName: 'Siemens Ltd.' },
    { symbol: 'IOC.NS', companyName: 'Indian Oil Corporation Ltd.' },
    { symbol: 'BEL.NS', companyName: 'Bharat Electronics Ltd.' },
    { symbol: 'AMBUJACEM.NS', companyName: 'Ambuja Cements Ltd.' },
    { symbol: 'GAIL.NS', companyName: 'GAIL (India) Ltd.' },
    { symbol: 'BANKBARODA.NS', companyName: 'Bank of Baroda' },
    { symbol: 'INDIGO.NS', companyName: 'InterGlobe Aviation Ltd.' },
    { symbol: 'PNB.NS', companyName: 'Punjab National Bank' },
    { symbol: 'ZOMATO.NS', companyName: 'Zomato Ltd.' },
    { symbol: 'TRENT.NS', companyName: 'Trent Ltd.' },
    { symbol: 'SBILIFE.NS', companyName: 'SBI Life Insurance Company Ltd.' },
    { symbol: 'PIDILITIND.NS', companyName: 'Pidilite Industries Ltd.' },
    { symbol: 'BAJAJ-AUTO.NS', companyName: 'Bajaj Auto Ltd.' },
    { symbol: 'LODHA.NS', companyName: 'Macrotech Developers Ltd.' },
    { symbol: 'GODREJCP.NS', companyName: 'Godrej Consumer Products Ltd.' },
    { symbol: 'DRREDDY.NS', companyName: 'Dr. Reddy\'s Laboratories Ltd.' },
    { symbol: 'SHREECEM.NS', companyName: 'Shree Cement Ltd.' },
    { symbol: 'HAVELLS.NS', companyName: 'Havells India Ltd.' },
    { symbol: 'CHOLAFIN.NS', companyName: 'Cholamandalam Investment and Finance Company Ltd.' },
    { symbol: 'ABB.NS', companyName: 'ABB India Ltd.' },
    { symbol: 'DABUR.NS', companyName: 'Dabur India Ltd.' },
    { symbol: 'VEDL.NS', companyName: 'Vedanta Ltd.' },
    { symbol: 'SRF.NS', companyName: 'SRF Ltd.' },
    { symbol: 'JIOFIN.NS', companyName: 'Jio Financial Services Ltd.' },
    { symbol: 'CANBK.NS', companyName: 'Canara Bank' },
    { symbol: 'UNIONBANK.NS', companyName: 'Union Bank of India' },
    { symbol: 'RECLTD.NS', companyName: 'REC Ltd.' },
    { symbol: 'PFC.NS', companyName: 'Power Finance Corporation Ltd.' },
    { symbol: 'IRFC.NS', companyName: 'Indian Railway Finance Corporation Ltd.' },
    { symbol: 'TVSMOTOR.NS', companyName: 'TVS Motor Company Ltd.' },
    { symbol: 'BOSCHLTD.NS', companyName: 'Bosch Ltd.' },
    { symbol: 'HEROMOTOCO.NS', companyName: 'Hero MotoCorp Ltd.' },
    { symbol: 'JINDALSTEL.NS', companyName: 'Jindal Steel & Power Ltd.' },
    { symbol: 'TATACHEM.NS', companyName: 'Tata Chemicals Ltd.' },
    { symbol: 'ICICIPRULI.NS', companyName: 'ICICI Prudential Life Insurance Company Ltd.' },
    { symbol: 'MCDOWELL-N.NS', companyName: 'United Spirits Ltd.' },
    { symbol: 'MOTHERSON.NS', companyName: 'Samvardhana Motherson International Ltd.' },
    { symbol: 'IDFCFIRSTB.NS', companyName: 'IDFC First Bank Ltd.' },
    { symbol: 'AUROPHARMA.NS', companyName: 'Aurobindo Pharma Ltd.' },
    { symbol: 'BHARATFORG.NS', companyName: 'Bharat Forge Ltd.' },
    { symbol: 'PERSISTENT.NS', companyName: 'Persistent Systems Ltd.' },
    { symbol: 'POLYCAB.NS', companyName: 'Polycab India Ltd.' },
    { symbol: 'MRF.NS', companyName: 'MRF Ltd.' },
    { symbol: 'LTTS.NS', companyName: 'L&T Technology Services Ltd.' },
    { symbol: 'CUMMINSIND.NS', companyName: 'Cummins India Ltd.' },
    { symbol: 'COLPAL.NS', companyName: 'Colgate-Palmolive (India) Ltd.' },
    // Popular Midcaps & Retail Favorites
    { symbol: 'PAYTM.NS', companyName: 'One97 Communications Ltd.' },
    { symbol: 'ZOMATO.NS', companyName: 'Zomato Ltd.' },
    { symbol: 'INDUSTOWER.NS', companyName: 'Indus Towers Limited' },
    { symbol: 'INDUSINDBK.NS', companyName: 'IndusInd Bank Limited' },
    { symbol: 'FSN.NS', companyName: 'FSN E-Commerce Ventures Ltd. (Nykaa)' },
    { symbol: 'POLICYBZR.NS', companyName: 'PB Fintech Ltd.' },
    { symbol: 'DELHIVERY.NS', companyName: 'Delhivery Ltd.' },
    { symbol: 'SUZLON.NS', companyName: 'Suzlon Energy Ltd.' },
    { symbol: 'IDEA.NS', companyName: 'Vodafone Idea Ltd.' },
    { symbol: 'YESBANK.NS', companyName: 'Yes Bank Ltd.' },
    { symbol: 'IDFCFIRSTB.NS', companyName: 'IDFC First Bank Ltd.' },
    { symbol: 'JUBLFOOD.NS', companyName: 'Jubilant FoodWorks Ltd.' },
    { symbol: 'IRCTC.NS', companyName: 'Indian Railway Catering and Tourism Corporation Ltd.' },
    { symbol: 'RVNL.NS', companyName: 'Rail Vikas Nigam Ltd.' },
    { symbol: 'NHPC.NS', companyName: 'NHPC Ltd.' },
    { symbol: 'SJVN.NS', companyName: 'SJVN Ltd.' },
    { symbol: 'BSE.NS', companyName: 'BSE Ltd.' },
    { symbol: 'CDSL.NS', companyName: 'Central Depository Services (India) Ltd.' },
    { symbol: 'ANGELONE.NS', companyName: 'Angel One Ltd.' },
    { symbol: 'MCX.NS', companyName: 'Multi Commodity Exchange of India Ltd.' },
    { symbol: 'KPITTECH.NS', companyName: 'KPIT Technologies Ltd.' },
    { symbol: 'TATAELXSI.NS', companyName: 'Tata Elxsi Ltd.' },
    { symbol: 'L&TFH.NS', companyName: 'L&T Finance Holdings Ltd.' },
    { symbol: 'ABCAPITAL.NS', companyName: 'Aditya Birla Capital Ltd.' },
    { symbol: 'M&MFIN.NS', companyName: 'Mahindra & Mahindra Financial Services Ltd.' },
    { symbol: 'ASHOKLEY.NS', companyName: 'Ashok Leyland Ltd.' },
    { symbol: 'TATACOMM.NS', companyName: 'Tata Communications Ltd.' },
    { symbol: 'OFSS.NS', companyName: 'Oracle Financial Services Software Ltd.' },
    { symbol: 'HAPPSTMNDS.NS', companyName: 'Happiest Minds Technologies Ltd.' },
    { symbol: 'DEVYANI.NS', companyName: 'Devyani International Ltd.' },
    { symbol: 'BIOCON.NS', companyName: 'Biocon Ltd.' },
    { symbol: 'LUPIN.NS', companyName: 'Lupin Ltd.' },
    { symbol: 'AUROPHARMA.NS', companyName: 'Aurobindo Pharma Ltd.' },
    { symbol: 'GLAND.NS', companyName: 'Gland Pharma Ltd.' },
    { symbol: 'LAURUSLABS.NS', companyName: 'Laurus Labs Ltd.' },
];
