// Comprehensive list of Top Indian Stocks (Nifty 500 & Popular)
export const NIFTY_500 = [
    // --- NIFTY 50 ---
    { symbol: 'RELIANCE.NS', companyName: 'Reliance Industries Ltd.' },
    { symbol: 'TCS.NS', companyName: 'Tata Consultancy Services Ltd.' },
    { symbol: 'HDFCBANK.NS', companyName: 'HDFC Bank Ltd.' },
    { symbol: 'ICICIBANK.NS', companyName: 'ICICI Bank Ltd.' },
    { symbol: 'INFY.NS', companyName: 'Infosys Ltd.' },
    { symbol: 'BHARTIARTL.NS', companyName: 'Bharti Airtel Ltd.' },
    { symbol: 'ITC.NS', companyName: 'ITC Ltd.' },
    { symbol: 'SBIN.NS', companyName: 'State Bank of India' },
    { symbol: 'LICI.NS', companyName: 'Life Insurance Corporation of India' },
    { symbol: 'LT.NS', companyName: 'Larsen & Toubro Ltd.' },
    { symbol: 'HINDUNILVR.NS', companyName: 'Hindustan Unilever Ltd.' },
    { symbol: 'BAJFINANCE.NS', companyName: 'Bajaj Finance Ltd.' },
    { symbol: 'HCLTECH.NS', companyName: 'HCL Technologies Ltd.' },
    { symbol: 'KOTAKBANK.NS', companyName: 'Kotak Mahindra Bank Ltd.' },
    { symbol: 'M&M.NS', companyName: 'Mahindra & Mahindra Ltd.' },
    { symbol: 'ADANIENT.NS', companyName: 'Adani Enterprises Ltd.' },
    { symbol: 'SUNPHARMA.NS', companyName: 'Sun Pharmaceutical Industries Ltd.' },
    { symbol: 'MARUTI.NS', companyName: 'Maruti Suzuki India Ltd.' },
    { symbol: 'TITAN.NS', companyName: 'Titan Company Ltd.' },
    { symbol: 'AXISBANK.NS', companyName: 'Axis Bank Ltd.' },
    { symbol: 'ULTRACEMCO.NS', companyName: 'UltraTech Cement Ltd.' },
    { symbol: 'TATAMOTORS.NS', companyName: 'Tata Motors Ltd.' },
    { symbol: 'ASIANPAINT.NS', companyName: 'Asian Paints Ltd.' },
    { symbol: 'NTPC.NS', companyName: 'NTPC Ltd.' },
    { symbol: 'ADANIPORTS.NS', companyName: 'Adani Ports and Special Economic Zone Ltd.' },
    { symbol: 'POWERGRID.NS', companyName: 'Power Grid Corporation of India Ltd.' },
    { symbol: 'ONGC.NS', companyName: 'Oil & Natural Gas Corporation Ltd.' },
    { symbol: 'WIPRO.NS', companyName: 'Wipro Ltd.' },
    { symbol: 'COALINDIA.NS', companyName: 'Coal India Ltd.' },
    { symbol: 'NESTLEIND.NS', companyName: 'Nestle India Ltd.' },
    { symbol: 'BAJAJFINSV.NS', companyName: 'Bajaj Finserv Ltd.' },
    { symbol: 'JSWSTEEL.NS', companyName: 'JSW Steel Ltd.' },
    { symbol: 'ADANIGREEN.NS', companyName: 'Adani Green Energy Ltd.' },
    { symbol: 'TATASTEEL.NS', companyName: 'Tata Steel Ltd.' },
    { symbol: 'GRASIM.NS', companyName: 'Grasim Industries Ltd.' },
    { symbol: 'TECHM.NS', companyName: 'Tech Mahindra Ltd.' },
    { symbol: 'HDFCLIFE.NS', companyName: 'HDFC Life Insurance Company Ltd.' },
    { symbol: 'INDUSINDBK.NS', companyName: 'IndusInd Bank Ltd.' },
    { symbol: 'LTIM.NS', companyName: 'LTIMindtree Ltd.' },
    { symbol: 'HINDALCO.NS', companyName: 'Hindalco Industries Ltd.' },
    { symbol: 'DIVISLAB.NS', companyName: 'Divi\'s Laboratories Ltd.' },
    { symbol: 'ADANIPOWER.NS', companyName: 'Adani Power Ltd.' },
    { symbol: 'CIPLA.NS', companyName: 'Cipla Ltd.' },
    { symbol: 'EICHERMOT.NS', companyName: 'Eicher Motors Ltd.' },
    { symbol: 'BPCL.NS', companyName: 'Bharat Petroleum Corporation Ltd.' },
    { symbol: 'SBIW.NS', companyName: 'SBI Cards and Payment Services Ltd.' },
    { symbol: 'BRITANNIA.NS', companyName: 'Britannia Industries Ltd.' },
    { symbol: 'APOLLOHOSP.NS', companyName: 'Apollo Hospitals Enterprise Ltd.' },
    { symbol: 'HAL.NS', companyName: 'Hindustan Aeronautics Ltd.' },
    { symbol: 'TATACONSUM.NS', companyName: 'Tata Consumer Products Ltd.' },

    // --- NIFTY NEXT 50 & MIDCAP 150 (High Quality) ---
    { symbol: 'DMART.NS', companyName: 'Avenue Supermarts Ltd.' },
    { symbol: 'VBL.NS', companyName: 'Varun Beverages Ltd.' },
    { symbol: 'DLF.NS', companyName: 'DLF Ltd.' },
    { symbol: 'SIEMENS.NS', companyName: 'Siemens Ltd.' },
    { symbol: 'IOC.NS', companyName: 'Indian Oil Corporation Ltd.' },
    { symbol: 'BEL.NS', companyName: 'Bharat Electronics Ltd.' },
    { symbol: 'AMBUJACEM.NS', companyName: 'Ambuja Cements Ltd.' },
    { symbol: 'GAIL.NS', companyName: 'GAIL (India) Ltd.' },
    { symbol: 'BANKBARODA.NS', companyName: 'Bank of Baroda' },
    { symbol: 'INDIGO.NS', companyName: 'InterGlobe Aviation Ltd.' },
    { symbol: 'PNB.NS', companyName: 'Punjab National Bank' },
    { symbol: 'ZOMATO.NS', companyName: 'Zomato Ltd.' },
    { symbol: 'TRENT.NS', companyName: 'Trent Ltd.' },
    { symbol: 'SBILIFE.NS', companyName: 'SBI Life Insurance Company Ltd.' },
    { symbol: 'PIDILITIND.NS', companyName: 'Pidilite Industries Ltd.' },
    { symbol: 'BAJAJ-AUTO.NS', companyName: 'Bajaj Auto Ltd.' },
    { symbol: 'LODHA.NS', companyName: 'Macrotech Developers Ltd.' },
    { symbol: 'GODREJCP.NS', companyName: 'Godrej Consumer Products Ltd.' },
    { symbol: 'DRREDDY.NS', companyName: 'Dr. Reddy\'s Laboratories Ltd.' },
    { symbol: 'SHREECEM.NS', companyName: 'Shree Cement Ltd.' },
    { symbol: 'HAVELLS.NS', companyName: 'Havells India Ltd.' },
    { symbol: 'CHOLAFIN.NS', companyName: 'Cholamandalam Investment and Finance Company Ltd.' },
    { symbol: 'ABB.NS', companyName: 'ABB India Ltd.' },
    { symbol: 'DABUR.NS', companyName: 'Dabur India Ltd.' },
    { symbol: 'VEDL.NS', companyName: 'Vedanta Ltd.' },
    { symbol: 'SRF.NS', companyName: 'SRF Ltd.' },
    { symbol: 'JIOFIN.NS', companyName: 'Jio Financial Services Ltd.' },
    { symbol: 'CANBK.NS', companyName: 'Canara Bank' },
    { symbol: 'UNIONBANK.NS', companyName: 'Union Bank of India' },
    { symbol: 'RECLTD.NS', companyName: 'REC Ltd.' },
    { symbol: 'PFC.NS', companyName: 'Power Finance Corporation Ltd.' },
    { symbol: 'IRFC.NS', companyName: 'Indian Railway Finance Corporation Ltd.' },
    { symbol: 'TVSMOTOR.NS', companyName: 'TVS Motor Company Ltd.' },
    { symbol: 'BOSCHLTD.NS', companyName: 'Bosch Ltd.' },
    { symbol: 'HEROMOTOCO.NS', companyName: 'Hero MotoCorp Ltd.' },
    { symbol: 'JINDALSTEL.NS', companyName: 'Jindal Steel & Power Ltd.' },
    { symbol: 'TATACHEM.NS', companyName: 'Tata Chemicals Ltd.' },
    { symbol: 'ICICIPRULI.NS', companyName: 'ICICI Prudential Life Insurance Company Ltd.' },
    { symbol: 'MCDOWELL-N.NS', companyName: 'United Spirits Ltd.' },
    { symbol: 'MOTHERSON.NS', companyName: 'Samvardhana Motherson International Ltd.' },
    { symbol: 'IDFCFIRSTB.NS', companyName: 'IDFC First Bank Ltd.' },
    { symbol: 'AUROPHARMA.NS', companyName: 'Aurobindo Pharma Ltd.' },
    { symbol: 'BHARATFORG.NS', companyName: 'Bharat Forge Ltd.' },
    { symbol: 'PERSISTENT.NS', companyName: 'Persistent Systems Ltd.' },
    { symbol: 'POLYCAB.NS', companyName: 'Polycab India Ltd.' },
    { symbol: 'MRF.NS', companyName: 'MRF Ltd.' },
    { symbol: 'LTTS.NS', companyName: 'L&T Technology Services Ltd.' },
    { symbol: 'CUMMINSIND.NS', companyName: 'Cummins India Ltd.' },
    { symbol: 'COLPAL.NS', companyName: 'Colgate-Palmolive (India) Ltd.' },

    // --- BANKING & FINANCE ---
    { symbol: 'FEDERALBNK.NS', companyName: 'Federal Bank Ltd.' },
    { symbol: 'IDBI.NS', companyName: 'IDBI Bank Ltd.' },
    { symbol: 'BANDHANBNK.NS', companyName: 'Bandhan Bank Ltd.' },
    { symbol: 'AUBANK.NS', companyName: 'AU Small Finance Bank Ltd.' },
    { symbol: 'BANKINDIA.NS', companyName: 'Bank of India' },
    { symbol: 'INDIANB.NS', companyName: 'Indian Bank' },
    { symbol: 'MAHABANK.NS', companyName: 'Bank of Maharashtra' },
    { symbol: 'UCOBANK.NS', companyName: 'UCO Bank' },
    { symbol: 'CENTRALBK.NS', companyName: 'Central Bank of India' },
    { symbol: 'IOB.NS', companyName: 'Indian Overseas Bank' },
    { symbol: 'PSB.NS', companyName: 'Punjab & Sind Bank' },
    { symbol: 'KUB.NS', companyName: 'City Union Bank Ltd.' },
    { symbol: 'KARURVYSYA.NS', companyName: 'Karur Vysya Bank Ltd.' },
    { symbol: 'RBLBANK.NS', companyName: 'RBL Bank Ltd.' },
    { symbol: 'JAMNAAUTO.NS', companyName: 'Jamna Auto Industries Ltd.' },
    { symbol: 'SUNDARMFIN.NS', companyName: 'Sundaram Finance Ltd.' },
    { symbol: 'M&MFIN.NS', companyName: 'Mahindra & Mahindra Financial Services Ltd.' },
    { symbol: 'MUTHOOTFIN.NS', companyName: 'Muthoot Finance Ltd.' },
    { symbol: 'MANAPPURAM.NS', companyName: 'Manappuram Finance Ltd.' },
    { symbol: 'POONAWALLA.NS', companyName: 'Poonawalla Fincorp Ltd.' },
    { symbol: 'ABFRL.NS', companyName: 'Aditya Birla Fashion and Retail Ltd.' },
    { symbol: 'ABCAPITAL.NS', companyName: 'Aditya Birla Capital Ltd.' },
    { symbol: 'L&TFH.NS', companyName: 'L&T Finance Holdings Ltd.' },

    // --- IT & TECHNOLOGY ---
    { symbol: 'OFSS.NS', companyName: 'Oracle Financial Services Software Ltd.' },
    { symbol: 'KPITTECH.NS', companyName: 'KPIT Technologies Ltd.' },
    { symbol: 'TATAELXSI.NS', companyName: 'Tata Elxsi Ltd.' },
    { symbol: 'COFORGE.NS', companyName: 'Coforge Ltd.' },
    { symbol: 'MPHASIS.NS', companyName: 'Mphasis Ltd.' },
    { symbol: 'LTI.NS', companyName: 'Larsen & Toubro Infotech Ltd.' }, // Legacy check needed
    { symbol: 'MINDTREE.NS', companyName: 'Mindtree Ltd.' }, // Legacy check needed
    { symbol: 'CYIENT.NS', companyName: 'Cyient Ltd.' },
    { symbol: 'ZENSARTECH.NS', companyName: 'Zensar Technologies Ltd.' },
    { symbol: 'SONATSOFTW.NS', companyName: 'Sonata Software Ltd.' },
    { symbol: 'INTELLECT.NS', companyName: 'Intellect Design Arena Ltd.' },
    { symbol: 'MASTEK.NS', companyName: 'Mastek Ltd.' },
    { symbol: 'TANLA.NS', companyName: 'Tanla Platforms Ltd.' },
    { symbol: 'ROUTE.NS', companyName: 'Route Mobile Ltd.' },
    { symbol: 'BCOM.NS', companyName: 'Brightcom Group Ltd.' },
    { symbol: 'FSL.NS', companyName: 'Firstsource Solutions Ltd.' },
    { symbol: 'HAPPSTMNDS.NS', companyName: 'Happiest Minds Technologies Ltd.' },
    { symbol: 'LATENTVIEW.NS', companyName: 'Latent View Analytics Ltd.' },
    { symbol: 'MAPMYINDIA.NS', companyName: 'C.E. Info Systems Ltd.' },
    { symbol: 'NAZARA.NS', companyName: 'Nazara Technologies Ltd.' },
    { symbol: 'PBFINTECH.NS', companyName: 'PB Fintech Ltd.' },
    { symbol: 'PAYTM.NS', companyName: 'One97 Communications Ltd.' },
    { symbol: 'FSN.NS', companyName: 'FSN E-Commerce Ventures Ltd.' },
    { symbol: 'DELHIVERY.NS', companyName: 'Delhivery Ltd.' },
    { symbol: 'AFFLE.NS', companyName: 'Affle (India) Ltd.' },
    { symbol: 'INDIAMART.NS', companyName: 'IndiaMART InterMESH Ltd.' },
    { symbol: 'JUSTDIAL.NS', companyName: 'Just Dial Ltd.' },

    // --- PHARMA & HEALTHCARE ---
    { symbol: 'LUPIN.NS', companyName: 'Lupin Ltd.' },
    { symbol: 'BIOCON.NS', companyName: 'Biocon Ltd.' },
    { symbol: 'ALKEM.NS', companyName: 'Alkem Laboratories Ltd.' },
    { symbol: 'TORNTPHARM.NS', companyName: 'Torrent Pharmaceuticals Ltd.' },
    { symbol: 'ZYDUSLIFE.NS', companyName: 'Zydus Lifesciences Ltd.' },
    { symbol: 'GLENMARK.NS', companyName: 'Glenmark Pharmaceuticals Ltd.' },
    { symbol: 'IPCALAB.NS', companyName: 'IPCA Laboratories Ltd.' },
    { symbol: 'SYNGENE.NS', companyName: 'Syngene International Ltd.' },
    { symbol: 'LAURUSLABS.NS', companyName: 'Laurus Labs Ltd.' },
    { symbol: 'GLAND.NS', companyName: 'Gland Pharma Ltd.' },
    { symbol: 'JBCHEPHARM.NS', companyName: 'J.B. Chemicals & Pharmaceuticals Ltd.' },
    { symbol: 'NATCOPHARM.NS', companyName: 'Natco Pharma Ltd.' },
    { symbol: 'PFIZER.NS', companyName: 'Pfizer Ltd.' },
    { symbol: 'SANOFI.NS', companyName: 'Sanofi India Ltd.' },
    { symbol: 'GSK.NS', companyName: 'GlaxoSmithKline Pharmaceuticals Ltd.' },
    { symbol: 'ABBOTINDIA.NS', companyName: 'Abbott India Ltd.' },
    { symbol: 'ASTRAZEN.NS', companyName: 'AstraZeneca Pharma India Ltd.' },
    { symbol: 'LALPATHLAB.NS', companyName: 'Dr. Lal PathLabs Ltd.' },
    { symbol: 'METROPOLIS.NS', companyName: 'Metropolis Healthcare Ltd.' },
    { symbol: 'NH.NS', companyName: 'Narayana Hrudayalaya Ltd.' },
    { symbol: 'ASTERDM.NS', companyName: 'Aster DM Healthcare Ltd.' },
    { symbol: 'KIMS.NS', companyName: 'Krishna Institute of Medical Sciences Ltd.' },
    { symbol: 'HCG.NS', companyName: 'HealthCare Global Enterprises Ltd.' },
    { symbol: 'FORTIS.NS', companyName: 'Fortis Healthcare Ltd.' },
    { symbol: 'MAXHEALTH.NS', companyName: 'Max Healthcare Institute Ltd.' },
    { symbol: 'RAINBOW.NS', companyName: 'Rainbow Childrens Medicare Ltd.' },
    { symbol: 'BIKAJI.NS', companyName: 'Bikaji Foods International Ltd.' },

    // --- AUTOMOBILE & ANCILLARY ---
    { symbol: 'ASHOKLEY.NS', companyName: 'Ashok Leyland Ltd.' },
    { symbol: 'ESCORTS.NS', companyName: 'Escorts Kubota Ltd.' },
    { symbol: 'MOTHERSON.NS', companyName: 'Samvardhana Motherson International Ltd.' },
    { symbol: 'BALKRISIND.NS', companyName: 'Balkrishna Industries Ltd.' },
    { symbol: 'APOLLOTYRE.NS', companyName: 'Apollo Tyres Ltd.' },
    { symbol: 'JKTYRE.NS', companyName: 'JK Tyre & Industries Ltd.' },
    { symbol: 'CEATLTD.NS', companyName: 'CEAT Ltd.' },
    { symbol: 'EXIDEIND.NS', companyName: 'Exide Industries Ltd.' },
    { symbol: 'AMARAJABAT.NS', companyName: 'Amara Raja Energy & Mobility Ltd.' },
    { symbol: 'SUNCITY.NS', companyName: 'Suncity Ltd' }, // Check symbol
    { symbol: 'ENDURANCE.NS', companyName: 'Endurance Technologies Ltd.' },
    { symbol: 'MINDAIND.NS', companyName: 'Uno Minda Ltd.' },
    { symbol: 'SUPRAJIT.NS', companyName: 'Suprajit Engineering Ltd.' },
    { symbol: 'GABRIEL.NS', companyName: 'Gabriel India Ltd.' },
    { symbol: 'CRAFTSMAN.NS', companyName: 'Craftsman Automation Ltd.' },
    { symbol: 'VARROC.NS', companyName: 'Varroc Engineering Ltd.' },

    // --- ENERGY, POWER & UTILITIES ---
    { symbol: 'NHPC.NS', companyName: 'NHPC Ltd.' },
    { symbol: 'SJVN.NS', companyName: 'SJVN Ltd.' },
    { symbol: 'TORNTPOWER.NS', companyName: 'Torrent Power Ltd.' },
    { symbol: 'JSWENERGY.NS', companyName: 'JSW Energy Ltd.' },
    { symbol: 'TATAPOWER.NS', companyName: 'Tata Power Company Ltd.' },
    { symbol: 'CESC.NS', companyName: 'CESC Ltd.' },
    { symbol: 'IEX.NS', companyName: 'Indian Energy Exchange Ltd.' },
    { symbol: 'MCX.NS', companyName: 'Multi Commodity Exchange of India Ltd.' },
    { symbol: 'BSE.NS', companyName: 'BSE Ltd.' },
    { symbol: 'CDSL.NS', companyName: 'Central Depository Services (India) Ltd.' },
    { symbol: 'CAMS.NS', companyName: 'Computer Age Management Services Ltd.' },
    { symbol: 'KFINTECH.NS', companyName: 'KFin Technologies Ltd.' },
    { symbol: 'PETRONET.NS', companyName: 'Petronet LNG Ltd.' },
    { symbol: 'IGL.NS', companyName: 'Indraprastha Gas Ltd.' },
    { symbol: 'MGL.NS', companyName: 'Mahanagar Gas Ltd.' },
    { symbol: 'GUJGASLTD.NS', companyName: 'Gujarat Gas Ltd.' },
    { symbol: 'GSPL.NS', companyName: 'Gujarat State Petronet Ltd.' },
    { symbol: 'MRPL.NS', companyName: 'Mangalore Refinery & Petrochemicals Ltd.' },
    { symbol: 'CHENNPETRO.NS', companyName: 'Chennai Petroleum Corporation Ltd.' },
    { symbol: 'HINDOILEXP.NS', companyName: 'Hindustan Oil Exploration Company Ltd.' },
    { symbol: 'DEEPINDS.NS', companyName: 'Deep Industries Ltd.' },

    // --- CAPITAL GOODS & INFRASTRUCTURE ---
    { symbol: 'L&T.NS', companyName: 'Larsen & Toubro Ltd.' }, // Duplicate check: LT.NS above
    { symbol: 'HAL.NS', companyName: 'Hindustan Aeronautics Ltd.' },
    { symbol: 'BEL.NS', companyName: 'Bharat Electronics Ltd.' },
    { symbol: 'BDL.NS', companyName: 'Bharat Dynamics Ltd.' },
    { symbol: 'MAZDOCK.NS', companyName: 'Mazagon Dock Shipbuilders Ltd.' },
    { symbol: 'COCHINSHIP.NS', companyName: 'Cochin Shipyard Ltd.' },
    { symbol: 'GRSE.NS', companyName: 'Garden Reach Shipbuilders & Engineers Ltd.' },
    { symbol: 'PARAS.NS', companyName: 'Paras Defence and Space Technologies Ltd.' },
    { symbol: 'MTARTECH.NS', companyName: 'MTAR Technologies Ltd.' },
    { symbol: 'DATAPATTNS.NS', companyName: 'Data Patterns (India) Ltd.' },
    { symbol: 'BHEL.NS', companyName: 'Bharat Heavy Electricals Ltd.' },
    { symbol: 'THERMAX.NS', companyName: 'Thermax Ltd.' },
    { symbol: 'TRITURBINE.NS', companyName: 'Triveni Turbine Ltd.' },
    { symbol: 'ELGIEQUIP.NS', companyName: 'Elgi Equipments Ltd.' },
    { symbol: 'KEC.NS', companyName: 'KEC International Ltd.' },
    { symbol: 'KALPATPOWR.NS', companyName: 'Kalpataru Projects International Ltd.' },
    { symbol: 'RVNL.NS', companyName: 'Rail Vikas Nigam Ltd.' },
    { symbol: 'IRCTC.NS', companyName: 'Indian Railway Catering and Tourism Corporation Ltd.' },
    { symbol: 'IRCON.NS', companyName: 'Ircon International Ltd.' },
    { symbol: 'RITES.NS', companyName: 'RITES Ltd.' },
    { symbol: 'RAILTEL.NS', companyName: 'RailTel Corporation of India Ltd.' },
    { symbol: 'TITAGARH.NS', companyName: 'Titagarh Rail Systems Ltd.' },
    { symbol: 'TEXRAIL.NS', companyName: 'Texmaco Rail & Engineering Ltd.' },
    { symbol: 'JWL.NS', companyName: 'Jupiter Wagons Ltd.' },

    // --- CONSUMER & RETAIL ---
    { symbol: 'TITAN.NS', companyName: 'Titan Company Ltd.' },
    { symbol: 'KALYANKJIL.NS', companyName: 'Kalyan Jewellers India Ltd.' },
    { symbol: 'RAJESHEXPO.NS', companyName: 'Rajesh Exports Ltd.' },
    { symbol: 'VAIBHAVGBL.NS', companyName: 'Vaibhav Global Ltd.' },
    { symbol: 'BATAINDIA.NS', companyName: 'Bata India Ltd.' },
    { symbol: 'RELAXO.NS', companyName: 'Relaxo Footwears Ltd.' },
    { symbol: 'METROBRAND.NS', companyName: 'Metro Brands Ltd.' },
    { symbol: 'CAMPUS.NS', companyName: 'Campus Activewear Ltd.' },
    { symbol: 'PAGEIND.NS', companyName: 'Page Industries Ltd.' },
    { symbol: 'LUXIND.NS', companyName: 'Lux Industries Ltd.' },
    { symbol: 'RUPA.NS', companyName: 'Rupa & Company Ltd.' },
    { symbol: 'DOLLAR.NS', companyName: 'Dollar Industries Ltd.' },
    { symbol: 'GOKEX.NS', companyName: 'Gokaldas Exports Ltd.' },
    { symbol: 'KPRMILL.NS', companyName: 'K.P.R. Mill Ltd.' },
    { symbol: 'WELSPUNIND.NS', companyName: 'Welspun Living Ltd.' },
    { symbol: 'TRIDENT.NS', companyName: 'Trident Ltd.' },
    { symbol: 'RAYMOND.NS', companyName: 'Raymond Ltd.' },
    { symbol: 'ARVIND.NS', companyName: 'Arvind Ltd.' },

    // --- FMCG ---
    { symbol: 'MARICO.NS', companyName: 'Marico Ltd.' },
    { symbol: 'EMAMILTD.NS', companyName: 'Emami Ltd.' },
    { symbol: 'JYOTHYLAB.NS', companyName: 'Jyothy Labs Ltd.' },
    { symbol: 'BAJAJCON.NS', companyName: 'Bajaj Consumer Care Ltd.' },
    { symbol: 'VBL.NS', companyName: 'Varun Beverages Ltd.' },
    { symbol: 'UBL.NS', companyName: 'United Breweries Ltd.' },
    { symbol: 'RADICO.NS', companyName: 'Radico Khaitan Ltd.' },
    { symbol: 'SULA.NS', companyName: 'Sula Vineyards Ltd.' },
    { symbol: 'GMMPFAUDLR.NS', companyName: 'GMM Pfaudler Ltd.' },
    { symbol: 'JUBLFOOD.NS', companyName: 'Jubilant FoodWorks Ltd.' },
    { symbol: 'DEVYANI.NS', companyName: 'Devyani International Ltd.' },
    { symbol: 'SAPPHIRE.NS', companyName: 'Sapphire Foods India Ltd.' },
    { symbol: 'WESTLIFE.NS', companyName: 'Westlife Foodworld Ltd.' },
    { symbol: 'RESTAURANT.NS', companyName: 'Restaurant Brands Asia Ltd.' },
    { symbol: 'BARBEQUE.NS', companyName: 'Barbeque Nation Hospitality Ltd.' },
    { symbol: 'DODLA.NS', companyName: 'Dodla Dairy Ltd.' },
    { symbol: 'HERITGFOOD.NS', companyName: 'Heritage Foods Ltd.' },
    { symbol: 'HATSON.NS', companyName: 'Hatsun Agro Product Ltd.' },
    { symbol: 'VADILALIND.NS', companyName: 'Vadilal Industries Ltd.' },
    { symbol: 'TASTYBITE.NS', companyName: 'Tasty Bite Eatables Ltd.' },
    { symbol: 'ADFZOODS.NS', companyName: 'ADF Foods Ltd.' },
    { symbol: 'LTFOODS.NS', companyName: 'LT Foods Ltd.' },
    { symbol: 'KRBL.NS', companyName: 'KRBL Ltd.' },
    { symbol: 'DAAWAT.NS', companyName: 'LT Foods Ltd' }, // Duplicate check
    { symbol: 'CCL.NS', companyName: 'CCL Products (India) Ltd.' },

    // --- CHEMICALS & FERTILIZERS ---
    { symbol: 'PIIND.NS', companyName: 'PI Industries Ltd.' },
    { symbol: 'UPL.NS', companyName: 'UPL Ltd.' },
    { symbol: 'COROMANDEL.NS', companyName: 'Coromandel International Ltd.' },
    { symbol: 'CHAMBLFERT.NS', companyName: 'Chambal Fertilisers and Chemicals Ltd.' },
    { symbol: 'GNFC.NS', companyName: 'Gujarat Narmada Valley Fertilizers & Chemicals Ltd.' },
    { symbol: 'GSFC.NS', companyName: 'Gujarat State Fertilizers & Chemicals Ltd.' },
    { symbol: 'RCF.NS', companyName: 'Rashtriya Chemicals & Fertilizers Ltd.' },
    { symbol: 'FACT.NS', companyName: 'Fertilisers and Chemicals Travancore Ltd.' },
    { symbol: 'DEEPAKNTR.NS', companyName: 'Deepak Nitrite Ltd.' },
    { symbol: 'ALKYLAMINE.NS', companyName: 'Alkyl Amines Chemicals Ltd.' },
    { symbol: 'BALAMINES.NS', companyName: 'Balaji Amines Ltd.' },
    { symbol: 'AARTIIND.NS', companyName: 'Aarti Industries Ltd.' },
    { symbol: 'ATUL.NS', companyName: 'Atul Ltd.' },
    { symbol: 'VINATIORGA.NS', companyName: 'Vinati Organics Ltd.' },
    { symbol: 'NAVINFLUOR.NS', companyName: 'Navin Fluorine International Ltd.' },
    { symbol: 'FLUOROCHEM.NS', companyName: 'Gujarat Fluorochemicals Ltd.' },
    { symbol: 'TATACHEM.NS', companyName: 'Tata Chemicals Ltd.' },
    { symbol: 'LINDEINDIA.NS', companyName: 'Linde India Ltd.' },
    { symbol: 'SOLARINDS.NS', companyName: 'Solar Industries India Ltd.' },

    // --- REAL ESTATE & CONSTRUCTION ---
    { symbol: 'DLF.NS', companyName: 'DLF Ltd.' },
    { symbol: 'LODHA.NS', companyName: 'Macrotech Developers Ltd.' },
    { symbol: 'GODREJPROP.NS', companyName: 'Godrej Properties Ltd.' },
    { symbol: 'OBEROIRLTY.NS', companyName: 'Oberoi Realty Ltd.' },
    { symbol: 'PRESTIGE.NS', companyName: 'Prestige Estates Projects Ltd.' },
    { symbol: 'PHOENIXLTD.NS', companyName: 'The Phoenix Mills Ltd.' },
    { symbol: 'BRIGADE.NS', companyName: 'Brigade Enterprises Ltd.' },
    { symbol: 'SOBHA.NS', companyName: 'Sobha Ltd.' },
    { symbol: 'MAHLIFE.NS', companyName: 'Mahindra Lifespace Developers Ltd.' },
    { symbol: 'SUNTECK.NS', companyName: 'Sunteck Realty Ltd.' },
    { symbol: 'IBREALEST.NS', companyName: 'Indiabulls Real Estate Ltd.' },
    { symbol: 'NCC.NS', companyName: 'NCC Ltd.' },
    { symbol: 'NBCC.NS', companyName: 'NBCC (India) Ltd.' },
    { symbol: 'PNCINFRA.NS', companyName: 'PNC Infratech Ltd.' },
    { symbol: 'KNRCON.NS', companyName: 'KNR Constructions Ltd.' },
    { symbol: 'ASHOKA.NS', companyName: 'Ashoka Buildcon Ltd.' },
    { symbol: 'IRB.NS', companyName: 'IRB Infrastructure Developers Ltd.' },
    { symbol: 'GRINFRA.NS', companyName: 'G R Infraprojects Ltd.' },
    { symbol: 'HGINFRA.NS', companyName: 'H.G. Infra Engineering Ltd.' },

    // --- METALS & MINING ---
    { symbol: 'TATASTEEL.NS', companyName: 'Tata Steel Ltd.' },
    { symbol: 'JSWSTEEL.NS', companyName: 'JSW Steel Ltd.' },
    { symbol: 'HINDALCO.NS', companyName: 'Hindalco Industries Ltd.' },
    { symbol: 'JINDALSTEL.NS', companyName: 'Jindal Steel & Power Ltd.' },
    { symbol: 'SAIL.NS', companyName: 'Steel Authority of India Ltd.' },
    { symbol: 'VEDL.NS', companyName: 'Vedanta Ltd.' },
    { symbol: 'HINDZINC.NS', companyName: 'Hindustan Zinc Ltd.' },
    { symbol: 'NMDC.NS', companyName: 'NMDC Ltd.' },
    { symbol: 'COALINDIA.NS', companyName: 'Coal India Ltd.' },
    { symbol: 'NATIONALUM.NS', companyName: 'National Aluminium Company Ltd.' },
    { symbol: 'HINDCOPPER.NS', companyName: 'Hindustan Copper Ltd.' },
    { symbol: 'MOIL.NS', companyName: 'MOIL Ltd.' },
    { symbol: 'GPIL.NS', companyName: 'Godawari Power & Ispat Ltd.' },
    { symbol: 'JSL.NS', companyName: 'Jindal Stainless Ltd.' },
    { symbol: 'APLAPOLLO.NS', companyName: 'APL Apollo Tubes Ltd.' },
    { symbol: 'WELCORP.NS', companyName: 'Welspun Corp Ltd.' },
    { symbol: 'MAHSEAMLES.NS', companyName: 'Maharashtra Seamless Ltd.' },

    // --- TELECOM & MEDIA ---
    { symbol: 'BHARTIARTL.NS', companyName: 'Bharti Airtel Ltd.' },
    { symbol: 'IDEA.NS', companyName: 'Vodafone Idea Ltd.' },
    { symbol: 'TATACOMM.NS', companyName: 'Tata Communications Ltd.' },
    { symbol: 'INDUSTOWER.NS', companyName: 'Indus Towers Ltd.' },
    { symbol: 'TEJASNET.NS', companyName: 'Tejas Networks Ltd.' },
    { symbol: 'HFCL.NS', companyName: 'HFCL Ltd.' },
    { symbol: 'ITI.NS', companyName: 'ITI Ltd.' },
    { symbol: 'SUNTV.NS', companyName: 'Sun TV Network Ltd.' },
    { symbol: 'ZEEL.NS', companyName: 'Zee Entertainment Enterprises Ltd.' },
    { symbol: 'PVRINOX.NS', companyName: 'PVR INOX Ltd.' },
    { symbol: 'NETWORK18.NS', companyName: 'Network18 Media & Investments Ltd.' },
    { symbol: 'TV18BRDCST.NS', companyName: 'TV18 Broadcast Ltd.' },
    { symbol: 'DBC.NS', companyName: 'D.B. Corp Ltd.' },
    { symbol: 'JAGRAN.NS', companyName: 'Jagran Prakashan Ltd.' },

    // --- MISCELLANEOUS ---
    { symbol: 'ADANIPORTS.NS', companyName: 'Adani Ports and SEZ' },
    { symbol: 'GPPL.NS', companyName: 'Gujarat Pipavav Port Ltd.' },
    { symbol: 'MAHLOG.NS', companyName: 'Mahindra Logistics Ltd.' },
    { symbol: 'TCIEXP.NS', companyName: 'TCI Express Ltd.' },
    { symbol: 'VRLLOG.NS', companyName: 'VRL Logistics Ltd.' },
    { symbol: 'BLUEDART.NS', companyName: 'Blue Dart Express Ltd.' },
    { symbol: 'CONCOR.NS', companyName: 'Container Corporation of India Ltd.' },
    { symbol: 'AEGISCHEM.NS', companyName: 'Aegis Logistics Ltd.' },
    { symbol: 'GSPL.NS', companyName: 'Gujarat State Petronet Ltd.' },
    { symbol: 'NYKAA.NS', companyName: 'FSN E-Commerce Ventures Ltd. (Nykaa)' }, // Duplicate check: FSN.NS
    { symbol: 'ZOMATO.NS', companyName: 'Zomato Ltd.' },
    { symbol: 'PAYTM.NS', companyName: 'Paytm' },
    { symbol: 'POLICYBZR.NS', companyName: 'PB Fintech' },
    { symbol: 'CARTRADE.NS', companyName: 'CarTrade Tech Ltd.' },
    { symbol: 'EASEMYTRIP.NS', companyName: 'Easy Trip Planners Ltd.' },
    { symbol: 'RATEGAIN.NS', companyName: 'RateGain Travel Technologies Ltd.' },
    { symbol: 'KAYNES.NS', companyName: 'Kaynes Technology India Ltd.' },
    { symbol: 'SYRMA.NS', companyName: 'Syrma SGS Technology Ltd.' },
    { symbol: 'AVALON.NS', companyName: 'Avalon Technologies Ltd.' },
    { symbol: 'IKIO.NS', companyName: 'IKIO Lighting Ltd.' },
    { symbol: 'CYIENTDLM.NS', companyName: 'Cyient DLM Ltd.' },
    { symbol: 'NETWEB.NS', companyName: 'Netweb Technologies India Ltd.' },

];
