export const MICRO_STOCKS_2 = [
  // --- E ---
  { symbol: 'EASEMYTRIP.NS', companyName: 'Easy Trip Planners Ltd.' },
  { symbol: 'ECLERX.NS', companyName: 'eClerx Services Ltd.' },
  { symbol: 'EDELWEISS.NS', companyName: 'Edelweiss Financial Services Ltd.' },
  { symbol: 'EIDPARRY.NS', companyName: 'E.I.D. - Parry (India) Ltd.' },
  { symbol: 'EIHAHOTELS.NS', companyName: 'EIH Associated Hotels Ltd.' },
  { symbol: 'EIJHOTELS.NS', companyName: 'EIH Ltd.' },
  { symbol: 'EIMCOELECO.NS', companyName: 'Eimco Elecon (India) Ltd.' },
  { symbol: 'EKC.NS', companyName: 'Everest Kanto Cylinder Ltd.' },
  { symbol: 'ELECON.NS', companyName: 'Elecon Engineering Company Ltd.' },
  { symbol: 'ELECTCAST.NS', companyName: 'Electrosteel Castings Ltd.' },
  { symbol: 'ELECTHERM.NS', companyName: 'Electrotherm (India) Ltd.' },
  { symbol: 'ELGIEQUIP.NS', companyName: 'Elgi Equipments Ltd.' },
  { symbol: 'ELGIRUBCO.NS', companyName: 'Elgi Rubber Company Ltd.' },
  { symbol: 'EMAMILTD.NS', companyName: 'Emami Ltd.' },
  { symbol: 'EMAMIPAP.NS', companyName: 'Emami Paper Mills Ltd.' },
  { symbol: 'EMAMIREAL.NS', companyName: 'Emami Realty Ltd.' },
  { symbol: 'EMIL.NS', companyName: 'Electronics Mart India Ltd.' },
  { symbol: 'EMKAY.NS', companyName: 'Emkay Global Financial Services Ltd.' },
  { symbol: 'EMMBI.NS', companyName: 'Emmbi Industries Ltd.' },
  { symbol: 'ENDURANCE.NS', companyName: 'Endurance Technologies Ltd.' },
  { symbol: 'ENERGYDEV.NS', companyName: 'Energy Development Company Ltd.' },
  { symbol: 'ENGINERSIN.NS', companyName: 'Engineers India Ltd.' },
  { symbol: 'ENIL.NS', companyName: 'Entertainment Network (India) Ltd.' },
  { symbol: 'EPL.NS', companyName: 'EPL Ltd.' },
  {
    symbol: 'EQUIPPP.NS',
    companyName: 'Equippp Social Impact Technologies Ltd.',
  },
  { symbol: 'EQUITASBNK.NS', companyName: 'Equitas Small Finance Bank Ltd.' },
  { symbol: 'ERIS.NS', companyName: 'Eris Lifesciences Ltd.' },
  { symbol: 'EROSMEDIA.NS', companyName: 'Eros International Media Ltd.' },
  { symbol: 'ESABINDIA.NS', companyName: 'ESAB India Ltd.' },
  { symbol: 'ESCORTS.NS', companyName: 'Escorts Kubota Ltd.' },
  { symbol: 'ESSARSHPNG.NS', companyName: 'Essar Shipping Ltd.' },
  { symbol: 'ESTER.NS', companyName: 'Ester Industries Ltd.' },
  { symbol: 'ETHOSLTD.NS', companyName: 'Ethos Ltd.' },
  { symbol: 'EVEREADY.NS', companyName: 'Eveready Industries India Ltd.' },
  { symbol: 'EVERESTIND.NS', companyName: 'Everest Industries Ltd.' },
  { symbol: 'EXCELINDUS.NS', companyName: 'Excel Industries Ltd.' },
  { symbol: 'EXIDEIND.NS', companyName: 'Exide Industries Ltd.' },
  { symbol: 'EXPLEOSOL.NS', companyName: 'Expleo Solutions Ltd.' },
  { symbol: 'EXXARO.NS', companyName: 'Exxaro Tiles Ltd.' },

  // --- F ---
  {
    symbol: 'FACT.NS',
    companyName: 'The Fertilisers and Chemicals Travancore Ltd.',
  },
  { symbol: 'FAIRCHEMOR.NS', companyName: 'Fairchem Organics Ltd.' },
  { symbol: 'FCL.NS', companyName: 'Fineotex Chemical Ltd.' },
  { symbol: 'FDC.NS', companyName: 'FDC Ltd.' },
  { symbol: 'FEDERALBNK.NS', companyName: 'The Federal Bank Ltd.' },
  { symbol: 'FEL.NS', companyName: 'Future Enterprises Ltd.' },
  { symbol: 'FEMTO.NS', companyName: 'Femto' }, // Check
  { symbol: 'FIBERWEB.NS', companyName: 'Fiberweb (India) Ltd.' },
  { symbol: 'FIEMIND.NS', companyName: 'Fiem Industries Ltd.' },
  { symbol: 'FILATEX.NS', companyName: 'Filatex India Ltd.' },
  { symbol: 'FINCABLES.NS', companyName: 'Finolex Cables Ltd.' },
  { symbol: 'FINEORG.NS', companyName: 'Fine Organic Industries Ltd.' },
  { symbol: 'FINOPB.NS', companyName: 'Fino Payments Bank Ltd.' },
  { symbol: 'FINPIPE.NS', companyName: 'Finolex Industries Ltd.' },
  { symbol: 'FIVESTAR.NS', companyName: 'Five-Star Business Finance Ltd.' },
  { symbol: 'FLAIR.NS', companyName: 'Flair Writing Industries Ltd.' },
  {
    symbol: 'FLEXITUFF.NS',
    companyName: 'Flexituff Ventures International Ltd.',
  },
  { symbol: 'FLFL.NS', companyName: 'Future Lifestyle Fashions Ltd.' },
  { symbol: 'FLUOROCHEM.NS', companyName: 'Gujarat Fluorochemicals Ltd.' },
  { symbol: 'FMGOETZE.NS', companyName: 'Federal-Mogul Goetze (India) Ltd.' },
  { symbol: 'FOCUS.NS', companyName: 'Focus Lighting and Fixtures Ltd.' },
  { symbol: 'FOODSIN.NS', companyName: 'Foods & Inns Ltd.' },
  { symbol: 'FORCEMOT.NS', companyName: 'Force Motors Ltd.' },
  { symbol: 'FORTIS.NS', companyName: 'Fortis Healthcare Ltd.' },
  { symbol: 'FOSECOIND.NS', companyName: 'Foseco India Ltd.' },
  { symbol: 'FSL.NS', companyName: 'Firstsource Solutions Ltd.' },
  { symbol: 'FUSION.NS', companyName: 'Fusion Micro Finance Ltd.' },

  // --- G ---
  { symbol: 'GABRIEL.NS', companyName: 'Gabriel India Ltd.' },
  { symbol: 'GAEL.NS', companyName: 'Gujarat Ambuja Exports Ltd.' },
  { symbol: 'GAIL.NS', companyName: 'GAIL (India) Ltd.' },
  { symbol: 'GALAXYSURF.NS', companyName: 'Galaxy Surfactants Ltd.' },
  { symbol: 'GALLANTT.NS', companyName: 'Gallantt Ispat Ltd.' },
  { symbol: 'GANDHAR.NS', companyName: 'Gandhar Oil Refinery (India) Ltd.' },
  { symbol: 'GANECOS.NS', companyName: 'Ganesha Ecosphere Ltd.' },
  { symbol: 'GANESHBE.NS', companyName: 'Ganesh Benzoplast Ltd.' },
  { symbol: 'GANESHHOUC.NS', companyName: 'Ganesh Housing Corporation Ltd.' },
  { symbol: 'GANGAFORGE.NS', companyName: 'Ganga Forging Ltd.' },
  { symbol: 'GANGESSECU.NS', companyName: 'Ganges Securities Ltd.' },
  { symbol: 'GARFIBRES.NS', companyName: 'Garware Technical Fibres Ltd.' },
  { symbol: 'GATEWAY.NS', companyName: 'Gateway Distriparks Ltd.' },
  { symbol: 'GATI.NS', companyName: 'Gati Ltd.' }, // Allcargo Gati
  { symbol: 'GAYAPROJ.NS', companyName: 'Gayatri Projects Ltd.' },
  { symbol: 'GEECEE.NS', companyName: 'GeeCee Ventures Ltd.' },
  { symbol: 'GEEKAYWIRE.NS', companyName: 'Geekay Wires Ltd.' },
  {
    symbol: 'GENCON.NS',
    companyName: 'Generic Engineering Construction and Projects Ltd.',
  },
  {
    symbol: 'GENESYS.NS',
    companyName: 'Genesys International Corporation Ltd.',
  },
  { symbol: 'GENSOL.NS', companyName: 'Gensol Engineering Ltd.' },
  { symbol: 'GENUSPAPER.NS', companyName: 'Genus Paper & Boards Ltd.' },
  { symbol: 'GENUSPOWER.NS', companyName: 'Genus Power Infrastructures Ltd.' },
  { symbol: 'GEOJITFSL.NS', companyName: 'Geojit Financial Services Ltd.' },
  { symbol: 'GEPIL.NS', companyName: 'GE Power India Ltd.' },
  {
    symbol: 'GESHIP.NS',
    companyName: 'The Great Eastern Shipping Company Ltd.',
  },
  { symbol: 'GET&D.NS', companyName: 'GE T&D India Ltd.' },
  { symbol: 'GHCL.NS', companyName: 'GHCL Ltd.' },
  { symbol: 'GHCLTEXTIL.NS', companyName: 'GHCL Textiles Ltd.' },
  { symbol: 'GICHSGFIN.NS', companyName: 'GIC Housing Finance Ltd.' },
  { symbol: 'GICRE.NS', companyName: 'General Insurance Corporation of India' },
  { symbol: 'GILLANDERS.NS', companyName: 'Gillanders Arbuthnot & Co. Ltd.' },
  { symbol: 'GILLETTE.NS', companyName: 'Gillette India Ltd.' },
  { symbol: 'GINNIFILA.NS', companyName: 'Ginni Filaments Ltd.' },
  { symbol: 'GIPCL.NS', companyName: 'Gujarat Industries Power Company Ltd.' },
  { symbol: 'GLAND.NS', companyName: 'Gland Pharma Ltd.' },
  { symbol: 'GLAXO.NS', companyName: 'GlaxoSmithKline Pharmaceuticals Ltd.' },
  { symbol: 'GLENMARK.NS', companyName: 'Glenmark Pharmaceuticals Ltd.' },
  { symbol: 'GLFL.NS', companyName: 'Gujarat Lease Financing Ltd.' },
  { symbol: 'GLOBAL.NS', companyName: 'Global Education Ltd.' },
  { symbol: 'GLOBALVECT.NS', companyName: 'Global Vectra Helicorp Ltd.' },
  { symbol: 'GLOBE.NS', companyName: 'Globe Textiles (India) Ltd.' },
  { symbol: 'GLOBOFFS.NS', companyName: 'Global Offshore Services Ltd.' },
  { symbol: 'GLOBUSSPR.NS', companyName: 'Globus Spirits Ltd.' },
  { symbol: 'GLS.NS', companyName: 'Glenmark Life Sciences Ltd.' },
  { symbol: 'GMBREW.NS', companyName: 'GM Breweries Ltd.' },
  {
    symbol: 'GMDCLTD.NS',
    companyName: 'Gujarat Mineral Development Corporation Ltd.',
  },
  { symbol: 'GMMPFAUDLR.NS', companyName: 'GMM Pfaudler Ltd.' },
  { symbol: 'GMRINFRA.NS', companyName: 'GMR Airports Infrastructure Ltd.' },
  { symbol: 'GMRP&UI.NS', companyName: 'GMR Power and Urban Infra Ltd.' },
  { symbol: 'GNA.NS', companyName: 'GNA Axles Ltd.' },
  {
    symbol: 'GNFC.NS',
    companyName: 'Gujarat Narmada Valley Fertilizers & Chemicals Ltd.',
  },
  { symbol: 'GOACARBON.NS', companyName: 'Goa Carbon Ltd.' },
  { symbol: 'GOCLCORP.NS', companyName: 'GOCL Corporation Ltd.' },
  { symbol: 'GOCOLORS.NS', companyName: 'Go Fashion (India) Ltd.' },
  { symbol: 'GODFRYPHLP.NS', companyName: 'Godfrey Phillips India Ltd.' },
  { symbol: 'GODHA.NS', companyName: 'Godha Cabcon & Insulation Ltd.' },
  { symbol: 'GODREJAGRO.NS', companyName: 'Godrej Agrovet Ltd.' },
  { symbol: 'GODREJCP.NS', companyName: 'Godrej Consumer Products Ltd.' },
  { symbol: 'GODREJIND.NS', companyName: 'Godrej Industries Ltd.' },
  { symbol: 'GODREJPROP.NS', companyName: 'Godrej Properties Ltd.' },
  { symbol: 'GOENKA.NS', companyName: 'Goenka Diamond and Jewels Ltd.' },
  { symbol: 'GOKEX.NS', companyName: 'Gokaldas Exports Ltd.' },
  { symbol: 'GOKUL.NS', companyName: 'Gokul Refoils and Solvent Ltd.' },
  { symbol: 'GOKULAGRO.NS', companyName: 'Gokul Agro Resources Ltd.' },
  { symbol: 'GOLDENTOBC.NS', companyName: 'Golden Tobacco Ltd.' },
  { symbol: 'GOLDIAM.NS', companyName: 'Goldiam International Ltd.' },
  { symbol: 'GOLDTECH.NS', companyName: 'Goldstone Technologies Ltd.' },
  { symbol: 'GOODLUCK.NS', companyName: 'Goodluck India Ltd.' },
  { symbol: 'GOYALALUM.NS', companyName: 'Goyal Aluminiums Ltd.' },
  { symbol: 'GPIL.NS', companyName: 'Godawari Power & Ispat Ltd.' },
  { symbol: 'GPPL.NS', companyName: 'Gujarat Pipavav Port Ltd.' },
  { symbol: 'GPTINFRA.NS', companyName: 'GPT Infraprojects Ltd.' },
  { symbol: 'GRANULES.NS', companyName: 'Granules India Ltd.' },
  { symbol: 'GRAPHITE.NS', companyName: 'Graphite India Ltd.' },
  { symbol: 'GRASIM.NS', companyName: 'Grasim Industries Ltd.' },
  { symbol: 'GRAVITA.NS', companyName: 'Gravita India Ltd.' },
  { symbol: 'GREAVESCOT.NS', companyName: 'Greaves Cotton Ltd.' },
  { symbol: 'GREENLAM.NS', companyName: 'Greenlam Industries Ltd.' },
  { symbol: 'GREENPANEL.NS', companyName: 'Greenpanel Industries Ltd.' },
  { symbol: 'GREENPLY.NS', companyName: 'Greenply Industries Ltd.' },
  { symbol: 'GREENPOWER.NS', companyName: 'Orient Green Power Company Ltd.' },
  { symbol: 'GRINDWELL.NS', companyName: 'Grindwell Norton Ltd.' },
  { symbol: 'GRINFRA.NS', companyName: 'G R Infraprojects Ltd.' },
  { symbol: 'GRMOVER.NS', companyName: 'GRM Overseas Ltd.' },
  { symbol: 'GROBTEA.NS', companyName: 'The Grob Tea Company Ltd.' },
  { symbol: 'GRPL.NS', companyName: 'GRPL' }, // Check
  {
    symbol: 'GRSE.NS',
    companyName: 'Garden Reach Shipbuilders & Engineers Ltd.',
  },
  { symbol: 'GRWRHITECH.NS', companyName: 'Garware Hi-Tech Films Ltd.' },
  { symbol: 'GSCLCEMENT.NS', companyName: 'Gujarat Sidhee Cement Ltd.' },
  {
    symbol: 'GSFC.NS',
    companyName: 'Gujarat State Fertilizers & Chemicals Ltd.',
  },
  { symbol: 'GSPL.NS', companyName: 'Gujarat State Petronet Ltd.' },
  { symbol: 'GSS.NS', companyName: 'GSS Infotech Ltd.' },
  { symbol: 'GTL.NS', companyName: 'GTL Ltd.' },
  { symbol: 'GTLINFRA.NS', companyName: 'GTL Infrastructure Ltd.' },
  { symbol: 'GTPL.NS', companyName: 'GTPL Hathway Ltd.' },
  { symbol: 'GUFICBIO.NS', companyName: 'Gufic Biosciences Ltd.' },
  {
    symbol: 'GUJALKALI.NS',
    companyName: 'Gujarat Alkalies and Chemicals Ltd.',
  },
  { symbol: 'GUJAPOLLO.NS', companyName: 'Gujarat Apollo Industries Ltd.' },
  { symbol: 'GUJGASLTD.NS', companyName: 'Gujarat Gas Ltd.' },
  { symbol: 'GUJRAFFIA.NS', companyName: 'Gujarat Raffia Industries Ltd.' },
  { symbol: 'GULFPETRO.NS', companyName: 'Gulf Oil Lubricants India Ltd.' },
  { symbol: 'GULOILCORP.NS', companyName: 'Gulf Oil Corporation Ltd.' },
  { symbol: 'GULPOLY.NS', companyName: 'Gulf Oil Corporation' }, // Check
  { symbol: 'GVKPIL.NS', companyName: 'GVK Power & Infrastructure Ltd.' },

  // --- H ---
  { symbol: 'HAL.NS', companyName: 'Hindustan Aeronautics Ltd.' },
  { symbol: 'HAPPSTMNDS.NS', companyName: 'Happiest Minds Technologies Ltd.' },
  { symbol: 'HARDWYN.NS', companyName: 'Hardwyn India Ltd.' },
  { symbol: 'HARIOMPIPE.NS', companyName: 'Hariom Pipe Industries Ltd.' },
  { symbol: 'HARRMALAYA.NS', companyName: 'Harrisons Malayalam Ltd.' },
  { symbol: 'HARSHA.NS', companyName: 'Harsha Engineers International Ltd.' },
  { symbol: 'HATHWAY.NS', companyName: 'Hathway Cable & Datacom Ltd.' },
  { symbol: 'HATSUN.NS', companyName: 'Hatsun Agro Product Ltd.' },
  { symbol: 'HAVELLS.NS', companyName: 'Havells India Ltd.' },
  {
    symbol: 'HAVISHA.NS',
    companyName: 'Sri Havisha Hospitality and Infrastructure Ltd.',
  },
  { symbol: 'HBLPOWER.NS', companyName: 'HBL Power Systems Ltd.' },
  { symbol: 'HBSL.NS', companyName: 'HB Stockholdings Ltd.' },
  { symbol: 'HCC.NS', companyName: 'Hindustan Construction Company Ltd.' },
  { symbol: 'HCG.NS', companyName: 'HealthCare Global Enterprises Ltd.' },
  { symbol: 'HCL-INSYS.NS', companyName: 'HCL Infosystems Ltd.' },
  { symbol: 'HCLTECH.NS', companyName: 'HCL Technologies Ltd.' },
  { symbol: 'HDFCAMC.NS', companyName: 'HDFC Asset Management Company Ltd.' },
  { symbol: 'HDFCBANK.NS', companyName: 'HDFC Bank Ltd.' },
  { symbol: 'HDFCLIFE.NS', companyName: 'HDFC Life Insurance Company Ltd.' },
  {
    symbol: 'HDIL.NS',
    companyName: 'Housing Development and Infrastructure Ltd.',
  },
  { symbol: 'HEADSUP.NS', companyName: 'Heads UP Ventures Ltd.' },
  { symbol: 'HECPROJECT.NS', companyName: 'HEC Infra Projects Ltd.' },
  { symbol: 'HEG.NS', companyName: 'HEG Ltd.' },
  { symbol: 'HEIDELBERG.NS', companyName: 'HeidelbergCement India Ltd.' },
  { symbol: 'HEMIPROP.NS', companyName: 'Hemisphere Properties India Ltd.' },
  { symbol: 'HERANBA.NS', companyName: 'Heranba Industries Ltd.' },
  { symbol: 'HERCULES.NS', companyName: 'Hercules Hoists Ltd.' },
  { symbol: 'HERITGFOOD.NS', companyName: 'Heritage Foods Ltd.' },
  { symbol: 'HEROMOTOCO.NS', companyName: 'Hero MotoCorp Ltd.' },
  { symbol: 'HESTERBIO.NS', companyName: 'Hester Biosciences Ltd.' },
  { symbol: 'HEXATRADEX.NS', companyName: 'Hexa Tradex Ltd.' },
  { symbol: 'HFCL.NS', companyName: 'HFCL Ltd.' },
  { symbol: 'HGINFRA.NS', companyName: 'H.G. Infra Engineering Ltd.' },
  { symbol: 'HGS.NS', companyName: 'Hinduja Global Solutions Ltd.' },
  { symbol: 'HIKAL.NS', companyName: 'Hikal Ltd.' },
  { symbol: 'HIL.NS', companyName: 'HIL Ltd.' },
  { symbol: 'HILTON.NS', companyName: 'Hilton Metal Forging Ltd.' },
  { symbol: 'HIMATSEIDE.NS', companyName: 'Himatsingka Seide Ltd.' },
  { symbol: 'HINDALCO.NS', companyName: 'Hindalco Industries Ltd.' },
  { symbol: 'HINDCOMPOS.NS', companyName: 'Hindustan Composites Ltd.' },
  { symbol: 'HINDCON.NS', companyName: 'Hindcon Chemicals Ltd.' },
  { symbol: 'HINDCOPPER.NS', companyName: 'Hindustan Copper Ltd.' },
  { symbol: 'HINDMOTORS.NS', companyName: 'Hindustan Motors Ltd.' },
  {
    symbol: 'HINDNATGLS.NS',
    companyName: 'Hindusthan National Glass & Industries Ltd.',
  },
  {
    symbol: 'HINDOILEXP.NS',
    companyName: 'Hindustan Oil Exploration Company Ltd.',
  },
  {
    symbol: 'HINDPETRO.NS',
    companyName: 'Hindustan Petroleum Corporation Ltd.',
  },
  { symbol: 'HINDUNILVR.NS', companyName: 'Hindustan Unilever Ltd.' },
  { symbol: 'HINDWAREAP.NS', companyName: 'Hindware Home Innovation Ltd.' },
  { symbol: 'HINDZINC.NS', companyName: 'Hindustan Zinc Ltd.' },
  { symbol: 'HIRECT.NS', companyName: 'Hind Rectifiers Ltd.' },
  { symbol: 'HISARMETAL.NS', companyName: 'Hisar Metal Industries Ltd.' },
  { symbol: 'HITECH.NS', companyName: 'Hi-Tech Pipes Ltd.' },
  { symbol: 'HITECHCORP.NS', companyName: 'Hitech Corporation Ltd.' },
  { symbol: 'HITECHGEAR.NS', companyName: 'The Hi-Tech Gears Ltd.' },
  { symbol: 'HLEGLAS.NS', companyName: 'HLE Glascoat Ltd.' },
  { symbol: 'HLVLTD.NS', companyName: 'HLV Ltd.' },
  { symbol: 'HMT.NS', companyName: 'HMT Ltd.' },
  { symbol: 'HMVL.NS', companyName: 'Hindustan Media Ventures Ltd.' },
  { symbol: 'HNDFDS.NS', companyName: 'Hindustan Foods Ltd.' },
  {
    symbol: 'HOMEFIRST.NS',
    companyName: 'Home First Finance Company India Ltd.',
  },
  { symbol: 'HONASA.NS', companyName: 'Honasa Consumer Ltd.' },
  { symbol: 'HONAUT.NS', companyName: 'Honeywell Automation India Ltd.' },
  { symbol: 'HONDAPOWER.NS', companyName: 'Honda India Power Products Ltd.' },
  { symbol: 'HOVS.NS', companyName: 'HOVS Ltd.' },
  { symbol: 'HPAL.NS', companyName: 'HP Adhesives Ltd.' },
  { symbol: 'HPCL.NS', companyName: 'Hindustan Petroleum Corporation Ltd.' },
  { symbol: 'HPL.NS', companyName: 'HPL Electric & Power Ltd.' },
  { symbol: 'HSCL.NS', companyName: 'Himadri Speciality Chemical Ltd.' },
  { symbol: 'HTMEDIA.NS', companyName: 'HT Media Ltd.' },
  { symbol: 'HUBTOWN.NS', companyName: 'Hubtown Ltd.' },
  {
    symbol: 'HUDCO.NS',
    companyName: 'Housing and Urban Development Corporation Ltd.',
  },
  { symbol: 'HUHTAMAKI.NS', companyName: 'Huhtamaki India Ltd.' },
  { symbol: 'HYBRIDFIN.NS', companyName: 'Hybrid Financial Services Ltd.' },

  // --- I ---
  { symbol: 'IBL.NS', companyName: 'Indbank Merchant Banking Services Ltd.' },
  { symbol: 'IBREALEST.NS', companyName: 'Indiabulls Real Estate Ltd.' },
  { symbol: 'IBULHSGFIN.NS', companyName: 'Indiabulls Housing Finance Ltd.' },
  { symbol: 'ICEMAKE.NS', companyName: 'Ice Make Refrigeration Ltd.' },
  { symbol: 'ICICIBANK.NS', companyName: 'ICICI Bank Ltd.' },
  {
    symbol: 'ICICIGI.NS',
    companyName: 'ICICI Lombard General Insurance Company Ltd.',
  },
  {
    symbol: 'ICICIPRULI.NS',
    companyName: 'ICICI Prudential Life Insurance Company Ltd.',
  },
  { symbol: 'ICIL.NS', companyName: 'Indo Count Industries Ltd.' },
  { symbol: 'ICRA.NS', companyName: 'ICRA Ltd.' },
  { symbol: 'IDBI.NS', companyName: 'IDBI Bank Ltd.' },
  { symbol: 'IDEA.NS', companyName: 'Vodafone Idea Ltd.' },
  { symbol: 'IDFC.NS', companyName: 'IDFC Ltd.' },
  { symbol: 'IDFCFIRSTB.NS', companyName: 'IDFC First Bank Ltd.' },
  { symbol: 'IEX.NS', companyName: 'Indian Energy Exchange Ltd.' },
  { symbol: 'IFBAGRO.NS', companyName: 'IFB Agro Industries Ltd.' },
  { symbol: 'IFBIND.NS', companyName: 'IFB Industries Ltd.' },
  { symbol: 'IFCI.NS', companyName: 'IFCI Ltd.' },
  { symbol: 'IFGLEXPOR.NS', companyName: 'IFGL Refractories Ltd.' },
  { symbol: 'IGARASHI.NS', companyName: 'Igarashi Motors India Ltd.' },
  { symbol: 'IGL.NS', companyName: 'Indraprastha Gas Ltd.' },
  { symbol: 'IGPL.NS', companyName: 'IG Petrochemicals Ltd.' },
  { symbol: 'IIFL.NS', companyName: 'IIFL Finance Ltd.' },
  { symbol: 'IIFLSEC.NS', companyName: 'IIFL Securities Ltd.' },
  { symbol: 'IITL.NS', companyName: 'Industrial Investment Trust Ltd.' },
  { symbol: 'IKIO.NS', companyName: 'IKIO Lighting Ltd.' },
  {
    symbol: 'IL&FSENGG.NS',
    companyName: 'IL&FS Engineering and Construction Company Ltd.',
  },
  {
    symbol: 'IL&FSTRANS.NS',
    companyName: 'IL&FS Transportation Networks Ltd.',
  },
  { symbol: 'IMAGICAA.NS', companyName: 'Imagicaaworld Entertainment Ltd.' },
  { symbol: 'IMFA.NS', companyName: 'Indian Metals & Ferro Alloys Ltd.' },
  { symbol: 'IMPAL.NS', companyName: 'India Motor Parts & Accessories Ltd.' },
  { symbol: 'IMPEXFERRO.NS', companyName: 'Impex Ferro Tech Ltd.' },
  { symbol: 'INCR.NS', companyName: 'Incredible Industries Ltd.' },
  {
    symbol: 'INDBANK.NS',
    companyName: 'Indbank Merchant Banking Services Ltd.',
  },
  { symbol: 'INDHOTEL.NS', companyName: 'The Indian Hotels Company Ltd.' },
  { symbol: 'INDIACEM.NS', companyName: 'The India Cements Ltd.' },
  { symbol: 'INDIAGLYCO.NS', companyName: 'India Glycols Ltd.' },
  { symbol: 'INDIAMART.NS', companyName: 'IndiaMART InterMESH Ltd.' },
  { symbol: 'INDIANB.NS', companyName: 'Indian Bank' },
  { symbol: 'INDIANCARD.NS', companyName: 'Indian Card Clothing Company Ltd.' },
  { symbol: 'INDIANHUME.NS', companyName: 'Indian Hume Pipe Company Ltd.' },
  { symbol: 'INDIGO.NS', companyName: 'InterGlobe Aviation Ltd.' },
  { symbol: 'INDIGOPNTS.NS', companyName: 'Indigo Paints Ltd.' },
  { symbol: 'INDIMP.NS', companyName: 'Ind-Swift Ltd.' },
  { symbol: 'INDNIPPON.NS', companyName: 'India Nippon Electricals Ltd.' },
  { symbol: 'INDOAMIN.NS', companyName: 'Indo Amines Ltd.' },
  { symbol: 'INDOBORAX.NS', companyName: 'Indo Borax & Chemicals Ltd.' },
  { symbol: 'INDOCO.NS', companyName: 'Indoco Remedies Ltd.' },
  { symbol: 'INDORAMA.NS', companyName: 'Indo Rama Synthetics (India) Ltd.' },
  { symbol: 'INDOSTAR.NS', companyName: 'IndoStar Capital Finance Ltd.' },
  { symbol: 'INDOTECH.NS', companyName: 'Indo Tech Transformers Ltd.' },
  { symbol: 'INDOTHAI.NS', companyName: 'Indo Thai Securities Ltd.' },
  { symbol: 'INDOWIND.NS', companyName: 'Indowind Energy Ltd.' },
  {
    symbol: 'INDRAMEDCO.NS',
    companyName: 'Indraprastha Medical Corporation Ltd.',
  },
  { symbol: 'INDSWFTLAB.NS', companyName: 'Ind-Swift Laboratories Ltd.' },
  { symbol: 'INDTERRAIN.NS', companyName: 'Indian Terrain Fashions Ltd.' },
  { symbol: 'INDUSINDBK.NS', companyName: 'IndusInd Bank Ltd.' },
  { symbol: 'INDUSTOWER.NS', companyName: 'Indus Towers Ltd.' },
  { symbol: 'INFIBEAM.NS', companyName: 'Infibeam Avenues Ltd.' },
  { symbol: 'INFOBEAN.NS', companyName: 'InfoBeans Technologies Ltd.' },
  { symbol: 'INFOMEDIA.NS', companyName: 'Infomedia Press Ltd.' },
  { symbol: 'INFY.NS', companyName: 'Infosys Ltd.' },
  { symbol: 'INGERRAND.NS', companyName: 'Ingersoll Rand (India) Ltd.' },
  { symbol: 'INNOVANA.NS', companyName: 'Innovana Thinklabs Ltd.' },
  { symbol: 'INNOVA.NS', companyName: 'Innova Captab Ltd.' }, // Check
  { symbol: 'INOXGREEN.NS', companyName: 'Inox Green Energy Services Ltd.' },
  { symbol: 'INOXINDIA.NS', companyName: 'INOX India Ltd.' },
  { symbol: 'INOXWIND.NS', companyName: 'Inox Wind Ltd.' },
  { symbol: 'INSECTICID.NS', companyName: 'Insecticides (India) Ltd.' },
  { symbol: 'INSPIRISYS.NS', companyName: 'Inspirisys Solutions Ltd.' },
  { symbol: 'INTELLECT.NS', companyName: 'Intellect Design Arena Ltd.' },
  { symbol: 'INTENSE.NS', companyName: 'Intense Technologies Ltd.' },
  { symbol: 'INTLCONV.NS', companyName: 'International Conveyors Ltd.' },
  { symbol: 'INVENTURE.NS', companyName: 'Inventure Growth & Securities Ltd.' },
  { symbol: 'IOB.NS', companyName: 'Indian Overseas Bank' },
  { symbol: 'IOC.NS', companyName: 'Indian Oil Corporation Ltd.' },
  { symbol: 'IOLCP.NS', companyName: 'IOL Chemicals and Pharmaceuticals Ltd.' },
  { symbol: 'IPCALAB.NS', companyName: 'IPCA Laboratories Ltd.' },
  { symbol: 'IPL.NS', companyName: 'India Pesticides Ltd.' },
  { symbol: 'IRB.NS', companyName: 'IRB Infrastructure Developers Ltd.' },
  { symbol: 'IRCON.NS', companyName: 'Ircon International Ltd.' },
  {
    symbol: 'IRCTC.NS',
    companyName: 'Indian Railway Catering and Tourism Corporation Ltd.',
  },
  { symbol: 'IRFC.NS', companyName: 'Indian Railway Finance Corporation Ltd.' },
  { symbol: 'IRIS.NS', companyName: 'Iris Business Services Ltd.' },
  { symbol: 'IRISDOREME.NS', companyName: 'Iris Clothings Ltd.' },
  { symbol: 'ISEC.NS', companyName: 'ICICI Securities Ltd.' },
  { symbol: 'ISFT.NS', companyName: 'Intrasoft Technologies Ltd.' },
  { symbol: 'ISGEC.NS', companyName: 'Isgec Heavy Engineering Ltd.' },
  { symbol: 'ISMTLTD.NS', companyName: 'ISMT Ltd.' },
  { symbol: 'IST.NS', companyName: 'IST Ltd.' },
  { symbol: 'ITBEES.NS', companyName: 'ITBees' }, // remove
  { symbol: 'ITC.NS', companyName: 'ITC Ltd.' },
  {
    symbol: 'ITDC.NS',
    companyName: 'India Tourism Development Corporation Ltd.',
  },
  { symbol: 'ITDCEM.NS', companyName: 'ITD Cementation India Ltd.' },
  { symbol: 'ITI.NS', companyName: 'ITI Ltd.' },
  { symbol: 'IVC.NS', companyName: 'IL&FS Investment Managers Ltd.' },
  { symbol: 'IVP.NS', companyName: 'IVP Ltd.' },
  { symbol: 'IZMO.NS', companyName: 'Izmo Ltd.' },

  // --- J ---
  { symbol: 'J&KBANK.NS', companyName: 'The Jammu & Kashmir Bank Ltd.' },
  { symbol: 'JAGRAN.NS', companyName: 'Jagran Prakashan Ltd.' },
  { symbol: 'JAGSNPHARM.NS', companyName: 'Jagsonpal Pharmaceuticals Ltd.' },
  { symbol: 'JAIBALAJI.NS', companyName: 'Jai Balaji Industries Ltd.' },
  { symbol: 'JAICORPLTD.NS', companyName: 'Jai Corp Ltd.' },
  { symbol: 'JAIPURKURT.NS', companyName: 'Nandani Creation Ltd.' },
  { symbol: 'JAMNAAUTO.NS', companyName: 'Jamna Auto Industries Ltd.' },
  { symbol: 'JASH.NS', companyName: 'Jash Engineering Ltd.' },
  { symbol: 'JAYAGROGN.NS', companyName: 'Jayant Agro-Organics Ltd.' },
  { symbol: 'JAYBARMARU.NS', companyName: 'Jay Bharat Maruti Ltd.' },
  { symbol: 'JAYNECOIND.NS', companyName: 'Jayaswal Neco Industries Ltd.' },
  { symbol: 'JAYSREETEA.NS', companyName: 'Jayshree Tea & Industries Ltd.' },
  {
    symbol: 'JBCHEPHARM.NS',
    companyName: 'J.B. Chemicals & Pharmaceuticals Ltd.',
  },
  { symbol: 'JBMA.NS', companyName: 'JBM Auto Ltd.' },
  {
    symbol: 'JCHAC.NS',
    companyName: 'Johnson Controls - Hitachi Air Conditioning India Ltd.',
  },
  { symbol: 'JETAIRWAYS.NS', companyName: 'Jet Airways (India) Ltd.' },
  { symbol: 'JETFREIGHT.NS', companyName: 'Jet Freight Logistics Ltd.' },
  { symbol: 'JGCHEM.NS', companyName: 'J.G. Chemicals Ltd.' },
  { symbol: 'JHS.NS', companyName: 'JHS Svendgaard Laboratories Ltd.' },
  { symbol: 'JINDALCO.NS', companyName: 'Jindal Cotex Ltd.' }, // Check
  { symbol: 'JINDALPHOT.NS', companyName: 'Jindal Photo Ltd.' },
  { symbol: 'JINDALPOLY.NS', companyName: 'Jindal Poly Films Ltd.' },
  { symbol: 'JINDALSAW.NS', companyName: 'Jindal Saw Ltd.' },
  { symbol: 'JINDALSTEL.NS', companyName: 'Jindal Steel & Power Ltd.' },
  { symbol: 'JINDRILL.NS', companyName: 'Jindal Drilling & Industries Ltd.' },
  { symbol: 'JINDWORLD.NS', companyName: 'Jindal Worldwide Ltd.' },
  { symbol: 'JIOFIN.NS', companyName: 'Jio Financial Services Ltd.' },
  {
    symbol: 'JISLDVREQS.NS',
    companyName: 'Jain Irrigation Systems Ltd. (DVR)',
  },
  { symbol: 'JISLJALEQS.NS', companyName: 'Jain Irrigation Systems Ltd.' },
  { symbol: 'JITFINFRA.NS', companyName: 'JITF Infralogistics Ltd.' },
  { symbol: 'JKCEMENT.NS', companyName: 'JK Cement Ltd.' },
  { symbol: 'JKIL.NS', companyName: 'J. Kumar Infraprojects Ltd.' },
  { symbol: 'JKLAKSHMI.NS', companyName: 'JK Lakshmi Cement Ltd.' },
  { symbol: 'JKPAPER.NS', companyName: 'JK Paper Ltd.' },
  { symbol: 'JKTYRE.NS', companyName: 'JK Tyre & Industries Ltd.' },
  { symbol: 'JMA.NS', companyName: 'Jullundur Motor Agency (Delhi) Ltd.' },
  { symbol: 'JMCPROJECT.NS', companyName: 'JMC Projects (India) Ltd.' },
  { symbol: 'JMFINANCIL.NS', companyName: 'JM Financial Ltd.' },
  { symbol: 'JOCIL.NS', companyName: 'Jocil Ltd.' },
  { symbol: 'JPASSOCIAT.NS', companyName: 'Jaiprakash Associates Ltd.' },
  { symbol: 'JPINFRATEC.NS', companyName: 'Jaypee Infratech Ltd.' },
  { symbol: 'JPPOWER.NS', companyName: 'Jaiprakash Power Ventures Ltd.' },
  { symbol: 'JSL.NS', companyName: 'Jindal Stainless Ltd.' },
  { symbol: 'JSLHISAR.NS', companyName: 'Jindal Stainless (Hisar) Ltd.' },
  { symbol: 'JSWENERGY.NS', companyName: 'JSW Energy Ltd.' },
  { symbol: 'JSWHL.NS', companyName: 'JSW Holdings Ltd.' },
  { symbol: 'JSWINFRA.NS', companyName: 'JSW Infrastructure Ltd.' },
  { symbol: 'JSWISP.NS', companyName: 'JSW Ispat Special Products Ltd.' },
  { symbol: 'JSWSTEEL.NS', companyName: 'JSW Steel Ltd.' },
  { symbol: 'JTEKTINDIA.NS', companyName: 'JTEKT India Ltd.' },
  { symbol: 'JTLIND.NS', companyName: 'JTL Industries Ltd.' },
  { symbol: 'JUBLFOOD.NS', companyName: 'Jubilant FoodWorks Ltd.' },
  { symbol: 'JUBLINDS.NS', companyName: 'Jubilant Industries Ltd.' },
  { symbol: 'JUBLINGREA.NS', companyName: 'Jubilant Ingrevia Ltd.' },
  { symbol: 'JUBLPHARMA.NS', companyName: 'Jubilant Pharmova Ltd.' },
  { symbol: 'JUSTDIAL.NS', companyName: 'Just Dial Ltd.' },
  { symbol: 'JWL.NS', companyName: 'Jupiter Wagons Ltd.' },
  { symbol: 'JYOTHYLAB.NS', companyName: 'Jyothy Labs Ltd.' },
  { symbol: 'JYOTI.NS', companyName: 'Jyoti Ltd.' },
  { symbol: 'JYOTISTRUC.NS', companyName: 'Jyoti Structures Ltd.' },

  // --- K ---
  { symbol: 'KABRAEXTRU.NS', companyName: 'Kabra Extrusiontechnik Ltd.' },
  { symbol: 'KAJARIACER.NS', companyName: 'Kajaria Ceramics Ltd.' },
  {
    symbol: 'KAKATCEM.NS',
    companyName: 'Kakatiya Cement Sugar & Industries Ltd.',
  },
  { symbol: 'KALAMANDIR.NS', companyName: 'Sai Silks (Kalamandir) Ltd.' },
  {
    symbol: 'KALPATPOWR.NS',
    companyName: 'Kalpataru Projects International Ltd.',
  },
  { symbol: 'KALYANI.NS', companyName: 'Kalyani Commercials Ltd.' }, // Check
  { symbol: 'KALYANIFRG.NS', companyName: 'Kalyani Forge Ltd.' },
  { symbol: 'KALYANKJIL.NS', companyName: 'Kalyan Jewellers India Ltd.' },
  { symbol: 'KAMATHOTEL.NS', companyName: 'Kamat Hotels (India) Ltd.' },
  { symbol: 'KAMDHENU.NS', companyName: 'Kamdhenu Ltd.' },
  { symbol: 'KANANIIND.NS', companyName: 'Kanani Industries Ltd.' },
  {
    symbol: 'KANORICHEM.NS',
    companyName: 'Kanoria Chemicals & Industries Ltd.',
  },
  { symbol: 'KANPRPLA.NS', companyName: 'Kanpur Plastipack Ltd.' },
  { symbol: 'KANSAINER.NS', companyName: 'Kansai Nerolac Paints Ltd.' },
  { symbol: 'KAPSTON.NS', companyName: 'Kapston Services Ltd.' },
  { symbol: 'KARDA.NS', companyName: 'Karda Constructions Ltd.' },
  { symbol: 'KARMAENG.NS', companyName: 'Karma Energy Ltd.' },
  { symbol: 'KARURVYSYA.NS', companyName: 'The Karur Vysya Bank Ltd.' },
  {
    symbol: 'KAUSHALYA.NS',
    companyName: 'Kaushalya Infrastructure Development Corporation Ltd.',
  },
  { symbol: 'KAVVERITEL.NS', companyName: 'Kavveri Telecom Products Ltd.' },
  { symbol: 'KAYA.NS', companyName: 'Kaya Ltd.' },
  { symbol: 'KAYNES.NS', companyName: 'Kaynes Technology India Ltd.' },
  { symbol: 'KBCGLOBAL.NS', companyName: 'KBC Global Ltd.' },
  { symbol: 'KCP.NS', companyName: 'KCP Ltd.' },
  {
    symbol: 'KCPSUGIND.NS',
    companyName: 'KCP Sugar and Industries Corporation Ltd.',
  },
  { symbol: 'KDDL.NS', companyName: 'KDDL Ltd.' },
  { symbol: 'KEC.NS', companyName: 'KEC International Ltd.' },
  { symbol: 'KECL.NS', companyName: 'Kirloskar Electric Company Ltd.' },
  { symbol: 'KEI.NS', companyName: 'KEI Industries Ltd.' },
  { symbol: 'KELLTONTEC.NS', companyName: 'Kellton Tech Solutions Ltd.' },
  { symbol: 'KENNAMET.NS', companyName: 'Kennametal India Ltd.' },
  { symbol: 'KERNEX.NS', companyName: 'Kernex Microsystems (India) Ltd.' },
  { symbol: 'KESORAMIND.NS', companyName: 'Kesoram Industries Ltd.' },
  { symbol: 'KEYNOTE.NS', companyName: 'Keynote Financial Services Ltd.' },
  { symbol: 'KFINTECH.NS', companyName: 'KFin Technologies Ltd.' },
  { symbol: 'KHADIM.NS', companyName: 'Khadim India Ltd.' },
  {
    symbol: 'KHAICHEM.NS',
    companyName: 'Khaitan Chemicals & Fertilizers Ltd.',
  },
  { symbol: 'KHANDSE.NS', companyName: 'Khandwala Securities Ltd.' },
  { symbol: 'KICL.NS', companyName: 'Kalyani Investment Company Ltd.' },
  { symbol: 'KILITCH.NS', companyName: 'Kilitch Drugs (India) Ltd.' },
  {
    symbol: 'KIMS.NS',
    companyName: 'Krishna Institute of Medical Sciences Ltd.',
  },
  {
    symbol: 'KINGFA.NS',
    companyName: 'Kingfa Science & Technology (India) Ltd.',
  },
  { symbol: 'KIOCL.NS', companyName: 'KIOCL Ltd.' },
  { symbol: 'KIRIINDUS.NS', companyName: 'Kiri Industries Ltd.' },
  { symbol: 'KIRLFER.NS', companyName: 'Kirloskar Ferrous Industries Ltd.' },
  { symbol: 'KIRLOSBROS.NS', companyName: 'Kirloskar Brothers Ltd.' },
  { symbol: 'KIRLOSENG.NS', companyName: 'Kirloskar Oil Engines Ltd.' },
  { symbol: 'KIRLOSIND.NS', companyName: 'Kirloskar Industries Ltd.' },
  { symbol: 'KIRLPNU.NS', companyName: 'Kirloskar Pneumatic Company Ltd.' },
  { symbol: 'KITEX.NS', companyName: 'Kitex Garments Ltd.' },
  { symbol: 'KKCL.NS', companyName: 'Kewal Kiran Clothing Ltd.' },
  { symbol: 'KMSUGAR.NS', companyName: 'K.M. Sugar Mills Ltd.' },
  { symbol: 'KNRCON.NS', companyName: 'KNR Constructions Ltd.' },
  { symbol: 'KOKUYOCML.NS', companyName: 'Kokuyo Camlin Ltd.' },
  { symbol: 'KOLTEPATIL.NS', companyName: 'Kolte-Patil Developers Ltd.' },
  { symbol: 'KOPRAN.NS', companyName: 'Kopran Ltd.' },
  { symbol: 'KOTAKBANK.NS', companyName: 'Kotak Mahindra Bank Ltd.' },
  { symbol: 'KOTARISUG.NS', companyName: 'Kothari Sugars and Chemicals Ltd.' },
  { symbol: 'KOTHARIPET.NS', companyName: 'Kothari Petrochemicals Ltd.' },
  { symbol: 'KOTHARIPRO.NS', companyName: 'Kothari Products Ltd.' },
  { symbol: 'KPIGREEN.NS', companyName: 'KPI Green Energy Ltd.' },
  { symbol: 'KPIL.NS', companyName: 'Kalpataru Projects International Ltd.' },
  { symbol: 'KPITTECH.NS', companyName: 'KPIT Technologies Ltd.' },
  { symbol: 'KPRMILL.NS', companyName: 'K.P.R. Mill Ltd.' },
  { symbol: 'KRBL.NS', companyName: 'KRBL Ltd.' },
  {
    symbol: 'KREBSBIO.NS',
    companyName: 'Krebs Biochemicals & Industries Ltd.',
  },
  { symbol: 'KRIDHANINF.NS', companyName: 'Kridhan Infra Ltd.' },
  { symbol: 'KRISHANA.NS', companyName: 'Krishana Phoschem Ltd.' },
  { symbol: 'KRITI.NS', companyName: 'Kriti Industries (India) Ltd.' },
  { symbol: 'KRITINUT.NS', companyName: 'Kriti Nutrients Ltd.' },
  { symbol: 'KRSNAA.NS', companyName: 'Krsnaa Diagnostics Ltd.' },
  { symbol: 'KSB.NS', companyName: 'KSB Ltd.' },
  { symbol: 'KSCL.NS', companyName: 'Kaveri Seed Company Ltd.' },
  { symbol: 'KSL.NS', companyName: 'Kalyani Steels Ltd.' },
  { symbol: 'KSOLVES.NS', companyName: 'Ksolves India Ltd.' },
  { symbol: 'KTKBANK.NS', companyName: 'Karnataka Bank Ltd.' },
  { symbol: 'KUANTUM.NS', companyName: 'Kuantum Papers Ltd.' },

  // --- L ---
  { symbol: 'L&TFH.NS', companyName: 'L&T Finance Holdings Ltd.' },
  { symbol: 'LAKPRE.NS', companyName: 'Lakshmi Precision Screws Ltd.' },
  { symbol: 'LALPATHLAB.NS', companyName: 'Dr. Lal PathLabs Ltd.' },
  { symbol: 'LAMBODHARA.NS', companyName: 'Lambodhara Textiles Ltd.' },
  { symbol: 'LAOPALA.NS', companyName: 'La Opala RG Ltd.' },
  { symbol: 'LASA.NS', companyName: 'Lasa Supergenerics Ltd.' },
  { symbol: 'LATENTVIEW.NS', companyName: 'Latent View Analytics Ltd.' },
  { symbol: 'LAURUSLABS.NS', companyName: 'Laurus Labs Ltd.' },
  { symbol: 'LAXMICOT.NS', companyName: 'Laxmi Cotspin Ltd.' },
  { symbol: 'LAXMIMACH.NS', companyName: 'Lakshmi Machine Works Ltd.' },
  { symbol: 'LCCINFOTEC.NS', companyName: 'LCC Infotech Ltd.' },
  { symbol: 'LEMONTREE.NS', companyName: 'Lemon Tree Hotels Ltd.' },
  {
    symbol: 'LFIC.NS',
    companyName: 'Lakshmi Finance & Industrial Corporation Ltd.',
  },
  { symbol: 'LGBBROSLTD.NS', companyName: 'L.G. Balakrishnan & Bros Ltd.' },
  { symbol: 'LGBFORGE.NS', companyName: 'LGB Forge Ltd.' },
  { symbol: 'LIBAS.NS', companyName: 'Libas Consumer Products Ltd.' },
  { symbol: 'LIBERTSHOE.NS', companyName: 'Liberty Shoes Ltd.' },
  { symbol: 'LICHSGFIN.NS', companyName: 'LIC Housing Finance Ltd.' },
  { symbol: 'LICI.NS', companyName: 'Life Insurance Corporation of India' },
  { symbol: 'LIKHITHA.NS', companyName: 'Likhitha Infrastructure Ltd.' },
  { symbol: 'LILAMODE.NS', companyName: 'Lila Mode' }, // Check
  { symbol: 'LINCOLN.NS', companyName: 'Lincoln Pharmaceuticals Ltd.' },
  { symbol: 'LINDEINDIA.NS', companyName: 'Linde India Ltd.' },
  { symbol: 'LLOYDSME.NS', companyName: 'Lloyds Metals and Energy Ltd.' },
  { symbol: 'LLOYDSSTEP.NS', companyName: 'Lloyds Steels Industries Ltd.' },
  { symbol: 'LODHA.NS', companyName: 'Macrotech Developers Ltd.' },
  { symbol: 'LOKESHMACH.NS', companyName: 'Lokesh Machines Ltd.' },
  {
    symbol: 'LOTUSEYE.NS',
    companyName: 'Lotus Eye Hospital and Institute Ltd.',
  },
  { symbol: 'LOVABLE.NS', companyName: 'Lovable Lingerie Ltd.' },
  {
    symbol: 'LPDC.NS',
    companyName: 'Landmark Property Development Company Ltd.',
  },
  { symbol: 'LSIL.NS', companyName: 'Lloyds Steels Industries Ltd.' },
  { symbol: 'LT.NS', companyName: 'Larsen & Toubro Ltd.' },
  { symbol: 'LTF.NS', companyName: 'L&T Finance Ltd.' },
  { symbol: 'LTFOODS.NS', companyName: 'LT Foods Ltd.' },
  { symbol: 'LTI.NS', companyName: 'LTIMindtree Ltd.' },
  { symbol: 'LTIM.NS', companyName: 'LTIMindtree Ltd.' },
  { symbol: 'LTTS.NS', companyName: 'L&T Technology Services Ltd.' },
  { symbol: 'LUMAXIND.NS', companyName: 'Lumax Industries Ltd.' },
  { symbol: 'LUMAXTECH.NS', companyName: 'Lumax Auto Technologies Ltd.' },
  { symbol: 'LUPIN.NS', companyName: 'Lupin Ltd.' },
  { symbol: 'LUXIND.NS', companyName: 'Lux Industries Ltd.' },
  { symbol: 'LXCHEM.NS', companyName: 'Laxmi Organic Industries Ltd.' },
  { symbol: 'LYKALABS.NS', companyName: 'Lyka Labs Ltd.' },
  { symbol: 'LYPSAGEMS.NS', companyName: 'Lypsa Gems & Jewellery Ltd.' },

  // --- M ---
  { symbol: 'M&M.NS', companyName: 'Mahindra & Mahindra Ltd.' },
  {
    symbol: 'M&MFIN.NS',
    companyName: 'Mahindra & Mahindra Financial Services Ltd.',
  },
  { symbol: 'MAANALU.NS', companyName: 'Maan Aluminium Ltd.' },
  { symbol: 'MACPOWER.NS', companyName: 'Macpower CNC Machines Ltd.' },
  { symbol: 'MADHAV.NS', companyName: 'Madhav Marbles & Granites Ltd.' },
  { symbol: 'MADHUCON.NS', companyName: 'Madhucon Projects Ltd.' },
  { symbol: 'MADRASFERT.NS', companyName: 'Madras Fertilizers Ltd.' },
  { symbol: 'MAGADSUGAR.NS', companyName: 'Magadh Sugar & Energy Ltd.' },
  { symbol: 'MAGNUM.NS', companyName: 'Magnum Ventures Ltd.' },
  { symbol: 'MAHABANK.NS', companyName: 'Bank of Maharashtra' },
  {
    symbol: 'MAHAPEXLTD.NS',
    companyName: 'Maha Rashtra Apex Corporation Ltd.',
  },
  { symbol: 'MAHASTEEL.NS', companyName: 'Mahamaya Steel Industries Ltd.' },
  { symbol: 'MAHEPC.NS', companyName: 'Mahindra EPC Irrigation Ltd.' },
  { symbol: 'MAHESHWARI.NS', companyName: 'Maheshwari Logistics Ltd.' },
  { symbol: 'MAHINDCIE.NS', companyName: 'Mahindra CIE Automotive Ltd.' },
  { symbol: 'MAHLIFE.NS', companyName: 'Mahindra Lifespace Developers Ltd.' },
  { symbol: 'MAHLOG.NS', companyName: 'Mahindra Logistics Ltd.' },
  { symbol: 'MAHSEAMLES.NS', companyName: 'Maharashtra Seamless Ltd.' },
  { symbol: 'MAITHANALL.NS', companyName: 'Maithan Alloys Ltd.' },
  { symbol: 'MAJESCO.NS', companyName: 'Majesco Ltd.' },
  { symbol: 'MALUPAPER.NS', companyName: 'Malu Paper Mills Ltd.' },
  { symbol: 'MANAKALU.NS', companyName: 'Manaksia Aluminium Company Ltd.' },
  {
    symbol: 'MANAKCOAT.NS',
    companyName: 'Manaksia Coated Metals & Industries Ltd.',
  },
  { symbol: 'MANAKSTEEL.NS', companyName: 'Manaksia Steels Ltd.' },
  { symbol: 'MANALIPETC.NS', companyName: 'Manali Petrochemicals Ltd.' },
  { symbol: 'MANAPPURAM.NS', companyName: 'Manappuram Finance Ltd.' },
  { symbol: 'MANGALAM.NS', companyName: 'Mangalam Cement Ltd.' },
  {
    symbol: 'MANGCHEFER.NS',
    companyName: 'Mangalore Chemicals & Fertilizers Ltd.',
  },
  { symbol: 'MANGLMCEM.NS', companyName: 'Mangalam Cement Ltd.' },
  { symbol: 'MANGTIMBER.NS', companyName: 'Mangalam Timber Products Ltd.' },
  { symbol: 'MANINDS.NS', companyName: 'Man Industries (India) Ltd.' },
  { symbol: 'MANINFRA.NS', companyName: 'Man Infraconstruction Ltd.' },
  { symbol: 'MANKIND.NS', companyName: 'Mankind Pharma Ltd.' },
  { symbol: 'MANORG.NS', companyName: 'Mangalam Organics Ltd.' },
  { symbol: 'MANUGRAPH.NS', companyName: 'Manugraph India Ltd.' },
  { symbol: 'MANYAVAR.NS', companyName: 'Vedant Fashions Ltd.' },
  { symbol: 'MARATHON.NS', companyName: 'Marathon Nextgen Realty Ltd.' },
  { symbol: 'MARICO.NS', companyName: 'Marico Ltd.' },
  { symbol: 'MARKSANS.NS', companyName: 'Marksans Pharma Ltd.' },
  { symbol: 'MARSHALL.NS', companyName: 'Marshall Machines Ltd.' },
  { symbol: 'MARUTI.NS', companyName: 'Maruti Suzuki India Ltd.' },
  { symbol: 'MASFIN.NS', companyName: 'MAS Financial Services Ltd.' },
  { symbol: 'MASKINVEST.NS', companyName: 'Mask Investments Ltd.' },
  { symbol: 'MASTEK.NS', companyName: 'Mastek Ltd.' },
  { symbol: 'MATRIMONY.NS', companyName: 'Matrimony.com Ltd.' },
  { symbol: 'MAWANASUG.NS', companyName: 'Mawana Sugars Ltd.' },
  { symbol: 'MAXHEALTH.NS', companyName: 'Max Healthcare Institute Ltd.' },
  { symbol: 'MAXIND.NS', companyName: 'Max India Ltd.' },
  { symbol: 'MAXVIL.NS', companyName: 'Max Ventures and Industries Ltd.' },
  { symbol: 'MAYURUNIQ.NS', companyName: 'Mayur Uniquoters Ltd.' },
  { symbol: 'MAZDA.NS', companyName: 'Mazda Ltd.' },
  { symbol: 'MAZDOCK.NS', companyName: 'Mazagon Dock Shipbuilders Ltd.' },
  { symbol: 'MBAPL.NS', companyName: 'Madhya Bharat Agro Products Ltd.' },
  {
    symbol: 'MBECL.NS',
    companyName: 'McNally Bharat Engineering Company Ltd.',
  },
  { symbol: 'MBLINFRA.NS', companyName: 'MBL Infrastructures Ltd.' },
  { symbol: 'MCDOWELL-N.NS', companyName: 'United Spirits Ltd.' },
  { symbol: 'MCL.NS', companyName: 'Madhav Copper Ltd.' },
  { symbol: 'MCLEODRUSS.NS', companyName: 'McLeod Russel India Ltd.' },
  { symbol: 'MCX.NS', companyName: 'Multi Commodity Exchange of India Ltd.' },
  { symbol: 'MEDANTA.NS', companyName: 'Global Health Ltd.' },
  { symbol: 'MEDICAME.NS', companyName: 'Medicamen Biotech Ltd.' },
  { symbol: 'MEDICO.NS', companyName: 'Medico Remedies Ltd.' },
  { symbol: 'MEDPLUS.NS', companyName: 'Medplus Health Services Ltd.' },
  { symbol: 'MEGASOFT.NS', companyName: 'Megasoft Ltd.' },
  { symbol: 'MEGH.NS', companyName: 'Meghmani Organics Ltd.' },
  {
    symbol: 'MELSTAR.NS',
    companyName: 'Melstar Information Technologies Ltd.',
  },
  { symbol: 'MENONBE.NS', companyName: 'Menon Bearings Ltd.' },
  { symbol: 'MENONPIST.NS', companyName: 'Menon Pistons Ltd.' },
  { symbol: 'MERCK.NS', companyName: 'Procter & Gamble Health Ltd.' },
  { symbol: 'METALFORGE.NS', companyName: 'Metalyst Forgings Ltd.' },
  { symbol: 'METROBRAND.NS', companyName: 'Metro Brands Ltd.' },
  { symbol: 'METROPOLIS.NS', companyName: 'Metropolis Healthcare Ltd.' },
  { symbol: 'MFL.NS', companyName: 'Madras Fertilizers Ltd.' },
  { symbol: 'MFSL.NS', companyName: 'Max Financial Services Ltd.' },
  { symbol: 'MGEL.NS', companyName: 'Mangalam Global Enterprise Ltd.' },
  { symbol: 'MGL.NS', companyName: 'Mahanagar Gas Ltd.' },
  { symbol: 'MHRIL.NS', companyName: 'Mahindra Holidays & Resorts India Ltd.' },
  { symbol: 'MIDHANI.NS', companyName: 'Mishra Dhatu Nigam Ltd.' },
  { symbol: 'MINDACORP.NS', companyName: 'Minda Corporation Ltd.' },
  { symbol: 'MINDTECK.NS', companyName: 'Mindteck (India) Ltd.' },
  { symbol: 'MIRZAINT.NS', companyName: 'Mirza International Ltd.' },
  { symbol: 'MITTAL.NS', companyName: 'Mittal Life Style Ltd.' },
  { symbol: 'MMFL.NS', companyName: 'M M Forgings Ltd.' },
  { symbol: 'MMP.NS', companyName: 'MMP Industries Ltd.' },
  { symbol: 'MMTC.NS', companyName: 'MMTC Ltd.' },
  { symbol: 'MODIRUBBER.NS', companyName: 'Modi Rubber Ltd.' },
  { symbol: 'MODISONMET.NS', companyName: 'Modison Metals Ltd.' },
  { symbol: 'MOHITIND.NS', companyName: 'Mohit Industries Ltd.' },
  { symbol: 'MOIL.NS', companyName: 'MOIL Ltd.' },
  { symbol: 'MOLDTEK.NS', companyName: 'Mold-Tek Technologies Ltd.' },
  { symbol: 'MOLDTKPAC.NS', companyName: 'Mold-Tek Packaging Ltd.' },
  { symbol: 'MONARCH.NS', companyName: 'Monarch Networth Capital Ltd.' },
  { symbol: 'MONTECARLO.NS', companyName: 'Monte Carlo Fashions Ltd.' },
  { symbol: 'MORARJEE.NS', companyName: 'Morarjee Textiles Ltd.' },
  { symbol: 'MOREPENLAB.NS', companyName: 'Morepen Laboratories Ltd.' },
  {
    symbol: 'MOTHERSON.NS',
    companyName: 'Samvardhana Motherson International Ltd.',
  },
  {
    symbol: 'MOTILALOFS.NS',
    companyName: 'Motilal Oswal Financial Services Ltd.',
  },
  { symbol: 'MOTISONS.NS', companyName: 'Motisons Jewellers Ltd.' },
  { symbol: 'MOIL.NS', companyName: 'MOIL Ltd.' },
  { symbol: 'MPHASIS.NS', companyName: 'Mphasis Ltd.' },
  { symbol: 'MPSLTD.NS', companyName: 'MPS Ltd.' },
  { symbol: 'MRF.NS', companyName: 'MRF Ltd.' },
  { symbol: 'MRO-TEK.NS', companyName: 'MRO-TEK Realty Ltd.' },
  {
    symbol: 'MRPL.NS',
    companyName: 'Mangalore Refinery and Petrochemicals Ltd.',
  },
  { symbol: 'MSPL.NS', companyName: 'MSP Steel & Power Ltd.' },
  { symbol: 'MSRINDIA.NS', companyName: 'MSR India Ltd.' },
  { symbol: 'MSTCLTD.NS', companyName: 'MSTC Ltd.' },
  { symbol: 'MTARTECH.NS', companyName: 'MTAR Technologies Ltd.' },
  { symbol: 'MTEDUCARE.NS', companyName: 'MT Educare Ltd.' },
  { symbol: 'MTNL.NS', companyName: 'Mahanagar Telephone Nigam Ltd.' },
  { symbol: 'MUKANDLTD.NS', companyName: 'Mukand Ltd.' },
  { symbol: 'MUKTAARTS.NS', companyName: 'Mukta Arts Ltd.' },
  { symbol: 'MUNJALAU.NS', companyName: 'Munjal Auto Industries Ltd.' },
  { symbol: 'MUNJALSHOW.NS', companyName: 'Munjal Showa Ltd.' },
  { symbol: 'MURUDCERA.NS', companyName: 'Murudeshwar Ceramics Ltd.' },
  { symbol: 'MUTHOOTCAP.NS', companyName: 'Muthoot Capital Services Ltd.' },
  { symbol: 'MUTHOOTFIN.NS', companyName: 'Muthoot Finance Ltd.' },
  { symbol: 'MUTHOOTMF.NS', companyName: 'Muthoot Microfin Ltd.' },
  { symbol: 'MXL.NS', companyName: 'Max India Ltd.' },
  { symbol: 'MYSOREPET.NS', companyName: 'Mysore Petro Chemicals Ltd.' },
];
