export const MICRO_STOCKS_3 = [
  // --- N ---
  { symbol: 'NACLIND.NS', companyName: 'NACL Industries Ltd.' },
  {
    symbol: 'NAGAFERT.NS',
    companyName: 'Nagarjuna Fertilizers and Chemicals Ltd.',
  },
  { symbol: 'NAGREEKEXP.NS', companyName: 'Nagreeka Exports Ltd.' },
  {
    symbol: 'NAHARCAP.NS',
    companyName: 'Nahar Capital and Financial Services Ltd.',
  },
  { symbol: 'NAHARINDUS.NS', companyName: 'Nahar Industrial Enterprises Ltd.' },
  { symbol: 'NAHARPOLY.NS', companyName: 'Nahar Poly Films Ltd.' },
  { symbol: 'NAHARSPING.NS', companyName: 'Nahar Spinning Mills Ltd.' },
  {
    symbol: 'NAM-INDIA.NS',
    companyName: 'Nippon Life India Asset Management Ltd.',
  },
  { symbol: 'NANDDANIM.NS', companyName: 'Nandan Denim Ltd.' },
  { symbol: 'NATCOPHARM.NS', companyName: 'Natco Pharma Ltd.' },
  { symbol: 'NATHBIOGEN.NS', companyName: 'Nath Bio-Genes (India) Ltd.' },
  { symbol: 'NATIONALUM.NS', companyName: 'National Aluminium Company Ltd.' },
  { symbol: 'NAUKRI.NS', companyName: 'Info Edge (India) Ltd.' },
  { symbol: 'NAVA.NS', companyName: 'Nava Ltd.' },
  { symbol: 'NAVINFLUOR.NS', companyName: 'Navin Fluorine International Ltd.' },
  { symbol: 'NAVKARCORP.NS', companyName: 'Navkar Corporation Ltd.' },
  { symbol: 'NAVNETEDUL.NS', companyName: 'Navneet Education Ltd.' },
  { symbol: 'NBCC.NS', companyName: 'NBCC (India) Ltd.' },
  { symbol: 'NBVENTURES.NS', companyName: 'Nava Bharat Ventures' }, // Renamed to NAVA
  { symbol: 'NCC.NS', companyName: 'NCC Ltd.' },
  { symbol: 'NCLIND.NS', companyName: 'NCL Industries Ltd.' },
  { symbol: 'NDL.NS', companyName: 'Nandan Denim Ltd' }, // Check
  { symbol: 'NDRAUTO.NS', companyName: 'Narendra Properties Ltd.' }, // Check symbol
  { symbol: 'NDTV.NS', companyName: 'New Delhi Television Ltd.' },
  {
    symbol: 'NECCLTD.NS',
    companyName: 'North Eastern Carrying Corporation Ltd.',
  },
  { symbol: 'NECLIFE.NS', companyName: 'Nectar Lifesciences Ltd.' },
  { symbol: 'NELCAST.NS', companyName: 'Nelcast Ltd.' },
  { symbol: 'NELCO.NS', companyName: 'Nelco Ltd.' },
  { symbol: 'NEOGEN.NS', companyName: 'Neogen Chemicals Ltd.' },
  { symbol: 'NESCO.NS', companyName: 'Nesco Ltd.' },
  { symbol: 'NESTLEIND.NS', companyName: 'Nestle India Ltd.' },
  { symbol: 'NETWORK18.NS', companyName: 'Network18 Media & Investments Ltd.' },
  { symbol: 'NEULANDLAB.NS', companyName: 'Neuland Laboratories Ltd.' },
  { symbol: 'NEWGEN.NS', companyName: 'Newgen Software Technologies Ltd.' },
  { symbol: 'NEXTMEDIA.NS', companyName: 'Next Mediaworks Ltd.' },
  { symbol: 'NFL.NS', companyName: 'National Fertilizers Ltd.' },
  { symbol: 'NH.NS', companyName: 'Narayana Hrudayalaya Ltd.' },
  { symbol: 'NHPC.NS', companyName: 'NHPC Ltd.' },
  { symbol: 'NIACL.NS', companyName: 'The New India Assurance Company Ltd.' },
  { symbol: 'NIBE.NS', companyName: 'Nibe Ltd.' },
  { symbol: 'NIITLTD.NS', companyName: 'NIIT Ltd.' },
  { symbol: 'LTIM.NS', companyName: 'LTIMindtree' }, // Check
  { symbol: 'NILKAMAL.NS', companyName: 'Nilkamal Ltd.' },
  { symbol: 'NIPPOBATRY.NS', companyName: 'Indo-National Ltd.' },
  { symbol: 'NIRAJ.NS', companyName: 'Niraj Cement Structurals Ltd.' },
  { symbol: 'NITCO.NS', companyName: 'Nitco Ltd.' },
  { symbol: 'NITINSPIN.NS', companyName: 'Nitin Spinners Ltd.' },
  { symbol: 'NKIND.NS', companyName: 'NK Industries Ltd.' },
  { symbol: 'NLCINDIA.NS', companyName: 'NLC India Ltd.' },
  { symbol: 'NMDC.NS', companyName: 'NMDC Ltd.' },
  { symbol: 'NOCIL.NS', companyName: 'NOCIL Ltd.' },
  { symbol: 'NOIDATOLL.NS', companyName: 'Noida Toll Bridge Company Ltd.' },
  { symbol: 'NORBTEAEXP.NS', companyName: 'Norben Tea & Exports Ltd.' },
  { symbol: 'NOVARTIND.NS', companyName: 'Novartis India Ltd.' },
  { symbol: 'NRAIL.NS', companyName: 'N R Agarwal Industries Ltd.' },
  { symbol: 'NRBBEARING.NS', companyName: 'NRB Bearings Ltd.' },
  { symbol: 'NSIL.NS', companyName: 'Nalwa Sons Investments Ltd.' },
  { symbol: 'NTPC.NS', companyName: 'NTPC Ltd.' },
  { symbol: 'NUCLEUS.NS', companyName: 'Nucleus Software Exports Ltd.' },
  { symbol: 'NURECA.NS', companyName: 'Nureca Ltd.' },
  { symbol: 'NXTDIGITAL.NS', companyName: 'NXTDIGITAL Ltd.' },
  { symbol: 'NYKAA.NS', companyName: 'FSN E-Commerce Ventures Ltd.' },

  // --- O ---
  { symbol: 'OBEROIRLTY.NS', companyName: 'Oberoi Realty Ltd.' },
  { symbol: 'OCCL.NS', companyName: 'Oriental Carbon & Chemicals Ltd.' },
  { symbol: 'OFSS.NS', companyName: 'Oracle Financial Services Software Ltd.' },
  { symbol: 'OIL.NS', companyName: 'Oil India Ltd.' },
  { symbol: 'OLECTRA.NS', companyName: 'Olectra Greentech Ltd.' },
  { symbol: 'OMAXAUTO.NS', companyName: 'Omax Autos Ltd.' },
  { symbol: 'OMAXE.NS', companyName: 'Omaxe Ltd.' },
  { symbol: 'OMINFRAL.NS', companyName: 'Om Infra Ltd.' },
  { symbol: 'OMKAR.NS', companyName: 'Omkar Speciality Chemicals Ltd.' },
  { symbol: 'ONELIFECAP.NS', companyName: 'Onelife Capital Advisors Ltd.' },
  { symbol: 'ONEPOINT.NS', companyName: 'One Point One Solutions Ltd.' },
  { symbol: 'ONGC.NS', companyName: 'Oil & Natural Gas Corporation Ltd.' },
  { symbol: 'ONMOBILE.NS', companyName: 'OnMobile Global Ltd.' },
  { symbol: 'ONWARDTEC.NS', companyName: 'Onward Technologies Ltd.' },
  { symbol: 'OPTIEMUS.NS', companyName: 'Optiemus Infracom Ltd.' },
  { symbol: 'ORBTEXP.NS', companyName: 'Orbit Exports Ltd.' },
  { symbol: 'ORCHPHARMA.NS', companyName: 'Orchid Pharma Ltd.' },
  { symbol: 'ORICONENT.NS', companyName: 'Oricon Enterprises Ltd.' },
  { symbol: 'ORIENTABRA.NS', companyName: 'Orient Abrasives Ltd.' },
  { symbol: 'ORIENTALTL.NS', companyName: 'Oriental Aromatics Ltd.' },
  { symbol: 'ORIENTBELL.NS', companyName: 'Orient Bell Ltd.' },
  { symbol: 'ORIENTCEM.NS', companyName: 'Orient Cement Ltd.' },
  { symbol: 'ORIENTELEC.NS', companyName: 'Orient Electric Ltd.' },
  { symbol: 'ORIENTHOT.NS', companyName: 'Oriental Hotels Ltd.' },
  { symbol: 'ORIENTLTD.NS', companyName: 'Orient Press Ltd.' },
  { symbol: 'ORIENTPPR.NS', companyName: 'Orient Paper & Industries Ltd.' },
  {
    symbol: 'ORISSAMINE.NS',
    companyName: 'The Orissa Minerals Development Company Ltd.',
  },
  { symbol: 'ORTINLAB.NS', companyName: 'Ortin Laboratories Ltd.' },
  { symbol: 'OSWALAGRO.NS', companyName: 'Oswal Agro Mills Ltd.' },
  {
    symbol: 'OSWALSEEDS.NS',
    companyName: 'ShreeOswal Seeds And Chemicals Ltd.',
  },

  // --- P ---
  { symbol: 'PAGEIND.NS', companyName: 'Page Industries Ltd.' },
  { symbol: 'PAISALO.NS', companyName: 'Paisalo Digital Ltd.' },
  { symbol: 'PALASHSECU.NS', companyName: 'Palash Securities Ltd.' },
  { symbol: 'PALREDTEC.NS', companyName: 'Palred Technologies Ltd.' },
  { symbol: 'PANACEABIO.NS', companyName: 'Panacea Biotec Ltd.' },
  { symbol: 'PANAMAPET.NS', companyName: 'Panama Petrochem Ltd.' },
  { symbol: 'PARACABLES.NS', companyName: 'Paramount Communications Ltd.' },
  { symbol: 'PARAGMILK.NS', companyName: 'Parag Milk Foods Ltd.' },
  {
    symbol: 'PARAS.NS',
    companyName: 'Paras Defence and Space Technologies Ltd.',
  },
  { symbol: 'PARASPETRO.NS', companyName: 'Paras Petrofils Ltd.' },
  { symbol: 'PARSVNATH.NS', companyName: 'Parsvnath Developers Ltd.' },
  { symbol: 'PASUPTAC.NS', companyName: 'Pasupati Acrylon Ltd.' },
  { symbol: 'PATELENG.NS', companyName: 'Patel Engineering Ltd.' },
  { symbol: 'PATINTLOG.NS', companyName: 'Patel Integrated Logistics Ltd.' },
  { symbol: 'PATYAM.NS', companyName: 'Patyam' }, // Check
  { symbol: 'PCJEWELLER.NS', companyName: 'PC Jeweller Ltd.' },
  { symbol: 'PCL.NS', companyName: 'Panyam Cements & Mineral Industries Ltd.' }, // Check stock status
  { symbol: 'PDMJEPAPER.NS', companyName: 'Pudumjee Paper Products Ltd.' },
  { symbol: 'PDSMFL.NS', companyName: 'PDS Ltd.' },
  { symbol: 'PEARLPOLY.NS', companyName: 'Pearl Polymers Ltd.' },
  { symbol: 'PEL.NS', companyName: 'Piramal Enterprises Ltd.' },
  { symbol: 'PENIND.NS', companyName: 'Pennar Industries Ltd.' },
  { symbol: 'PENINLAND.NS', companyName: 'Peninsula Land Ltd.' },
  { symbol: 'PERSISTENT.NS', companyName: 'Persistent Systems Ltd.' },
  { symbol: 'PETRONET.NS', companyName: 'Petronet LNG Ltd.' },
  { symbol: 'PFC.NS', companyName: 'Power Finance Corporation Ltd.' },
  { symbol: 'PFIZER.NS', companyName: 'Pfizer Ltd.' },
  { symbol: 'PFOCUS.NS', companyName: 'Prime Focus Ltd.' },
  { symbol: 'PFS.NS', companyName: 'PTC India Financial Services Ltd.' },
  { symbol: 'PGEL.NS', companyName: 'PG Electroplast Ltd.' },
  {
    symbol: 'PGHH.NS',
    companyName: 'Procter & Gamble Hygiene and Health Care Ltd.',
  },
  { symbol: 'PGHL.NS', companyName: 'Procter & Gamble Health Ltd.' },
  { symbol: 'PGIL.NS', companyName: 'Pearl Global Industries Ltd.' },
  { symbol: 'PHILIPCARB.NS', companyName: 'Phillips Carbon Black Ltd.' },
  { symbol: 'PHOENIXLTD.NS', companyName: 'The Phoenix Mills Ltd.' },
  { symbol: 'PIDILITIND.NS', companyName: 'Pidilite Industries Ltd.' },
  { symbol: 'PIIND.NS', companyName: 'PI Industries Ltd.' },
  {
    symbol: 'PILANIINVS.NS',
    companyName: 'Pilani Investment and Industries Corporation Ltd.',
  },
  { symbol: 'PILITA.NS', companyName: 'Pil It' }, // Check
  { symbol: 'PIONEEREMB.NS', companyName: 'Pioneer Embroideries Ltd.' },
  { symbol: 'PITTIENG.NS', companyName: 'Pitti Engineering Ltd.' },
  { symbol: 'PIXTRANS.NS', companyName: 'Pix Transmissions Ltd.' },
  { symbol: 'PLASTIBLEN.NS', companyName: 'Plastiblends India Ltd.' },
  { symbol: 'PNB.NS', companyName: 'Punjab National Bank' },
  { symbol: 'PNBGILTS.NS', companyName: 'PNB Gilts Ltd.' },
  { symbol: 'PNBHOUSING.NS', companyName: 'PNB Housing Finance Ltd.' },
  { symbol: 'PNCINFRA.NS', companyName: 'PNC Infratech Ltd.' },
  { symbol: 'PODDARMENT.NS', companyName: 'Poddar Pigments Ltd.' },
  { symbol: 'POKARNA.NS', companyName: 'Pokarna Ltd.' },
  { symbol: 'POLICYBZR.NS', companyName: 'PB Fintech Ltd.' },
  { symbol: 'POLYCAB.NS', companyName: 'Polycab India Ltd.' },
  { symbol: 'POLYMED.NS', companyName: 'Poly Medicure Ltd.' },
  { symbol: 'POLYPLEX.NS', companyName: 'Polyplex Corporation Ltd.' },
  { symbol: 'PONNIERODE.NS', companyName: 'Ponni Sugars (Erode) Ltd.' },
  { symbol: 'POONAWALLA.NS', companyName: 'Poonawalla Fincorp Ltd.' },
  {
    symbol: 'POWERGRID.NS',
    companyName: 'Power Grid Corporation of India Ltd.',
  },
  { symbol: 'POWERINDIA.NS', companyName: 'Hitachi Energy India Ltd.' },
  { symbol: 'POWERMECH.NS', companyName: 'Power Mech Projects Ltd.' },
  { symbol: 'PPAP.NS', companyName: 'PPAP Automotive Ltd.' },
  { symbol: 'PPL.NS', companyName: 'Prakash Pipes Ltd.' },
  { symbol: 'PPLPHARMA.NS', companyName: 'Piramal Pharma Ltd.' },
  { symbol: 'PRAENG.NS', companyName: 'Praj Industries Ltd.' },
  { symbol: 'PRAJIND.NS', companyName: 'Praj Industries Ltd.' },
  { symbol: 'PRAKASH.NS', companyName: 'Prakash Industries Ltd.' },
  { symbol: 'PRAKASHSTL.NS', companyName: 'Prakash Steelage Ltd.' },
  { symbol: 'PRAXIS.NS', companyName: 'Praxis Home Retail Ltd.' },
  { symbol: 'PRECAM.NS', companyName: 'Precision Camshafts Ltd.' },
  { symbol: 'PRECOT.NS', companyName: 'Precot Ltd.' },
  { symbol: 'PRECWIRE.NS', companyName: 'Precision Wires India Ltd.' },
  { symbol: 'PREMEXPLQ.NS', companyName: 'Premier Explosives Ltd.' },
  { symbol: 'PREMIER.NS', companyName: 'Premier Ltd.' },
  { symbol: 'PREMIERPOL.NS', companyName: 'Premier Polyfilm Ltd.' },
  { symbol: 'PRESSMN.NS', companyName: 'Pressman Advertising Ltd.' },
  { symbol: 'PRESTIGE.NS', companyName: 'Prestige Estates Projects Ltd.' },
  { symbol: 'PRICOLLTD.NS', companyName: 'Pricol Ltd.' },
  { symbol: 'PRIMESECU.NS', companyName: 'Prime Securities Ltd.' },
  { symbol: 'PRINCEPIPE.NS', companyName: 'Prince Pipes and Fittings Ltd.' },
  { symbol: 'PRITIKAUTO.NS', companyName: 'Pritika Auto Industries Ltd.' },
  { symbol: 'PRIVISCL.NS', companyName: 'Privi Speciality Chemicals Ltd.' },
  { symbol: 'PROZONINT.NS', companyName: 'Prozone Integ Properties Ltd.' },
  {
    symbol: 'PRUDENT.NS',
    companyName: 'Prudent Corporate Advisory Services Ltd.',
  },
  { symbol: 'PSB.NS', companyName: 'Punjab & Sind Bank' },
  { symbol: 'PSPPROJECT.NS', companyName: 'PSP Projects Ltd.' },
  { symbol: 'PTC.NS', companyName: 'PTC India Ltd.' },
  { symbol: 'PTCIL.NS', companyName: 'PTC Industries Ltd.' },
  { symbol: 'PTL.NS', companyName: 'PTL Enterprises Ltd.' },
  {
    symbol: 'PUNJABCHEM.NS',
    companyName: 'Punjab Chemicals & Crop Protection Ltd.',
  },
  { symbol: 'PUNJLLOYD.NS', companyName: 'Punj Lloyd Ltd.' },
  { symbol: 'PURVA.NS', companyName: 'Puravankara Ltd.' },
  { symbol: 'PVRINOX.NS', companyName: 'PVR INOX Ltd.' },

  // --- Q ---
  { symbol: 'QUICKHEAL.NS', companyName: 'Quick Heal Technologies Ltd.' },
  { symbol: 'QUESS.NS', companyName: 'Quess Corp Ltd.' },
  { symbol: 'QUICKHEAL.NS', companyName: 'Quick Heal' }, // dup

  // --- R ---
  { symbol: 'RBL.NS', companyName: 'Rane Brake Lining Ltd.' },
  { symbol: 'RBLBANK.NS', companyName: 'RBL Bank Ltd.' },
  { symbol: 'RCF.NS', companyName: 'Rashtriya Chemicals & Fertilizers Ltd.' },
  { symbol: 'RCOM.NS', companyName: 'Reliance Communications Ltd.' },
  { symbol: 'RECLTD.NS', companyName: 'REC Ltd.' },
  { symbol: 'REDINGTON.NS', companyName: 'Redington Ltd.' },
  { symbol: 'REFEX.NS', companyName: 'Refex Industries Ltd.' },
  { symbol: 'REGENCERAM.NS', companyName: 'Regency Ceramics Ltd.' },
  { symbol: 'RELAXO.NS', companyName: 'Relaxo Footwears Ltd.' },
  { symbol: 'RELIANCE.NS', companyName: 'Reliance Industries Ltd.' },
  { symbol: 'RELIGARE.NS', companyName: 'Religare Enterprises Ltd.' },
  { symbol: 'RELINFRA.NS', companyName: 'Reliance Infrastructure Ltd.' },
  { symbol: 'REMSONSIND.NS', companyName: 'Remsons Industries Ltd.' },
  { symbol: 'RENUKA.NS', companyName: 'Shree Renuka Sugars Ltd.' },
  { symbol: 'REPCOHOME.NS', companyName: 'Repco Home Finance Ltd.' },
  { symbol: 'REPL.NS', companyName: 'Rudrabhishek Enterprises Ltd.' },
  { symbol: 'REPRO.NS', companyName: 'Repro India Ltd.' },
  { symbol: 'RESPONIND.NS', companyName: 'Responsive Industries Ltd.' },
  { symbol: 'REVATHI.NS', companyName: 'Revathi Equipment Ltd.' },
  { symbol: 'RGL.NS', companyName: 'Renaissance Global Ltd.' },
  { symbol: 'RHIM.NS', companyName: 'RHI Magnesita India Ltd.' },
  { symbol: 'RICOAUTO.NS', companyName: 'Rico Auto Industries Ltd.' },
  { symbol: 'RIIL.NS', companyName: 'Reliance Industrial Infrastructure Ltd.' },
  { symbol: 'RITES.NS', companyName: 'RITES Ltd.' },
  { symbol: 'RKDL.NS', companyName: 'Ravi Kumar Distilleries Ltd.' },
  { symbol: 'RKEC.NS', companyName: 'RKEC Projects Ltd.' },
  { symbol: 'RKFORGE.NS', companyName: 'Ramkrishna Forgings Ltd.' },
  { symbol: 'RMCL.NS', companyName: 'Radha Madhav Corporation Ltd.' },
  { symbol: 'RML.NS', companyName: 'Rane (Madras) Ltd.' },
  { symbol: 'ROHL.NS', companyName: 'Royal Orchid Hotels Ltd.' },
  { symbol: 'ROLEXRINGS.NS', companyName: 'Rolex Rings Ltd.' },
  { symbol: 'ROLLT.NS', companyName: 'Rollatainers Ltd.' },
  { symbol: 'ROSSARI.NS', companyName: 'Rossari Biotech Ltd.' },
  { symbol: 'ROSSELLIND.NS', companyName: 'Rossell India Ltd.' },
  { symbol: 'ROUTE.NS', companyName: 'Route Mobile Ltd.' },
  { symbol: 'RPGLIFE.NS', companyName: 'RPG Life Sciences Ltd.' },
  { symbol: 'RPOWER.NS', companyName: 'Reliance Power Ltd.' },
  { symbol: 'RPPINFRA.NS', companyName: 'RPP Infra Projects Ltd.' },
  { symbol: 'RSSOFTWARE.NS', companyName: 'R. S. Software (India) Ltd.' },
  { symbol: 'RSWM.NS', companyName: 'RSWM Ltd.' },
  { symbol: 'RSYSTEMS.NS', companyName: 'R Systems International Ltd.' },
  { symbol: 'RTNINDIA.NS', companyName: 'RattanIndia Enterprises Ltd.' },
  { symbol: 'RTNPOWER.NS', companyName: 'RattanIndia Power Ltd.' },
  { symbol: 'RUBYMILLS.NS', companyName: 'The Ruby Mills Ltd.' },
  { symbol: 'RUCHINFRA.NS', companyName: 'Ruchi Infrastructure Ltd.' },
  { symbol: 'RUCHIRA.NS', companyName: 'Ruchira Papers Ltd.' },
  { symbol: 'RUPA.NS', companyName: 'Rupa & Company Ltd.' },
  { symbol: 'RUSHIL.NS', companyName: 'Rushil Decor Ltd.' },
  { symbol: 'RVHL.NS', companyName: 'Ravindra Energy Ltd.' },
  { symbol: 'RVNL.NS', companyName: 'Rail Vikas Nigam Ltd.' },
  { symbol: 'RWS.NS', companyName: 'RWS' }, // Check

  // --- S ---
  { symbol: 'S&SPOWER.NS', companyName: 'S&S Power Switchgear Ltd.' },
  {
    symbol: 'SABEVENTS.NS',
    companyName: 'Sab Events & Governance Now Media Ltd.',
  },
  { symbol: 'SADBHAV.NS', companyName: 'Sadbhav Engineering Ltd.' },
  { symbol: 'SADBHIN.NS', companyName: 'Sadbhav Infrastructure Project Ltd.' },
  { symbol: 'SAFARI.NS', companyName: 'Safari Industries (India) Ltd.' },
  { symbol: 'SAGARDEEP.NS', companyName: 'Sagardeep Alloys Ltd.' },
  { symbol: 'SAGCEM.NS', companyName: 'Sagar Cements Ltd.' },
  { symbol: 'SAIL.NS', companyName: 'Steel Authority of India Ltd.' },
  { symbol: 'SAKAR.NS', companyName: 'Sakar Healthcare Ltd.' },
  { symbol: 'SAKHTISUG.NS', companyName: 'Sakthi Sugars Ltd.' },
  { symbol: 'SAKSOFT.NS', companyName: 'Saksoft Ltd.' },
  { symbol: 'SAKUMA.NS', companyName: 'Sakuma Exports Ltd.' },
  { symbol: 'SALASAR.NS', companyName: 'Salasar Techno Engineering Ltd.' },
  { symbol: 'SALONA.NS', companyName: 'Salona Cotspin Ltd.' },
  { symbol: 'SALSTEEL.NS', companyName: 'SAL Steel Ltd.' },
  { symbol: 'SALZERELEC.NS', companyName: 'Salzer Electronics Ltd.' },
  { symbol: 'SAMBHAAV.NS', companyName: 'Sambhaav Media Ltd.' },
  { symbol: 'SANDESH.NS', companyName: 'The Sandesh Ltd.' },
  { symbol: 'SANDHAR.NS', companyName: 'Sandhar Technologies Ltd.' },
  { symbol: 'SANGAMIND.NS', companyName: 'Sangam (India) Ltd.' },
  { symbol: 'SANGHIIND.NS', companyName: 'Sanghi Industries Ltd.' },
  { symbol: 'SANGHVIMOV.NS', companyName: 'Sanghvi Movers Ltd.' },
  { symbol: 'SANGINITA.NS', companyName: 'Sanginita Chemicals Ltd.' },
  { symbol: 'SANOFI.NS', companyName: 'Sanofi India Ltd.' },
  { symbol: 'SANWARIA.NS', companyName: 'Sanwaria Consumer Ltd.' },
  { symbol: 'SARDAEN.NS', companyName: 'Sarda Energy & Minerals Ltd.' },
  { symbol: 'SAREGAMA.NS', companyName: 'Saregama India Ltd.' },
  { symbol: 'SARLAPOLY.NS', companyName: 'Sarla Performance Fibers Ltd.' },
  { symbol: 'SASKEN.NS', companyName: 'Sasken Technologies Ltd.' },
  { symbol: 'SASTASUNDR.NS', companyName: 'Sastasundar Ventures Ltd.' },
  { symbol: 'SATIA.NS', companyName: 'Satia Industries Ltd.' },
  { symbol: 'SATIN.NS', companyName: 'Satin Creditcare Network Ltd.' },
  { symbol: 'SATINDLTD.NS', companyName: 'Sat Industries Ltd.' },
  { symbol: 'SBC.NS', companyName: 'SBC Exports Ltd.' },
  { symbol: 'SBCL.NS', companyName: 'Shivalik Bimetal Controls Ltd.' },
  { symbol: 'SBICARD.NS', companyName: 'SBI Cards and Payment Services Ltd.' },
  { symbol: 'SBILIFE.NS', companyName: 'SBI Life Insurance Company Ltd.' },
  { symbol: 'SBIN.NS', companyName: 'State Bank of India' },
  { symbol: 'SCAPDVR.NS', companyName: 'Stampede Capital Ltd. (DVR)' },
  { symbol: 'SCHAEFFLER.NS', companyName: 'Schaeffler India Ltd.' },
  { symbol: 'SCHAND.NS', companyName: 'S Chand And Company Ltd.' },
  {
    symbol: 'SCHNEIDER.NS',
    companyName: 'Schneider Electric Infrastructure Ltd.',
  },
  { symbol: 'SCI.NS', companyName: 'Shipping Corporation of India Ltd.' },
  { symbol: 'SDBL.NS', companyName: 'Som Distilleries & Breweries Ltd.' },
  { symbol: 'SEAMECLTD.NS', companyName: 'Seamec Ltd.' },
  { symbol: 'SECURCRED.NS', companyName: 'SecUR Credentials Ltd.' },
  { symbol: 'SECURKLOUD.NS', companyName: 'SecureKloud Technologies Ltd.' },
  { symbol: 'SEJALLTD.NS', companyName: 'Sejal Glass Ltd.' },
  {
    symbol: 'SEKSARIA.NS',
    companyName: 'Ishwarshakti Holdings & Traders Ltd.',
  }, // Check
  { symbol: 'SELAN.NS', companyName: 'Selan Exploration Technology Ltd.' },
  { symbol: 'SEYAIND.NS', companyName: 'Seya Industries Ltd.' },
  { symbol: 'SFL.NS', companyName: 'Sheela Foam Ltd.' },
  { symbol: 'SGIL.NS', companyName: 'Synergy Green Industries Ltd.' },
  { symbol: 'SGL.NS', companyName: 'STL Global Ltd.' },
  { symbol: 'SHALPAINTS.NS', companyName: 'Shalimar Paints Ltd.' },
  { symbol: 'SHANKARA.NS', companyName: 'Shankara Building Products Ltd.' },
  { symbol: 'SHANTIGEAR.NS', companyName: 'Shanthi Gears Ltd.' },
  { symbol: 'SHARDACROP.NS', companyName: 'Sharda Cropchem Ltd.' },
  { symbol: 'SHARDAMOTR.NS', companyName: 'Sharda Motor Industries Ltd.' },
  { symbol: 'SHAREINDIA.NS', companyName: 'Share India Securities Ltd.' },
  { symbol: 'SHEMAROO.NS', companyName: 'Shemaroo Entertainment Ltd.' },
  { symbol: 'SHILPAMED.NS', companyName: 'Shilpa Medicare Ltd.' },
  { symbol: 'SHIVALIK.NS', companyName: 'Shivalik Rasayan Ltd.' },
  { symbol: 'SHIVAMAUTO.NS', companyName: 'Shivam Autotech Ltd.' },
  { symbol: 'SHIVATEX.NS', companyName: 'Shiva Texyarn Ltd.' },
  { symbol: 'SHK.NS', companyName: 'S H Kelkar and Company Ltd.' },
  { symbol: 'SHOPERSTOP.NS', companyName: 'Shoppers Stop Ltd.' },
  { symbol: 'SHRADHA.NS', companyName: 'Shradha Infraprojects Ltd.' },
  { symbol: 'SHREDIGCEM.NS', companyName: 'Shree Digvijay Cement Co. Ltd.' },
  { symbol: 'SHREECEM.NS', companyName: 'Shree Cement Ltd.' },
  {
    symbol: 'SHREEPUSHK.NS',
    companyName: 'Shree Pushkar Chemicals & Fertilisers Ltd.',
  },
  { symbol: 'SHREERAMA.NS', companyName: 'Shree Rama Multi-Tech Ltd.' },
  { symbol: 'SHRENIK.NS', companyName: 'Shrenik Ltd.' },
  { symbol: 'SHREYANIND.NS', companyName: 'Shreyans Industries Ltd.' },
  { symbol: 'SHREYAS.NS', companyName: 'Shreyas Shipping & Logistics Ltd.' },
  { symbol: 'SHRIPISTON.NS', companyName: 'Shriram Pistons & Rings Ltd.' },
  { symbol: 'SHRIRAMFIN.NS', companyName: 'Shriram Finance Ltd.' },
  { symbol: 'SHYAMCENT.NS', companyName: 'Shyam Century Ferrous Ltd.' },
  { symbol: 'SHYAMMETL.NS', companyName: 'Shyam Metalics and Energy Ltd.' },
  { symbol: 'SIEMENS.NS', companyName: 'Siemens Ltd.' },
  { symbol: 'SIGACHI.NS', companyName: 'Sigachi Industries Ltd.' },
  { symbol: 'SIGIND.NS', companyName: 'Signet Industries Ltd.' },
  { symbol: 'SIKKO.NS', companyName: 'Sikko Industries Ltd.' },
  { symbol: 'SIL.NS', companyName: 'Standard Industries Ltd.' },
  { symbol: 'SILINV.NS', companyName: 'SIL Investments Ltd.' },
  { symbol: 'SILLYMONKS.NS', companyName: 'Silly Monks Entertainment Ltd.' },
  { symbol: 'SIMBHALS.NS', companyName: 'Simbhaoli Sugars Ltd.' },
  { symbol: 'SIMPLEXINF.NS', companyName: 'Simplex Infrastructures Ltd.' },
  { symbol: 'SINTERCOM.NS', companyName: 'Sintercom India Ltd.' },
  { symbol: 'SIRCA.NS', companyName: 'Sirca Paints India Ltd.' },
  { symbol: 'SIS.NS', companyName: 'SIS Ltd.' },
  { symbol: 'SIVIK.NS', companyName: 'Sivik' }, // check
  { symbol: 'SJVN.NS', companyName: 'SJVN Ltd.' },
  { symbol: 'SKFINDIA.NS', companyName: 'SKF India Ltd.' },
  { symbol: 'SKIPPER.NS', companyName: 'Skipper Ltd.' },
  {
    symbol: 'SKMEGGPROD.NS',
    companyName: 'SKM Egg Products Export (India) Ltd.',
  },
  { symbol: 'SMARTLINK.NS', companyName: 'Smartlink Holdings Ltd.' },
  { symbol: 'SMLISUZU.NS', companyName: 'SML Isuzu Ltd.' },
  { symbol: 'SMLT.NS', companyName: 'Sarthak Metals Ltd.' },
  { symbol: 'SMSLIFE.NS', companyName: 'SMS Lifesciences India Ltd.' },
  { symbol: 'SMSPHARMA.NS', companyName: 'SMS Pharmaceuticals Ltd.' },
  { symbol: 'SNOWMAN.NS', companyName: 'Snowman Logistics Ltd.' },
  { symbol: 'SOBHA.NS', companyName: 'Sobha Ltd.' },
  { symbol: 'SOFTTECH.NS', companyName: 'Softtech Engineers Ltd.' },
  { symbol: 'SOLARA.NS', companyName: 'Solara Active Pharma Sciences Ltd.' },
  { symbol: 'SOLARINDS.NS', companyName: 'Solar Industries India Ltd.' },
  { symbol: 'SOMANYCERA.NS', companyName: 'Somany Ceramics Ltd.' },
  { symbol: 'SOMATEX.NS', companyName: 'Soma Textiles & Industries Ltd.' },
  { symbol: 'SOMI.NS', companyName: 'Somi Conveyor Beltings Ltd.' },
  { symbol: 'SONACOMS.NS', companyName: 'Sona BLW Precision Forgings Ltd.' },
  { symbol: 'SONAMCLOCK.NS', companyName: 'Sonam Clock Ltd.' },
  { symbol: 'SONATSOFTW.NS', companyName: 'Sonata Software Ltd.' },
  { symbol: 'SOTL.NS', companyName: 'Savita Oil Technologies Ltd.' },
  { symbol: 'SOUTHBANK.NS', companyName: 'The South Indian Bank Ltd.' },
  {
    symbol: 'SOUTHWEST.NS',
    companyName: 'South West Pinnacle Exploration Ltd.',
  },
  { symbol: 'SPAL.NS', companyName: 'S.P. Apparels Ltd.' },
  { symbol: 'SPANDANA.NS', companyName: 'Spandana Sphoorty Financial Ltd.' },
  {
    symbol: 'SPARC.NS',
    companyName: 'Sun Pharma Advanced Research Company Ltd.',
  },
  { symbol: 'SPCENET.NS', companyName: 'Spacenet Enterprises India Ltd.' },
  { symbol: 'SPECIALITY.NS', companyName: 'Speciality Restaurants Ltd.' },
  { symbol: 'SPENCERS.NS', companyName: "Spencer's Retail Ltd." },
  {
    symbol: 'SPIC.NS',
    companyName: 'Southern Petrochemical Industries Corporation Ltd.',
  },
  { symbol: 'SPLIL.NS', companyName: 'SPL Industries Ltd.' },
  { symbol: 'SPMLINFRA.NS', companyName: 'SPML Infra Ltd.' },
  { symbol: 'SPORTKING.NS', companyName: 'Sportking India Ltd.' },
  { symbol: 'SREEL.NS', companyName: 'Sreeleathers Ltd.' },
  { symbol: 'SRF.NS', companyName: 'SRF Ltd.' },
  {
    symbol: 'SRHHYPOLTD.NS',
    companyName: 'Sree Rayalaseema Hi-Strength Hypo Ltd.',
  },
  { symbol: 'SRIPIPES.NS', companyName: 'Srikalahasthi Pipes Ltd.' },
  { symbol: 'SRPL.NS', companyName: 'Shree Ram Proteins Ltd.' },
  { symbol: 'SSWL.NS', companyName: 'Steel Strips Wheels Ltd.' },
  { symbol: 'STAR.NS', companyName: 'Strides Pharma Science Ltd.' },
  { symbol: 'STARCEMENT.NS', companyName: 'Star Cement Ltd.' },
  {
    symbol: 'STARHEALTH.NS',
    companyName: 'Star Health and Allied Insurance Company Ltd.',
  },
  { symbol: 'STARPAPER.NS', companyName: 'Star Paper Mills Ltd.' },
  { symbol: 'STARTECK.NS', companyName: 'Starteck Finance Ltd.' },
  {
    symbol: 'STCINDIA.NS',
    companyName: 'The State Trading Corporation of India Ltd.',
  },
  { symbol: 'STEELCAS.NS', companyName: 'Steelcast Ltd.' },
  { symbol: 'STEELCITY.NS', companyName: 'Steel City Securities Ltd.' },
  { symbol: 'STEELXIND.NS', companyName: 'Steel Exchange India Ltd.' },
  { symbol: 'STEL.NS', companyName: 'Stel Holdings Ltd.' },
  { symbol: 'STERTOOLS.NS', companyName: 'Sterling Tools Ltd.' },
  { symbol: 'STLTECH.NS', companyName: 'Sterlite Technologies Ltd.' },
  { symbol: 'STOVEKRAFT.NS', companyName: 'Stove Kraft Ltd.' },
  { symbol: 'STYLAMIND.NS', companyName: 'Stylam Industries Ltd.' },
  { symbol: 'STYRENIX.NS', companyName: 'Styrenix Performance Materials Ltd.' },
  { symbol: 'SUBEXLTD.NS', companyName: 'Subex Ltd.' },
  { symbol: 'SUBROS.NS', companyName: 'Subros Ltd.' },
  {
    symbol: 'SUDARSCHEM.NS',
    companyName: 'Sudarshan Chemical Industries Ltd.',
  },
  { symbol: 'SULA.NS', companyName: 'Sula Vineyards Ltd.' },
  { symbol: 'SUMICHEM.NS', companyName: 'Sumitomo Chemical India Ltd.' },
  { symbol: 'SUMIT.NS', companyName: 'Sumit Woods Ltd.' },
  { symbol: 'SUMMITSEC.NS', companyName: 'Summit Securities Ltd.' },
  { symbol: 'SUNCLAYLTD.NS', companyName: 'Sundaram-Clayton Ltd.' },
  { symbol: 'SUNDARMHLD.NS', companyName: 'Sundaram Brake Linings Ltd.' },
  { symbol: 'SUNDARMFIN.NS', companyName: 'Sundaram Finance Ltd.' },
  { symbol: 'SUNDRMBRAK.NS', companyName: 'Sundaram Brake Linings Ltd.' },
  { symbol: 'SUNDRMFAST.NS', companyName: 'Sundram Fasteners Ltd.' },
  { symbol: 'SUNFLAG.NS', companyName: 'Sunflag Iron and Steel Company Ltd.' },
  { symbol: 'SUNPHARMA.NS', companyName: 'Sun Pharmaceutical Industries Ltd.' },
  { symbol: 'SUNTECK.NS', companyName: 'Sunteck Realty Ltd.' },
  { symbol: 'SUNTV.NS', companyName: 'Sun TV Network Ltd.' },
  { symbol: 'SUPERHOUSE.NS', companyName: 'Superhouse Ltd.' },
  { symbol: 'SUPERSPIN.NS', companyName: 'Super Spinning Mills Ltd.' },
  { symbol: 'SUPRAJIT.NS', companyName: 'Suprajit Engineering Ltd.' },
  { symbol: 'SUPREMEENG.NS', companyName: 'Supreme Engineering Ltd.' },
  { symbol: 'SUPREMEIND.NS', companyName: 'Supreme Industries Ltd.' },
  { symbol: 'SUPREMEINF.NS', companyName: 'Supreme Infrastructure India Ltd.' },
  { symbol: 'SURANASOL.NS', companyName: 'Surana Solar Ltd.' },
  { symbol: 'SURANAT&P.NS', companyName: 'Surana Telecom and Power Ltd.' },
  { symbol: 'SURYALAXMI.NS', companyName: 'Suryalakshmi Cotton Mills Ltd.' },
  { symbol: 'SURYAROSNI.NS', companyName: 'Surya Roshni Ltd.' },
  { symbol: 'SURYODAY.NS', companyName: 'Suryoday Small Finance Bank Ltd.' },
  {
    symbol: 'SUTLEJTEX.NS',
    companyName: 'Sutlej Textiles and Industries Ltd.',
  },
  { symbol: 'SUVEN.NS', companyName: 'Suven Life Sciences Ltd.' },
  { symbol: 'SUVENPHAR.NS', companyName: 'Suven Pharmaceuticals Ltd.' },
  { symbol: 'SUVIDHAA.NS', companyName: 'Suvidhaa Infoserve Ltd.' },
  { symbol: 'SUZLON.NS', companyName: 'Suzlon Energy Ltd.' },
  { symbol: 'SVPGLOB.NS', companyName: 'SVP Global Textiles Ltd.' },
  { symbol: 'SWANENERGY.NS', companyName: 'Swan Energy Ltd.' },
  { symbol: 'SWARAJENG.NS', companyName: 'Swaraj Engines Ltd.' },
  { symbol: 'SWELECTES.NS', companyName: 'Swelect Energy Systems Ltd.' },
  {
    symbol: 'SWSOLAR.NS',
    companyName: 'Sterling and Wilson Renewable Energy Ltd.',
  },
  { symbol: 'SYMPHONY.NS', companyName: 'Symphony Ltd.' },
  { symbol: 'SYNCOMF.NS', companyName: 'Syncom Formulations (India) Ltd.' },
  { symbol: 'SYNGENE.NS', companyName: 'Syngene International Ltd.' },
  { symbol: 'SYRMA.NS', companyName: 'Syrma SGS Technology Ltd.' },

  // --- T ---
  {
    symbol: 'TAINWALCHM.NS',
    companyName: 'Tainwala Chemicals and Plastics (India) Ltd.',
  },
  { symbol: 'TAJGVK.NS', companyName: 'Taj GVK Hotels & Resorts Ltd.' },
  { symbol: 'TAKE.NS', companyName: 'Take Solutions Ltd.' },
  {
    symbol: 'TALBROAUTO.NS',
    companyName: 'Talbros Automotive Components Ltd.',
  },
  { symbol: 'TANFACIND.NS', companyName: 'Tanfac Industries Ltd.' },
  { symbol: 'TANLA.NS', companyName: 'Tanla Platforms Ltd.' },
  { symbol: 'TANTIACONS.NS', companyName: 'Tantia Constructions Ltd.' },
  { symbol: 'TARMAT.NS', companyName: 'Tarmat Ltd.' },
  { symbol: 'TARSONS.NS', companyName: 'Tarsons Products Ltd.' },
  { symbol: 'TASTYBITE.NS', companyName: 'Tasty Bite Eatables Ltd.' },
  { symbol: 'TATACHEM.NS', companyName: 'Tata Chemicals Ltd.' },
  { symbol: 'TATACOFFEE.NS', companyName: 'Tata Coffee Ltd.' },
  { symbol: 'TATACOMM.NS', companyName: 'Tata Communications Ltd.' },
  { symbol: 'TATACONSUM.NS', companyName: 'Tata Consumer Products Ltd.' },
  { symbol: 'TATAELXSI.NS', companyName: 'Tata Elxsi Ltd.' },
  { symbol: 'TATAINVEST.NS', companyName: 'Tata Investment Corporation Ltd.' },
  { symbol: 'TATAMETALI.NS', companyName: 'Tata Metaliks Ltd.' },
  { symbol: 'TATAMOTORS.NS', companyName: 'Tata Motors Ltd.' },
  { symbol: 'TATAPOWER.NS', companyName: 'Tata Power Company Ltd.' },
  { symbol: 'TATASTEEL.NS', companyName: 'Tata Steel Ltd.' },
  { symbol: 'TATATECH.NS', companyName: 'Tata Technologies Ltd.' },
  { symbol: 'TATACHEM.NS', companyName: 'Tata Chemicals Ltd.' },
  { symbol: 'TATVA.NS', companyName: 'Tatva Chintan Pharma Chem Ltd.' },
  { symbol: 'TBZ.NS', companyName: 'Tribhovandas Bhimji Zaveri Ltd.' },
  { symbol: 'TCI.NS', companyName: 'Transport Corporation of India Ltd.' },
  { symbol: 'TCIEXP.NS', companyName: 'TCI Express Ltd.' },
  { symbol: 'TCNSBRANDS.NS', companyName: 'TCNS Clothing Co. Ltd.' },
  { symbol: 'TCPLPACK.NS', companyName: 'TCPL Packaging Ltd.' },
  { symbol: 'TCS.NS', companyName: 'Tata Consultancy Services Ltd.' },
  { symbol: 'TDPOWERSYS.NS', companyName: 'TD Power Systems Ltd.' },
  { symbol: 'TEAMLEASE.NS', companyName: 'TeamLease Services Ltd.' },
  { symbol: 'TECHIN.NS', companyName: 'Techindia Nirman Ltd.' },
  { symbol: 'TECHM.NS', companyName: 'Tech Mahindra Ltd.' },
  {
    symbol: 'TECHNOE.NS',
    companyName: 'Techno Electric & Engineering Company Ltd.',
  },
  { symbol: 'TEGA.NS', companyName: 'Tega Industries Ltd.' },
  { symbol: 'TEJASNET.NS', companyName: 'Tejas Networks Ltd.' },
  { symbol: 'TEMBO.NS', companyName: 'Tembo Global Industries Ltd.' },
  { symbol: 'TERASOFT.NS', companyName: 'Tera Software Ltd.' },
  {
    symbol: 'TEXINFRA.NS',
    companyName: 'Texmaco Infrastructure & Holdings Ltd.',
  },
  { symbol: 'TEXMOPIPES.NS', companyName: 'Texmo Pipes and Products Ltd.' },
  { symbol: 'TEXRAIL.NS', companyName: 'Texmaco Rail & Engineering Ltd.' },
  {
    symbol: 'TFCILTD.NS',
    companyName: 'Tourism Finance Corporation of India Ltd.',
  },
  { symbol: 'TFL.NS', companyName: 'Transwarranty Finance Ltd.' },
  { symbol: 'TGBHOTELS.NS', companyName: 'TGB Banquets and Hotels Ltd.' },
  { symbol: 'THANGAMAYL.NS', companyName: 'Thangamayil Jewellery Ltd.' },
  { symbol: 'THEINVEST.NS', companyName: 'The Investment Trust of India Ltd.' },
  { symbol: 'THEMISMED.NS', companyName: 'Themis Medicare Ltd.' },
  { symbol: 'THERMAX.NS', companyName: 'Thermax Ltd.' },
  { symbol: 'THIRUMALAI.NS', companyName: 'Thirumalai Chemicals Ltd.' },
  { symbol: 'THOMASCOOK.NS', companyName: 'Thomas Cook (India) Ltd.' },
  { symbol: 'THYROCARE.NS', companyName: 'Thyrocare Technologies Ltd.' },
  { symbol: 'TI.NS', companyName: 'Tilaknagar Industries Ltd.' },
  { symbol: 'TIDEWATER.NS', companyName: 'Tide Water Oil Co. (India) Ltd.' },
  { symbol: 'TIIL.NS', companyName: 'Technocraft Industries (India) Ltd.' },
  { symbol: 'TIINDIA.NS', companyName: 'Tube Investments of India Ltd.' },
  { symbol: 'TIJARIA.NS', companyName: 'Tijaria Polypipes Ltd.' },
  { symbol: 'TIL.NS', companyName: 'TIL Ltd.' },
  { symbol: 'TIMESGTY.NS', companyName: 'Times Guaranty Ltd.' },
  { symbol: 'TIMETECHNO.NS', companyName: 'Time Technoplast Ltd.' },
  { symbol: 'TIMKEN.NS', companyName: 'Timken India Ltd.' },
  { symbol: 'TINPLATE.NS', companyName: 'The Tinplate Company of India Ltd.' },
  { symbol: 'TIPSINDLTD.NS', companyName: 'Tips Industries Ltd.' },
  { symbol: 'TIRUMALCHM.NS', companyName: 'Thirumalai Chemicals Ltd.' },
  { symbol: 'TIRUPATIFL.NS', companyName: 'Tirupati Forge Ltd.' },
  { symbol: 'TITAN.NS', companyName: 'Titan Company Ltd.' },
  { symbol: 'TITANBIO.NS', companyName: 'Titan Biotech Ltd.' },
  { symbol: 'TMRVL.NS', companyName: 'The Mandhana Retail Ventures Ltd.' },
  { symbol: 'TNPETRO.NS', companyName: 'Tamilnadu Petroproducts Ltd.' },
  { symbol: 'TNPL.NS', companyName: 'Tamil Nadu Newsprint & Papers Ltd.' },
  { symbol: 'TNTELE.NS', companyName: 'Tamilnadu Telecommunication Ltd.' },
  { symbol: 'TOKYOPLAST.NS', companyName: 'Tokyo Plast International Ltd.' },
  { symbol: 'TORNTPHARM.NS', companyName: 'Torrent Pharmaceuticals Ltd.' },
  { symbol: 'TORNTPOWER.NS', companyName: 'Torrent Power Ltd.' },
  { symbol: 'TOTAL.NS', companyName: 'Total Transport Systems Ltd.' },
  { symbol: 'TOUCHWOOD.NS', companyName: 'Touchwood Entertainment Ltd.' },
  { symbol: 'TPLPLASTEH.NS', companyName: 'TPL Plastech Ltd.' },
  {
    symbol: 'TREEHOUSE.NS',
    companyName: 'Tree House Education & Accessories Ltd.',
  },
  { symbol: 'TREJHARA.NS', companyName: 'Trejhara Solutions Ltd.' },
  { symbol: 'TRENT.NS', companyName: 'Trent Ltd.' },
  { symbol: 'TRF.NS', companyName: 'TRF Ltd.' },
  { symbol: 'TRIDENT.NS', companyName: 'Trident Ltd.' },
  { symbol: 'TRIGYN.NS', companyName: 'Trigyn Technologies Ltd.' },
  {
    symbol: 'TRIL.NS',
    companyName: 'Transformers and Rectifiers (India) Ltd.',
  },
  { symbol: 'TRITURBINE.NS', companyName: 'Triveni Turbine Ltd.' },
  {
    symbol: 'TRIVENI.NS',
    companyName: 'Triveni Engineering & Industries Ltd.',
  },
  { symbol: 'TTKHEALTH.NS', companyName: 'TTK Healthcare Ltd.' },
  { symbol: 'TTKPRESTIG.NS', companyName: 'TTK Prestige Ltd.' },
  { symbol: 'TTL.NS', companyName: 'T T Ltd.' },
  { symbol: 'TTML.NS', companyName: 'Tata Teleservices (Maharashtra) Ltd.' },
  { symbol: 'TV18BRDCST.NS', companyName: 'TV18 Broadcast Ltd.' },
  { symbol: 'TVSMOTOR.NS', companyName: 'TVS Motor Company Ltd.' },
  { symbol: 'TVSSRICHAK.NS', companyName: 'TVS Srichakra Ltd.' },
  { symbol: 'TVTODAY.NS', companyName: 'TV Today Network Ltd.' },
  { symbol: 'TVVISION.NS', companyName: 'TV Vision Ltd.' },
  { symbol: 'TWL.NS', companyName: 'Titagarh Wagons' }, // check

  // --- U ---
  { symbol: 'UBL.NS', companyName: 'United Breweries Ltd.' },
  { symbol: 'UCALFUEL.NS', companyName: 'Ucal Fuel Systems Ltd.' },
  { symbol: 'UCOBANK.NS', companyName: 'UCO Bank' },
  { symbol: 'UFLEX.NS', companyName: 'Uflex Ltd.' },
  { symbol: 'UFO.NS', companyName: 'UFO Moviez India Ltd.' },
  { symbol: 'UGARSUGAR.NS', companyName: 'The Ugar Sugar Works Ltd.' },
  { symbol: 'UGROCAP.NS', companyName: 'Ugro Capital Ltd.' },
  { symbol: 'UJAAS.NS', companyName: 'Ujaas Energy Ltd.' },
  { symbol: 'UJJIVAN.NS', companyName: 'Ujjivan Financial Services Ltd.' },
  { symbol: 'UJJIVANSFB.NS', companyName: 'Ujjivan Small Finance Bank Ltd.' },
  { symbol: 'ULTRACEMCO.NS', companyName: 'UltraTech Cement Ltd.' },
  { symbol: 'ULTRAMAR.NS', companyName: 'Ultramarine & Pigments Ltd.' },
  { symbol: 'UMANGDAIRY.NS', companyName: 'Umang Dairies Ltd.' },
  {
    symbol: 'UMESLTD.NS',
    companyName: 'Usha Martin Education & Solutions Ltd.',
  },
  { symbol: 'UNICHEMLAB.NS', companyName: 'Unichem Laboratories Ltd.' },
  { symbol: 'UNIDT.NS', companyName: 'United Drilling Tools Ltd.' },
  { symbol: 'UNIENTER.NS', companyName: 'Uniphos Enterprises Ltd.' },
  { symbol: 'UNIONBANK.NS', companyName: 'Union Bank of India' },
  { symbol: 'UNIPARTS.NS', companyName: 'Uniparts India Ltd.' },
  { symbol: 'UNIPHOS.NS', companyName: 'Uniphos Enterprises Ltd.' },
  { symbol: 'UNITECH.NS', companyName: 'Unitech Ltd.' },
  {
    symbol: 'UNITEDTEA.NS',
    companyName: 'The United Nilgiri Tea Estates Company Ltd.',
  },
  { symbol: 'UNITY.NS', companyName: 'Unity Small Finance Bank Ltd.' },
  { symbol: 'UNIVASTU.NS', companyName: 'Univastu India Ltd.' },
  { symbol: 'UNIVCABLES.NS', companyName: 'Universal Cables Ltd.' },
  { symbol: 'UNIVPHOTO.NS', companyName: 'Universus Photo Imagings Ltd.' },
  { symbol: 'UNOMINDA.NS', companyName: 'Uno Minda Ltd.' },
  { symbol: 'UPL.NS', companyName: 'UPL Ltd.' },
  { symbol: 'URJA.NS', companyName: 'Urja Global Ltd.' },
  { symbol: 'USHAMART.NS', companyName: 'Usha Martin Ltd.' },
  { symbol: 'UTKARSHBNK.NS', companyName: 'Utkarsh Small Finance Bank Ltd.' },
  { symbol: 'UTTAMSUGAR.NS', companyName: 'Uttam Sugar Mills Ltd.' },

  // --- V ---
  { symbol: 'VAIBHAVGBL.NS', companyName: 'Vaibhav Global Ltd.' },
  { symbol: 'VAISHALI.NS', companyName: 'Vaishali Pharma Ltd.' },
  { symbol: 'VAKRANGEE.NS', companyName: 'Vakrangee Ltd.' },
  { symbol: 'VALIANTORG.NS', companyName: 'Valiant Organics Ltd.' },
  { symbol: 'VARDHACRLC.NS', companyName: 'Vardhman Acrylics Ltd.' },
  { symbol: 'VARDHMAN.NS', companyName: 'Vardhman Textiles Ltd.' },
  { symbol: 'VARROC.NS', companyName: 'Varroc Engineering Ltd.' },
  { symbol: 'VASCONEQ.NS', companyName: 'Vascon Engineers Ltd.' },
  { symbol: 'VASWANI.NS', companyName: 'Vaswani Industries Ltd.' },
  { symbol: 'VBL.NS', companyName: 'Varun Beverages Ltd.' },
  { symbol: 'VEDL.NS', companyName: 'Vedanta Ltd.' },
  { symbol: 'VENKEYS.NS', companyName: "Venky's (India) Ltd." },
  { symbol: 'VENUSREM.NS', companyName: 'Venus Remedies Ltd.' },
  { symbol: 'VERANDA.NS', companyName: 'Veranda Learning Solutions Ltd.' },
  { symbol: 'VERTOZ.NS', companyName: 'Vertoz Advertising Ltd.' },
  { symbol: 'VESUVIUS.NS', companyName: 'Vesuvius India Ltd.' },
  { symbol: 'VGUARD.NS', companyName: 'V-Guard Industries Ltd.' },
  { symbol: 'VHL.NS', companyName: 'Vardhman Holdings Ltd.' },
  {
    symbol: 'VIDHIING.NS',
    companyName: 'Vidhi Specialty Food Ingredients Ltd.',
  },
  { symbol: 'VIJAYA.NS', companyName: 'Vijaya Diagnostic Centre Ltd.' },
  { symbol: 'VIKASECO.NS', companyName: 'Vikas EcoTech Ltd.' },
  { symbol: 'VIKASLIFE.NS', companyName: 'Vikas Lifecare Ltd.' },
  { symbol: 'VIKASPROP.NS', companyName: 'Vikas Proppant & Granite Ltd.' },
  { symbol: 'VIKASWSP.NS', companyName: 'Vikas WSP Ltd.' },
  { symbol: 'VIMTALABS.NS', companyName: 'Vimta Labs Ltd.' },
  { symbol: 'VINATIORGA.NS', companyName: 'Vinati Organics Ltd.' },
  { symbol: 'VINDHYATEL.NS', companyName: 'Vindhya Telelinks Ltd.' },
  { symbol: 'VINNY.NS', companyName: 'Vinny Overseas Ltd.' },
  { symbol: 'VINYLINDIA.NS', companyName: 'Vinyl Chemicals (India) Ltd.' },
  { symbol: 'VIPCLOTHNG.NS', companyName: 'VIP Clothing Ltd.' },
  { symbol: 'VIPIND.NS', companyName: 'VIP Industries Ltd.' },
  { symbol: 'VIPULLTD.NS', companyName: 'Vipul Ltd.' },
  { symbol: 'VISAKAIND.NS', companyName: 'Visaka Industries Ltd.' },
  { symbol: 'VISASTEEL.NS', companyName: 'Visa Steel Ltd.' },
  { symbol: 'VISHNU.NS', companyName: 'Vishnu Chemicals Ltd.' },
  { symbol: 'VISHWARAJ.NS', companyName: 'Vishwaraj Sugar Industries Ltd.' },
  { symbol: 'VIVIDHA.NS', companyName: 'Visagar Polytex Ltd.' },
  { symbol: 'VIVIMEDLAB.NS', companyName: 'Vivimed Labs Ltd.' },
  { symbol: 'VLSFINANCE.NS', companyName: 'VLS Finance Ltd.' },
  { symbol: 'VMART.NS', companyName: 'V-Mart Retail Ltd.' },
  { symbol: 'VOLTAMP.NS', companyName: 'Voltamp Transformers Ltd.' },
  { symbol: 'VOLTAS.NS', companyName: 'Voltas Ltd.' },
  { symbol: 'VRLLOG.NS', companyName: 'VRL Logistics Ltd.' },
  { symbol: 'VSSL.NS', companyName: 'Vardhman Special Steels Ltd.' },
  { symbol: 'VSTIND.NS', companyName: 'VST Industries Ltd.' },
  { symbol: 'VSTTILLERS.NS', companyName: 'VST Tillers Tractors Ltd.' },
  { symbol: 'VTL.NS', companyName: 'Vardhman Textiles Ltd.' },

  // --- W ---
  { symbol: 'WABAG.NS', companyName: 'VA Tech Wabag Ltd.' },
  { symbol: 'WALCHANNAG.NS', companyName: 'Walchandnagar Industries Ltd.' },
  { symbol: 'WANBURY.NS', companyName: 'Wanbury Ltd.' },
  { symbol: 'WATERBASE.NS', companyName: 'The Waterbase Ltd.' },
  { symbol: 'WEALTH.NS', companyName: 'Wealth First Portfolio Managers Ltd.' },
  { symbol: 'WEBELSOLAR.NS', companyName: 'Websol Energy System Ltd.' },
  { symbol: 'WEIZMANIND.NS', companyName: 'Weizmann Ltd.' },
  { symbol: 'WELCORP.NS', companyName: 'Welspun Corp Ltd.' },
  { symbol: 'WELENT.NS', companyName: 'Welspun Enterprises Ltd.' },
  {
    symbol: 'WELINV.NS',
    companyName: 'Welspun Investments and Commercials Ltd.',
  },
  { symbol: 'WELSPUNIND.NS', companyName: 'Welspun Living Ltd.' },
  { symbol: 'WELSPUNLIV.NS', companyName: 'Welspun Living Ltd.' },
  { symbol: 'WENDT.NS', companyName: 'Wendt (India) Ltd.' },
  { symbol: 'WESTLIFE.NS', companyName: 'Westlife Foodworld Ltd.' },
  { symbol: 'WEWIN.NS', companyName: 'WE WIN Ltd.' },
  { symbol: 'WHEELS.NS', companyName: 'Wheels India Ltd.' },
  { symbol: 'WHIRLPOOL.NS', companyName: 'Whirlpool of India Ltd.' },
  { symbol: 'WILLAMAGOR.NS', companyName: 'Williamson Magor & Company Ltd.' },
  { symbol: 'WIMPLAST.NS', companyName: 'Wim Plast Ltd.' },
  { symbol: 'WINDLAS.NS', companyName: 'Windlas Biotech Ltd.' },
  { symbol: 'WINDMACHIN.NS', companyName: 'Windsor Machines Ltd.' },
  { symbol: 'WIPRO.NS', companyName: 'Wipro Ltd.' },
  { symbol: 'WOCKPHARMA.NS', companyName: 'Wockhardt Ltd.' },
  { symbol: 'WONDERLA.NS', companyName: 'Wonderla Holidays Ltd.' },
  { symbol: 'WORTH.NS', companyName: 'Worth Peripherals Ltd.' },
  { symbol: 'WSTCSTPAPR.NS', companyName: 'West Coast Paper Mills Ltd.' },

  // --- X ---
  { symbol: 'XCHANGING.NS', companyName: 'Xchanging Solutions Ltd.' },
  { symbol: 'XELPMOC.NS', companyName: 'Xelpmoc Design and Tech Ltd.' },
  { symbol: 'XPROINDIA.NS', companyName: 'Xpro India Ltd.' },

  // --- Y ---
  { symbol: 'YAARI.NS', companyName: 'Yaari Digital Integrated Services Ltd.' },
  { symbol: 'YESBANK.NS', companyName: 'Yes Bank Ltd.' },
  { symbol: 'YUKEN.NS', companyName: 'Yuken India Ltd.' },

  // --- Z ---
  { symbol: 'ZEEL.NS', companyName: 'Zee Entertainment Enterprises Ltd.' },
  { symbol: 'ZEELEARN.NS', companyName: 'Zee Learn Ltd.' },
  { symbol: 'ZEEMEDIA.NS', companyName: 'Zee Media Corporation Ltd.' },
  { symbol: 'ZENITHEXPO.NS', companyName: 'Zenith Exports Ltd.' },
  {
    symbol: 'ZENITHSTL.NS',
    companyName: 'Zenith Steel Pipes & Industries Ltd.',
  },
  { symbol: 'ZENSARTECH.NS', companyName: 'Zensar Technologies Ltd.' },
  { symbol: 'ZENTEC.NS', companyName: 'Zen Technologies Ltd.' },
  {
    symbol: 'ZFCVINDIA.NS',
    companyName: 'ZF Commercial Vehicle Control Systems India Ltd.',
  },
  { symbol: 'ZIMLAB.NS', companyName: 'Zim Laboratories Ltd.' },
  { symbol: 'ZODIAC.NS', companyName: 'Zodiac Clothing Company Ltd.' },
  { symbol: 'ZOTA.NS', companyName: 'Zota Health Care Ltd.' },
  { symbol: 'ZUARI.NS', companyName: 'Zuari Agro Chemicals Ltd.' },
  { symbol: 'ZUARIIND.NS', companyName: 'Zuari Industries Ltd.' },
  { symbol: 'ZYDUSLIFE.NS', companyName: 'Zydus Lifesciences Ltd.' },
  { symbol: 'ZYDUSWELL.NS', companyName: 'Zydus Wellness Ltd.' },
];
