export const MICRO_STOCKS = [
  // --- TEXTILES ---
  { symbol: 'AMBIKCO.NS', companyName: 'Ambika Cotton Mills Ltd.' },
  { symbol: 'BANSWRAS.NS', companyName: 'Banswara Syntex Ltd.' },
  { symbol: 'CONFIPET.NS', companyName: 'Confidence Petroleum' },
  { symbol: 'ELIN.NS', companyName: 'Elin Electronics Ltd.' },
  { symbol: 'GHCL.NS', companyName: 'GHCL Ltd.' },
  { symbol: 'GHCLTEXTIL.NS', companyName: 'GHCL Textiles Ltd.' },
  { symbol: 'GOCLCORP.NS', companyName: 'GOCL Corporation Ltd.' },
  { symbol: 'GREAVESCOT.NS', companyName: 'Greaves Cotton Ltd.' },
  { symbol: 'HIMATSEIDE.NS', companyName: 'Himatsingka Seide Ltd.' },
  { symbol: 'INDORAMA.NS', companyName: 'Indo Rama Synthetics (India) Ltd.' },
  { symbol: 'JINDWORLD.NS', companyName: 'Jindal Worldwide Ltd.' },
  { symbol: 'KITEX.NS', companyName: 'Kitex Garments Ltd.' },
  { symbol: 'LSIL.NS', companyName: 'Lloyds Steels Industries Ltd.' },
  { symbol: 'MONTECARLO.NS', companyName: 'Monte Carlo Fashions Ltd.' },
  { symbol: 'NAHARSPING.NS', companyName: 'Nahar Spinning Mills Ltd.' },
  { symbol: 'NITINSPIN.NS', companyName: 'Nitin Spinners Ltd.' },
  { symbol: 'RSWM.NS', companyName: 'RSWM Ltd.' },
  { symbol: 'RUBYMILLS.NS', companyName: 'The Ruby Mills Ltd.' },
  { symbol: 'SANGAMIND.NS', companyName: 'Sangam (India) Ltd.' },
  { symbol: 'SIYSIL.NS', companyName: 'Siyaram Silk Mills Ltd.' },
  { symbol: 'SPAL.NS', companyName: 'S.P. Apparels Ltd.' },
  {
    symbol: 'SUTLEJTEX.NS',
    companyName: 'Sutlej Textiles and Industries Ltd.',
  },
  { symbol: 'SWANENERGY.NS', companyName: 'Swan Energy Ltd.' },
  { symbol: 'TCNSBRANDS.NS', companyName: 'TCNS Clothing Co. Ltd.' },
  { symbol: 'VARDHACRLC.NS', companyName: 'Vardhman Acrylics Ltd.' },

  // --- SUGAR ---
  { symbol: 'AVADHSUGAR.NS', companyName: 'Avadh Sugar & Energy Ltd.' },
  { symbol: 'BAJAJHIND.NS', companyName: 'Bajaj Hindusthan Sugar Ltd.' },
  { symbol: 'BALRAMCHIN.NS', companyName: 'Balrampur Chini Mills Ltd.' },
  { symbol: 'BANNARI.NS', companyName: 'Bannari Amman Sugars Ltd.' },
  {
    symbol: 'DALMIASUG.NS',
    companyName: 'Dalmia Bharat Sugar and Industries Ltd.',
  },
  { symbol: 'DCM.NS', companyName: 'DCM Ltd.' },
  { symbol: 'DHAMPURSUG.NS', companyName: 'Dhampur Sugar Mills Ltd.' },
  { symbol: 'DWARKESH.NS', companyName: 'Dwarikesh Sugar Industries Ltd.' },
  { symbol: 'EIDPARRY.NS', companyName: 'E.I.D. - Parry (India) Ltd.' },
  { symbol: 'KMSETUP.NS', companyName: 'K.M. Sugar Mills Ltd.' },
  { symbol: 'MAGADSUGAR.NS', companyName: 'Magadh Sugar & Energy Ltd.' },
  { symbol: 'MAWANASUG.NS', companyName: 'Mawana Sugars Ltd.' },
  { symbol: 'PONNIERODE.NS', companyName: 'Ponni Sugars (Erode) Ltd.' },
  { symbol: 'RAJSREESUG.NS', companyName: 'Rajshree Sugars & Chemicals Ltd.' },
  { symbol: 'RENUKA.NS', companyName: 'Shree Renuka Sugars Ltd.' },
  { symbol: 'SAKHTISUG.NS', companyName: 'Sakthi Sugars Ltd.' },
  {
    symbol: 'TRIVENI.NS',
    companyName: 'Triveni Engineering & Industries Ltd.',
  },
  { symbol: 'UGARSUGAR.NS', companyName: 'The Ugar Sugar Works Ltd.' },
  { symbol: 'UTTAMSUGAR.NS', companyName: 'Uttam Sugar Mills Ltd.' },
  { symbol: 'VISHWARAJ.NS', companyName: 'Vishwaraj Sugar Industries Ltd.' },

  // --- PAPER ---
  { symbol: 'ANDHRAPAP.NS', companyName: 'Andhra Paper Ltd.' },
  { symbol: 'BALKRISHNA.NS', companyName: 'Balkrishna Paper Mills Ltd.' },
  { symbol: 'EMAMIPAP.NS', companyName: 'Emami Paper Mills Ltd.' },
  { symbol: 'GENUSPAPER.NS', companyName: 'Genus Paper & Boards Ltd.' },
  { symbol: 'JKPAPER.NS', companyName: 'JK Paper Ltd.' },
  { symbol: 'KUANTUM.NS', companyName: 'Kuantum Papers Ltd.' },
  { symbol: 'MALUPAPER.NS', companyName: 'Malu Paper Mills Ltd.' },
  { symbol: 'NRAIL.NS', companyName: 'N R Agarwal Industries Ltd.' },
  { symbol: 'ORIENTPPR.NS', companyName: 'Orient Paper & Industries Ltd.' },
  { symbol: 'PUDUMJEE.NS', companyName: 'Pudumjee Paper Products Ltd.' },
  { symbol: 'RUCHIRA.NS', companyName: 'Ruchira Papers Ltd.' },
  { symbol: 'SATIA.NS', companyName: 'Satia Industries Ltd.' },
  { symbol: 'SESHAPAPER.NS', companyName: 'Seshasayee Paper and Boards Ltd.' },
  { symbol: 'SHREYAS.NS', companyName: 'Shreyas Shipping & Logistics Ltd.' }, // Check
  { symbol: 'STARPAPER.NS', companyName: 'Star Paper Mills Ltd.' },
  { symbol: 'TNPL.NS', companyName: 'Tamil Nadu Newsprint & Papers Ltd.' },
  { symbol: 'WSTCSTPAPR.NS', companyName: 'West Coast Paper Mills Ltd.' },

  // --- CHEMICALS (SMALL) ---
  { symbol: 'ALUFLUOR.NS', companyName: 'Alufluoride Ltd.' },
  { symbol: 'AROMATICS.NS', companyName: 'Aromatics' }, // check symbol
  { symbol: 'ASAHIINDIA.NS', companyName: 'Asahi India Glass Ltd.' },
  { symbol: 'BHARATRAS.NS', companyName: 'Bharat Rasayan Ltd.' },
  { symbol: 'BODALCHEM.NS', companyName: 'Bodal Chemicals Ltd.' },
  { symbol: 'CAMLINFINE.NS', companyName: 'Camlin Fine Sciences Ltd.' },
  { symbol: 'CHEMCON.NS', companyName: 'Chemcon Speciality Chemicals Ltd.' },
  { symbol: 'CHEMFAB.NS', companyName: 'Chemfab Alkalis Ltd.' },
  { symbol: 'DCW.NS', companyName: 'DCW Ltd.' },
  { symbol: 'DY-CH.NS', companyName: 'Dynemic Products Ltd.' }, // Check
  { symbol: 'EXCELINDUS.NS', companyName: 'Excel Industries Ltd.' },
  { symbol: 'FAIRCHEMOR.NS', companyName: 'Fairchem Organics Ltd.' },
  { symbol: 'FCL.NS', companyName: 'Fineotex Chemical Ltd.' },
  { symbol: 'FOSECOIND.NS', companyName: 'Foseco India Ltd.' },
  { symbol: 'GRAVITA.NS', companyName: 'Gravita India Ltd.' },
  {
    symbol: 'GUJALKALI.NS',
    companyName: 'Gujarat Alkalies and Chemicals Ltd.',
  },
  { symbol: 'HERANBA.NS', companyName: 'Heranba Industries Ltd.' },
  { symbol: 'HIKAL.NS', companyName: 'Hikal Ltd.' },
  { symbol: 'IGPL.NS', companyName: 'IG Petrochemicals Ltd.' },
  { symbol: 'INDIAHLY.NS', companyName: 'India Glycols Ltd.' }, // Check symbol
  { symbol: 'JAYAGROGN.NS', companyName: 'Jayant Agro-Organics Ltd.' },
  {
    symbol: 'KANORICHEM.NS',
    companyName: 'Kanoria Chemicals & Industries Ltd.',
  },
  { symbol: 'KIRIINDUS.NS', companyName: 'Kiri Industries Ltd.' },
  { symbol: 'LAXMICOT.NS', companyName: 'Laxmi Cotspin Ltd.' },
  { symbol: 'MANALIPETC.NS', companyName: 'Manali Petrochemicals Ltd.' },
  { symbol: 'MEGH.NS', companyName: 'Meghmani Organics Ltd.' },
  { symbol: 'NACLIND.NS', companyName: 'NACL Industries Ltd.' },
  { symbol: 'NEEULEC.NS', companyName: 'Neuland Laboratories Ltd.' },
  { symbol: 'NOCIL.NS', companyName: 'NOCIL Ltd.' },
  { symbol: 'ORIENTALTL.NS', companyName: 'Oriental Aromatics Ltd.' },
  { symbol: 'PANAMAPET.NS', companyName: 'Panama Petrochem Ltd.' },
  { symbol: 'PHILIPCARB.NS', companyName: 'Phillips Carbon Black Ltd.' },
  { symbol: 'PODDARMENT.NS', companyName: 'Poddar Pigments Ltd.' },
  { symbol: 'PREMEXPLQ.NS', companyName: 'Premier Explosives Ltd.' },
  {
    symbol: 'PUNJABCHEM.NS',
    companyName: 'Punjab Chemicals & Crop Protection Ltd.',
  },
  { symbol: 'ROSSARI.NS', companyName: 'Rossari Biotech Ltd.' },
  { symbol: 'SADHNANIQ.NS', companyName: 'Sadhana Nitro Chem Ltd.' },
  { symbol: 'SHARDACROP.NS', companyName: 'Sharda Cropchem Ltd.' },
  {
    symbol: 'SUDARSCHEM.NS',
    companyName: 'Sudarshan Chemical Industries Ltd.',
  },
  { symbol: 'TANFACIND.NS', companyName: 'Tanfac Industries Ltd.' },
  { symbol: 'TATVA.NS', companyName: 'Tatva Chintan Pharma Chem Ltd.' },
  { symbol: 'THIRUMALAI.NS', companyName: 'Thirumalai Chemicals Ltd.' },
  { symbol: 'TIRUMALCHM.NS', companyName: 'Thirumalai Chemicals Ltd.' }, // Dup check
  { symbol: 'TRANSPEK.NS', companyName: 'Transpek Industry Ltd.' },
  { symbol: 'ULTRAMAR.NS', companyName: 'Ultramarine & Pigments Ltd.' },
  {
    symbol: 'VIDHIING.NS',
    companyName: 'Vidhi Specialty Food Ingredients Ltd.',
  },
  { symbol: 'VISHNU.NS', companyName: 'Vishnu Chemicals Ltd.' },
  { symbol: 'YASHO.NS', companyName: 'Yasho Industries Ltd.' },

  // --- AUTO PARTS ---
  { symbol: 'ACRYSIL.NS', companyName: 'Carysil Ltd.' }, // Acrysil renamed
  { symbol: 'AGROPHOS.NS', companyName: 'Agro Phos India Ltd.' },
  { symbol: 'ALICON.NS', companyName: 'Alicon Castalloy Ltd.' },
  {
    symbol: 'ASAL.NS',
    companyName: 'Automotive Stampings and Assemblies Ltd.',
  },
  { symbol: 'AUTOLITIND.NS', companyName: 'Autolite (India) Ltd.' },
  { symbol: 'BANCOINDIA.NS', companyName: 'Banco Products (India) Ltd.' },
  { symbol: 'ESABINDIA.NS', companyName: 'ESAB India Ltd.' },
  { symbol: 'FIEMIND.NS', companyName: 'Fiem Industries Ltd.' },
  { symbol: 'GNA.NS', companyName: 'GNA Axles Ltd.' },
  { symbol: 'GULFPETRO.NS', companyName: 'Gulf Oil Lubricants India Ltd.' },
  { symbol: 'HARSHA.NS', companyName: 'Harsha Engineers International Ltd.' },
  { symbol: 'HITECHGEAR.NS', companyName: 'The Hi-Tech Gears Ltd.' },
  { symbol: 'IGARASHI.NS', companyName: 'Igarashi Motors India Ltd.' },
  { symbol: 'IMFA.NS', companyName: 'Indian Metals & Ferro Alloys Ltd.' },
  { symbol: 'IST.NS', companyName: 'IST Ltd.' },
  { symbol: 'JMA.NS', companyName: 'Jullundur Motor Agency (Delhi) Ltd.' },
  { symbol: 'LGTR.NS', companyName: 'L.G. Balakrishnan & Bros Ltd.' },
  { symbol: 'LUMAXIND.NS', companyName: 'Lumax Industries Ltd.' },
  { symbol: 'LUMAXTECH.NS', companyName: 'Lumax Auto Technologies Ltd.' },
  { symbol: 'MENONBE.NS', companyName: 'Menon Bearings Ltd.' },
  { symbol: 'MINDACORP.NS', companyName: 'Minda Corporation Ltd.' },
  { symbol: 'MMFL.NS', companyName: 'M M Forgings Ltd.' },
  { symbol: 'MUNJALAU.NS', companyName: 'Munjal Auto Industries Ltd.' },
  { symbol: 'MUNJALSHOW.NS', companyName: 'Munjal Showa Ltd.' },
  { symbol: 'NELCAST.NS', companyName: 'Nelcast Ltd.' },
  { symbol: 'NRBBEARING.NS', companyName: 'NRB Bearings Ltd.' },
  { symbol: 'ORICOLLTD.NS', companyName: 'Oricon Enterprises Ltd.' },
  { symbol: 'PPAP.NS', companyName: 'PPAP Automotive Ltd.' },
  { symbol: 'PRECISION.NS', companyName: 'Precision Camshafts Ltd.' },
  { symbol: 'PRICOLLTD.NS', companyName: 'Pricol Ltd.' },
  { symbol: 'PRITIKAUTO.NS', companyName: 'Pritika Auto Industries Ltd.' },
  { symbol: 'RACLGEAR.NS', companyName: 'RACL Geartech Ltd.' },
  { symbol: 'RANEENGINE.NS', companyName: 'Rane Engine Valve Ltd.' },
  { symbol: 'RANEHOLDIN.NS', companyName: 'Rane Holdings Ltd.' },
  { symbol: 'RICOAUTO.NS', companyName: 'Rico Auto Industries Ltd.' },
  { symbol: 'ROLEXRINGS.NS', companyName: 'Rolex Rings Ltd.' },
  { symbol: 'SANDHAR.NS', companyName: 'Sandhar Technologies Ltd.' },
  { symbol: 'SETCO.NS', companyName: 'Setco Automotive Ltd.' },
  { symbol: 'SHARDAMOTR.NS', companyName: 'Sharda Motor Industries Ltd.' },
  { symbol: 'SHIVAMAUTO.NS', companyName: 'Shivam Autotech Ltd.' },
  { symbol: 'SKFINDIA.NS', companyName: 'SKF India Ltd.' },
  { symbol: 'SSWL.NS', companyName: 'Steel Strips Wheels Ltd.' },
  { symbol: 'SUBROS.NS', companyName: 'Subros Ltd.' },
  { symbol: 'SUNDARMHLD.NS', companyName: 'Sundaram Brake Linings Ltd.' },
  { symbol: 'SUPRAJIT.NS', companyName: 'Suprajit Engineering Ltd.' },
  {
    symbol: 'TALBROAUTO.NS',
    companyName: 'Talbros Automotive Components Ltd.',
  },
  { symbol: 'TIRUMALCHM.NS', companyName: 'Thirumalai Chemicals' }, // dup catch
  { symbol: 'WHEELS.NS', companyName: 'Wheels India Ltd.' },
  { symbol: 'ZFSTEERING.NS', companyName: 'ZF Steering Gear (India) Ltd.' },

  // --- CONSTRUCTION & INFRA (Micro) ---
  { symbol: 'AHLUCONT.NS', companyName: 'Ahluwalia Contracts (India) Ltd.' },
  { symbol: 'AJMERA.NS', companyName: 'Ajmera Realty & Infra India Ltd.' },
  {
    symbol: 'ANSALAPI.NS',
    companyName: 'Ansal Properties & Infrastructure Ltd.',
  },
  { symbol: 'ANSALHSG.NS', companyName: 'Ansal Housing Ltd.' },
  { symbol: 'ARSSINFRA.NS', companyName: 'ARSS Infrastructure Projects Ltd.' },
  { symbol: 'ASHIANA.NS', companyName: 'Ashiana Housing Ltd.' },
  { symbol: 'ATLASCYCLE.NS', companyName: 'Atlas Cycles (Haryana) Ltd.' },
  { symbol: 'BFUTILITIE.NS', companyName: 'BF Utilities Ltd.' },
  { symbol: 'BINANIIND.NS', companyName: 'Binani Industries Ltd.' },
  {
    symbol: 'CONSOFINVT.NS',
    companyName: 'Consolidated Finvest & Holdings Ltd.',
  },
  {
    symbol: 'DREDGECORP.NS',
    companyName: 'Dredging Corporation of India Ltd.',
  },
  { symbol: 'ELDEHSG.NS', companyName: 'Eldeco Housing & Industries Ltd.' },
  { symbol: 'GEECEE.NS', companyName: 'GeeCee Ventures Ltd.' },
  { symbol: 'GVKPIL.NS', companyName: 'GVK Power & Infrastructure Ltd.' },
  { symbol: 'HCC.NS', companyName: 'Hindustan Construction Company Ltd.' },
  { symbol: 'HITECHCORP.NS', companyName: 'Hitech Corporation Ltd.' },
  { symbol: 'HUBTOWN.NS', companyName: 'Hubtown Ltd.' },
  {
    symbol: 'IL&FSENGG.NS',
    companyName: 'IL&FS Engineering and Construction Company Ltd.',
  },
  {
    symbol: 'IL&FSTRANS.NS',
    companyName: 'IL&FS Transportation Networks Ltd.',
  },
  { symbol: 'ITDCEM.NS', companyName: 'ITD Cementation India Ltd.' },
  { symbol: 'JKIL.NS', companyName: 'J. Kumar Infraprojects Ltd.' },
  { symbol: 'KNRCON.NS', companyName: 'KNR Constructions Ltd.' },
  { symbol: 'KSCL.NS', companyName: 'Kaveri Seed Company Ltd.' },
  { symbol: 'MADHAV.NS', companyName: 'Madhav Marbles & Granites Ltd.' },
  { symbol: 'MAHESHWARI.NS', companyName: 'Maheshwari Logistics Ltd.' },
  { symbol: 'MANINFRA.NS', companyName: 'Man Infraconstruction Ltd.' },
  { symbol: 'MARATHON.NS', companyName: 'Marathon Nextgen Realty Ltd.' },
  { symbol: 'MBLINFRA.NS', companyName: 'MBL Infrastructures Ltd.' },
  { symbol: 'MODISONMET.NS', companyName: 'Modison Metals Ltd.' },
  { symbol: 'NOGL.NS', companyName: 'Nitin Castings Ltd.' }, // check
  { symbol: 'OMINFRA.NS', companyName: 'Om Infra Ltd.' },
  { symbol: 'PATELENG.NS', companyName: 'Patel Engineering Ltd.' },
  { symbol: 'PENINLAND.NS', companyName: 'Peninsula Land Ltd.' },
  { symbol: 'PRAKASH.NS', companyName: 'Prakash Industries Ltd.' },
  { symbol: 'PROZONE.NS', companyName: 'Prozone Integ Properties' }, // Check
  { symbol: 'PUNJLLOYD.NS', companyName: 'Punj Lloyd Ltd.' },
  { symbol: 'PURVA.NS', companyName: 'Puravankara Ltd.' },
  { symbol: 'RAMKY.NS', companyName: 'Ramky Infrastructure Ltd.' },
  { symbol: 'RPGLIFE.NS', companyName: 'RPG Life Sciences Ltd.' },
  { symbol: 'SADBHAV.NS', companyName: 'Sadbhav Engineering Ltd.' },
  { symbol: 'SIMPLEXINF.NS', companyName: 'Simplex Infrastructures Ltd.' },
  { symbol: 'SPMLINFRA.NS', companyName: 'SPML Infra Ltd.' },
  {
    symbol: 'TEXINFRA.NS',
    companyName: 'Texmaco Infrastructure & Holdings Ltd.',
  },
  { symbol: 'VASCONEQ.NS', companyName: 'Vascon Engineers Ltd.' },
  { symbol: 'ZKHANDEL.NS', companyName: 'Zandu Realty' }, // check

  // --- MISC / OTHERS ---
  { symbol: '20MICRONS.NS', companyName: '20 Microns Ltd.' },
  { symbol: '3IINFOTECH.NS', companyName: '3i Infotech Ltd.' },
  { symbol: '63MOONS.NS', companyName: '63 Moons Technologies Ltd.' },
  { symbol: 'ADSL.NS', companyName: 'Allied Digital Services Ltd.' },
  {
    symbol: 'ADVANIHOTR.NS',
    companyName: 'Advani Hotels & Resorts (India) Ltd.',
  },
  { symbol: 'AGARIND.NS', companyName: 'Agarwal Industrial Corporation Ltd.' },
  { symbol: 'AHL.NS', companyName: 'Abans Holdings Ltd.' },
  { symbol: 'AIAENG.NS', companyName: 'AIA Engineering Ltd.' },
  { symbol: 'ALLCARGO.NS', companyName: 'Allcargo Logistics Ltd.' },
  { symbol: 'ALMONDZ.NS', companyName: 'Almondz Global Securities Ltd.' },
  { symbol: 'ALPA.NS', companyName: 'Alpa Laboratories Ltd.' },
  { symbol: 'ALPHAGEO.NS', companyName: 'Alphageo (India) Ltd.' },
  { symbol: 'ALPSINDUS.NS', companyName: 'Alps Industries Ltd.' },
  { symbol: 'AMJLAND.NS', companyName: 'Amj Land Holdings Ltd.' },
  { symbol: 'AMRUTANJAN.NS', companyName: 'Amrutanjan Health Care Ltd.' },
  { symbol: 'ANDHRACEMT.NS', companyName: 'Andhra Cements Ltd.' },
  { symbol: 'ANDHRSUGAR.NS', companyName: 'The Andhra Sugars Ltd.' },
  { symbol: 'ANMOL.NS', companyName: 'Anmol India Ltd.' },
  { symbol: 'APCL.NS', companyName: 'Anjani Portland Cement Ltd.' },
  { symbol: 'APCOTEXIND.NS', companyName: 'Apcotex Industries Ltd.' },
  { symbol: 'APOLSINHOT.NS', companyName: 'Apollo Sindoori Hotels Ltd.' },
  { symbol: 'ARCHIDPLY.NS', companyName: 'Archidply Industries Ltd.' },
  { symbol: 'ARCHIES.NS', companyName: 'Archies Ltd.' },
  { symbol: 'ARIES.NS', companyName: 'Aries Agro Ltd.' },
  { symbol: 'ARIHANTCAP.NS', companyName: 'Arihant Capital Markets Ltd.' },
  { symbol: 'ARIHANTsup.NS', companyName: 'Arihant Superstructures Ltd.' },
  { symbol: 'ARMANFIN.NS', companyName: 'Arman Financial Services Ltd.' },
  { symbol: 'AROGRANITE.NS', companyName: 'Aro Granite Industries Ltd.' },
  { symbol: 'ARROWGREEN.NS', companyName: 'Arrow Greentech Ltd.' },
  { symbol: 'ARSHIYA.NS', companyName: 'Arshiya Ltd.' },
  { symbol: 'ARVIND.NS', companyName: 'Arvind Ltd.' },
  { symbol: 'ARVINDFASN.NS', companyName: 'Arvind Fashions Ltd.' },
  { symbol: 'ASAHISONG.NS', companyName: 'Asahi Songwon Colors Ltd.' },
  { symbol: 'ASALCBR.NS', companyName: 'Associated Alcohols & Breweries Ltd.' },
  { symbol: 'ASHIMASYN.NS', companyName: 'Ashima Ltd.' },
  { symbol: 'ASHOKA.NS', companyName: 'Ashoka Buildcon Ltd.' },
  { symbol: 'ASIANTILES.NS', companyName: 'Asian Granito India Ltd.' },
  { symbol: 'ASPINWALL.NS', companyName: 'Aspinwall and Company Ltd.' },
  { symbol: 'ASTRAMICRO.NS', companyName: 'Astra Microwave Products Ltd.' },
  { symbol: 'ASTRAZEN.NS', companyName: 'AstraZeneca Pharma India Ltd.' },
  { symbol: 'ASTRON.NS', companyName: 'Astron Paper & Board Mill Ltd.' },
  { symbol: 'ATFL.NS', companyName: 'Agro Tech Foods Ltd.' },
  { symbol: 'ATLANTA.NS', companyName: 'Atlanta Ltd.' },
  { symbol: 'ATULAUTO.NS', companyName: 'Atul Auto Ltd.' },
  { symbol: 'AURIONPRO.NS', companyName: 'Aurionpro Solutions Ltd.' },
  { symbol: 'AUSOMENT.NS', companyName: 'Ausom Enterprise Ltd.' },
  { symbol: 'AUTOAXLES.NS', companyName: 'Automotive Axles Ltd.' },
  { symbol: 'AUTOIND.NS', companyName: 'Autoline Industries Ltd.' },
  { symbol: 'AVTNPL.NS', companyName: 'AVT Natural Products Ltd.' },
  { symbol: 'AXISCADES.NS', companyName: 'Axiscades Technologies Ltd.' },
  { symbol: 'AYMSYNTEX.NS', companyName: 'AYM Syntex Ltd.' },
  { symbol: 'BAFNAPH.NS', companyName: 'Bafna Pharmaceuticals Ltd.' },
  { symbol: 'BAGFILMS.NS', companyName: 'B.A.G. Films and Media Ltd.' },
  { symbol: 'BAJAJCON.NS', companyName: 'Bajaj Consumer Care Ltd.' },
  { symbol: 'BAJAJELEC.NS', companyName: 'Bajaj Electricals Ltd.' },
  { symbol: 'BAJAJHCARE.NS', companyName: 'Bajaj Healthcare Ltd.' },
  { symbol: 'BAJAJHIND.NS', companyName: 'Bajaj Hindusthan Sugar Ltd.' },
  { symbol: 'BALAJITELE.NS', companyName: 'Balaji Telefilms Ltd.' },
  { symbol: 'BALAMINES.NS', companyName: 'Balaji Amines Ltd.' },
  { symbol: 'BALAXI.NS', companyName: 'Balaxi Pharmaceuticals Ltd.' },
  { symbol: 'BALMLAWRIE.NS', companyName: 'Balmer Lawrie & Co. Ltd.' },
  { symbol: 'BALPHARMA.NS', companyName: 'Bal Pharma Ltd.' },
  { symbol: 'BANARISUG.NS', companyName: 'Bannari Amman Sugars Ltd.' },
  { symbol: 'BANCOINDIA.NS', companyName: 'Banco Products (India) Ltd.' },
  { symbol: 'BANG.NS', companyName: 'Bang Overseas Ltd.' },
  { symbol: 'BANKA.NS', companyName: 'Banka BioLoo Ltd.' },
  { symbol: 'BANSWRAS.NS', companyName: 'Banswara Syntex Ltd.' },
  { symbol: 'BARTRONICS.NS', companyName: 'Bartronics India Ltd.' },
  { symbol: 'BASML.NS', companyName: 'Bannari Amman Spinning Mills Ltd.' },
  { symbol: 'BBL.NS', companyName: 'Bharat Bijlee Ltd.' },
  { symbol: 'BBTC.NS', companyName: 'Bombay Burmah Trading Corporation Ltd.' },
  { symbol: 'BCG.NS', companyName: 'Brightcom Group Ltd.' },
  { symbol: 'BCP.NS', companyName: 'B.C. Power Controls Ltd.' },
  { symbol: 'BDL.NS', companyName: 'Bharat Dynamics Ltd.' },
  { symbol: 'BEARDSELL.NS', companyName: 'Beardsell Ltd.' },
  {
    symbol: 'BECTORFOOD.NS',
    companyName: 'Mrs. Bectors Food Specialities Ltd.',
  },
  { symbol: 'BEDMUTHA.NS', companyName: 'Bedmutha Industries Ltd.' },
  { symbol: 'BEL.NS', companyName: 'Bharat Electronics Ltd.' },
  { symbol: 'BEML.NS', companyName: 'BEML Ltd.' },
  { symbol: 'BEPL.NS', companyName: 'Bhansali Engineering Polymers Ltd.' },
  { symbol: 'BERGEPAINT.NS', companyName: 'Berger Paints India Ltd.' },
  { symbol: 'BESTAGRO.NS', companyName: 'Best Agrolife Ltd.' },
  { symbol: 'BFINVEST.NS', companyName: 'BF Investment Ltd.' },
  { symbol: 'BFUTILITIE.NS', companyName: 'BF Utilities Ltd.' },
  { symbol: 'BGRENERGY.NS', companyName: 'BGR Energy Systems Ltd.' },
  { symbol: 'BHAGERIA.NS', companyName: 'Bhageria Industries Ltd.' },
  { symbol: 'BHAGYANGR.NS', companyName: 'Bhagyanagar India Ltd.' },
  { symbol: 'BHANDARI.NS', companyName: 'Bhandari Hosiery Exports Ltd.' },
  { symbol: 'BHARATGEAR.NS', companyName: 'Bharat Gears Ltd.' },
  { symbol: 'BHARATRAS.NS', companyName: 'Bharat Rasayan Ltd.' },
  { symbol: 'BHARATWIRE.NS', companyName: 'Bharat Wire Ropes Ltd.' },
  { symbol: 'BHARTIPART.NS', companyName: 'Bhartiya International Ltd.' },
  { symbol: 'BHEL.NS', companyName: 'Bharat Heavy Electricals Ltd.' },
  { symbol: 'BIGBLOC.NS', companyName: 'Bigbloc Construction Ltd.' },
  { symbol: 'BIL.NS', companyName: 'Bhartiya International Ltd.' }, // Check
  { symbol: 'BINANIIND.NS', companyName: 'Binani Industries Ltd.' },
  { symbol: 'BIOCON.NS', companyName: 'Biocon Ltd.' },
  {
    symbol: 'BIOFILCHEM.NS',
    companyName: 'Biofil Chemicals & Pharmaceuticals Ltd.',
  },
  { symbol: 'BIRLACABLE.NS', companyName: 'Birla Cable Ltd.' },
  { symbol: 'BIRLACORPN.NS', companyName: 'Birla Corporation Ltd.' },
  { symbol: 'BIRLAMONEY.NS', companyName: 'Aditya Birla Money Ltd.' },
  { symbol: 'BIRLATYRE.NS', companyName: 'Birla Tyres Ltd.' },
  { symbol: 'BKMINDST.NS', companyName: 'BKM Industries Ltd.' },
  { symbol: 'BLBL.NS', companyName: 'Blue Dart Express Ltd.' }, // Check
  { symbol: 'BLISSGVS.NS', companyName: 'Bliss GVS Pharma Ltd.' },
  { symbol: 'BLKASHYAP.NS', companyName: 'B.L. Kashyap and Sons Ltd.' },
  { symbol: 'BLS.NS', companyName: 'BLS International Services Ltd.' },
  { symbol: 'BLUECHIP.NS', companyName: 'Blue Chip India Ltd.' },
  { symbol: 'BLUECOAST.NS', companyName: 'Blue Coast Hotels Ltd.' },
  { symbol: 'BLUEDART.NS', companyName: 'Blue Dart Express Ltd.' },
  { symbol: 'BLUESTARCO.NS', companyName: 'Blue Star Ltd.' },
  { symbol: 'BODALCHEM.NS', companyName: 'Bodal Chemicals Ltd.' },
  { symbol: 'BOMDYEING.NS', companyName: 'Bombay Dyeing & Mfg. Co. Ltd.' },
  { symbol: 'BOROLTD.NS', companyName: 'Borosil Ltd.' },
  { symbol: 'BORORENEW.NS', companyName: 'Borosil Renewables Ltd.' },
  { symbol: 'BOSCHLTD.NS', companyName: 'Bosch Ltd.' },
  { symbol: 'BPCL.NS', companyName: 'Bharat Petroleum Corporation Ltd.' },
  { symbol: 'BPL.NS', companyName: 'BPL Ltd.' },
  { symbol: 'BRIGADE.NS', companyName: 'Brigade Enterprises Ltd.' },
  { symbol: 'BRITANNIA.NS', companyName: 'Britannia Industries Ltd.' },
  { symbol: 'BRNL.NS', companyName: 'Bharat Road Network Ltd.' },
  { symbol: 'BROOKS.NS', companyName: 'Brooks Laboratories Ltd.' },
  { symbol: 'BSE.NS', companyName: 'BSE Ltd.' },
  { symbol: 'BSELINFRA.NS', companyName: 'BSEL Infrastructure Realty Ltd.' },
  { symbol: 'BSL.NS', companyName: 'BSL Ltd.' },
  { symbol: 'BSOFT.NS', companyName: 'Birlasoft Ltd.' },
  { symbol: 'BURGERKING.NS', companyName: 'Restaurant Brands Asia Ltd.' },
  { symbol: 'BURNPUR.NS', companyName: 'Burnpur Cement Ltd.' },
  {
    symbol: 'BUTTERFLY.NS',
    companyName: 'Butterfly Gandhimathi Appliances Ltd.',
  },
  { symbol: 'BVCL.NS', companyName: 'Barak Valley Cements Ltd.' },
  { symbol: 'BYKE.NS', companyName: 'The Byke Hospitality Ltd.' },
  { symbol: 'CALSOFT.NS', companyName: 'California Software Company Ltd.' },
  { symbol: 'CAMLINFINE.NS', companyName: 'Camlin Fine Sciences Ltd.' },
  { symbol: 'CAMPUS.NS', companyName: 'Campus Activewear Ltd.' },
  { symbol: 'CAMS.NS', companyName: 'Computer Age Management Services Ltd.' },
  { symbol: 'CANBK.NS', companyName: 'Canara Bank' },
  { symbol: 'CANFINHOME.NS', companyName: 'Can Fin Homes Ltd.' },
  { symbol: 'CANTABIL.NS', companyName: 'Cantabil Retail India Ltd.' },
  { symbol: 'CAPACITE.NS', companyName: 'Capacite Infraprojects Ltd.' },
  { symbol: 'CAPLIPOINT.NS', companyName: 'Caplin Point Laboratories Ltd.' },
  { symbol: 'CAPTRUST.NS', companyName: 'Capital Trust Ltd.' },
  { symbol: 'CARBORUNIV.NS', companyName: 'Carborundum Universal Ltd.' },
  { symbol: 'CAREERP.NS', companyName: 'Career Point Ltd.' },
  { symbol: 'CARERATING.NS', companyName: 'CARE Ratings Ltd.' },
  { symbol: 'CARTRADE.NS', companyName: 'CarTrade Tech Ltd.' },
  { symbol: 'CASTROLIND.NS', companyName: 'Castrol India Ltd.' },
  {
    symbol: 'CCCL.NS',
    companyName: 'Consolidated Construction Consortium Ltd.',
  },
  {
    symbol: 'CCHHL.NS',
    companyName: 'Country Club Hospitality & Holidays Ltd.',
  },
  { symbol: 'CCL.NS', companyName: 'CCL Products (India) Ltd.' },
  {
    symbol: 'CDSL.NS',
    companyName: 'Central Depository Services (India) Ltd.',
  },
  { symbol: 'CEATLTD.NS', companyName: 'CEAT Ltd.' },
  {
    symbol: 'CEBBCO.NS',
    companyName: 'Commercial Engineers & Body Builders Co Ltd.',
  },
  { symbol: 'CELEBRITY.NS', companyName: 'Celebrity Fashions Ltd.' },
  { symbol: 'CENTENKA.NS', companyName: 'Century Enka Ltd.' },
  { symbol: 'CENTEXT.NS', companyName: 'Century Extrusions Ltd.' },
  { symbol: 'CENTRALBK.NS', companyName: 'Central Bank of India' },
  { symbol: 'CENTRUM.NS', companyName: 'Centrum Capital Ltd.' },
  { symbol: 'CENTUM.NS', companyName: 'Centrum Electronics Ltd.' },
  { symbol: 'CENTURYPLY.NS', companyName: 'Century Plyboards (India) Ltd.' },
  {
    symbol: 'CENTURYTEX.NS',
    companyName: 'Century Textiles and Industries Ltd.',
  },
  { symbol: 'CERA.NS', companyName: 'Cera Sanitaryware Ltd.' },
  {
    symbol: 'CEREBRAINT.NS',
    companyName: 'Cerebra Integrated Technologies Ltd.',
  },
  { symbol: 'CESC.NS', companyName: 'CESC Ltd.' },
  { symbol: 'CGCL.NS', companyName: 'Capri Global Capital Ltd.' },
  {
    symbol: 'CGPOWER.NS',
    companyName: 'CG Power and Industrial Solutions Ltd.',
  },
  { symbol: 'CHALET.NS', companyName: 'Chalet Hotels Ltd.' },
  {
    symbol: 'CHAMBLFERT.NS',
    companyName: 'Chambal Fertilisers and Chemicals Ltd.',
  },
  { symbol: 'CHEMBOND.NS', companyName: 'Chembond Chemicals Ltd.' },
  { symbol: 'CHEMCON.NS', companyName: 'Chemcon Speciality Chemicals Ltd.' },
  { symbol: 'CHEMFAB.NS', companyName: 'Chemfab Alkalis Ltd.' },
  {
    symbol: 'CHENNPETRO.NS',
    companyName: 'Chennai Petroleum Corporation Ltd.',
  },
  {
    symbol: 'CHOLAFIN.NS',
    companyName: 'Cholamandalam Investment and Finance Company Ltd.',
  },
  {
    symbol: 'CHOLAHLDNG.NS',
    companyName: 'Cholamandalam Financial Holdings Ltd.',
  },
  { symbol: 'CIGNITITEC.NS', companyName: 'Cigniti Technologies Ltd.' },
  { symbol: 'CINELINE.NS', companyName: 'Cineline India Ltd.' },
  { symbol: 'CINEVISTA.NS', companyName: 'Cinevista Ltd.' },
  { symbol: 'CIPLA.NS', companyName: 'Cipla Ltd.' },
  { symbol: 'CLEAN.NS', companyName: 'Clean Science and Technology Ltd.' },
  { symbol: 'CLEDUCATE.NS', companyName: 'CL Educate Ltd.' },
  { symbol: 'CMICABLES.NS', companyName: 'CMI Ltd.' },
  { symbol: 'CNOVAPETRO.NS', companyName: 'Cnova Petrochemicals' }, // Check
  { symbol: 'COALINDIA.NS', companyName: 'Coal India Ltd.' },
  { symbol: 'COCHINSHIP.NS', companyName: 'Cochin Shipyard Ltd.' },
  { symbol: 'COFORGE.NS', companyName: 'Coforge Ltd.' },
  { symbol: 'COLPAL.NS', companyName: 'Colgate-Palmolive (India) Ltd.' },
  { symbol: 'COMPINFO.NS', companyName: 'Compuage Infocom Ltd.' },
  { symbol: 'COMPUSOFT.NS', companyName: 'Compucom Software Ltd.' },
  { symbol: 'CONCOR.NS', companyName: 'Container Corporation of India Ltd.' },
  { symbol: 'CONFIPET.NS', companyName: 'Confidence Petroleum India Ltd.' },
  {
    symbol: 'CONSOFINVT.NS',
    companyName: 'Consolidated Finvest & Holdings Ltd.',
  },
  { symbol: 'CONTROLPR.NS', companyName: 'Control Print Ltd.' },
  {
    symbol: 'CORALFINAC.NS',
    companyName: 'Coral India Finance & Housing Ltd.',
  },
  { symbol: 'CORDSCABLE.NS', companyName: 'Cords Cable Industries Ltd.' },
  { symbol: 'COROMANDEL.NS', companyName: 'Coromandel International Ltd.' },
  { symbol: 'COSMOFIRST.NS', companyName: 'Cosmo First Ltd.' },
  { symbol: 'COUNCODOS.NS', companyName: "Country Condo's Ltd." },
  { symbol: 'CRAFTSMAN.NS', companyName: 'Craftsman Automation Ltd.' },
  { symbol: 'CREATIVE.NS', companyName: 'Creative Eye Ltd.' },
  { symbol: 'CREST.NS', companyName: 'Crest Ventures Ltd.' },
  { symbol: 'CRISIL.NS', companyName: 'CRISIL Ltd.' },
  {
    symbol: 'CROMPTON.NS',
    companyName: 'Crompton Greaves Consumer Electricals Ltd.',
  },
  { symbol: 'CSL.NS', companyName: 'Comfort Systems' }, // Check
  { symbol: 'CTE.NS', companyName: 'Cambridge Technology Enterprises Ltd.' },
  { symbol: 'CUB.NS', companyName: 'City Union Bank Ltd.' },
  { symbol: 'CUBEXTUB.NS', companyName: 'Cubex Tubings Ltd.' },
  { symbol: 'CUMMINSIND.NS', companyName: 'Cummins India Ltd.' },
  { symbol: 'CUPID.NS', companyName: 'Cupid Ltd.' },
  { symbol: 'CYBERMEDIA.NS', companyName: 'Cyber Media (India) Ltd.' },
  {
    symbol: 'CYBERTECH.NS',
    companyName: 'Cybertech Systems and Software Ltd.',
  },
  { symbol: 'CYIENT.NS', companyName: 'Cyient Ltd.' },
  { symbol: 'DAAWAT.NS', companyName: 'LT Foods Ltd.' }, // old symbol check
  { symbol: 'DABUR.NS', companyName: 'Dabur India Ltd.' },
  { symbol: 'DALBHARAT.NS', companyName: 'Dalmia Bharat Ltd.' },
  {
    symbol: 'DALMIASUG.NS',
    companyName: 'Dalmia Bharat Sugar and Industries Ltd.',
  },
  { symbol: 'DAMODARIND.NS', companyName: 'Damodar Industries Ltd.' },
  { symbol: 'DATAMATICS.NS', companyName: 'Datamatics Global Services Ltd.' },
  { symbol: 'DATAPATTNS.NS', companyName: 'Data Patterns (India) Ltd.' },
  { symbol: 'DBCORP.NS', companyName: 'D.B. Corp Ltd.' },
  { symbol: 'DBL.NS', companyName: 'Dilip Buildcon Ltd.' },
  { symbol: 'DBREALTY.NS', companyName: 'D B Realty Ltd.' },
  {
    symbol: 'DBSTOCKBRO.NS',
    companyName: 'DB (International) Stock Brokers Ltd.',
  },
  { symbol: 'DCAL.NS', companyName: 'Dishman Carbogen Amcis Ltd.' },
  { symbol: 'DCM.NS', companyName: 'DCM Ltd.' },
  { symbol: 'DCMFINSERV.NS', companyName: 'DCM Financial Services Ltd.' },
  { symbol: 'DCMNVL.NS', companyName: 'DCM Nouvelle Ltd.' },
  { symbol: 'DCMSHRIRAM.NS', companyName: 'DCM Shriram Ltd.' },
  { symbol: 'DCW.NS', companyName: 'DCW Ltd.' },
  { symbol: 'DCXINDIA.NS', companyName: 'DCX Systems Ltd.' },
  { symbol: 'DECCANCE.NS', companyName: 'Deccan Cements Ltd.' },
  {
    symbol: 'DEEPAKFERT.NS',
    companyName: 'Deepak Fertilisers and Petrochemicals Corporation Ltd.',
  },
  { symbol: 'DEEPAKNTR.NS', companyName: 'Deepak Nitrite Ltd.' },
  { symbol: 'DEEPINDS.NS', companyName: 'Deep Industries Ltd.' },
  { symbol: 'DELHIVERY.NS', companyName: 'Delhivery Ltd.' },
  { symbol: 'DELPHIFX.NS', companyName: 'Delphi World Money Ltd.' },
  { symbol: 'DELTACORP.NS', companyName: 'Delta Corp Ltd.' },
  { symbol: 'DELTAMAGNT.NS', companyName: 'Delta Manufacturing Ltd.' },
  { symbol: 'DEN.NS', companyName: 'Den Networks Ltd.' },
  { symbol: 'DENORA.NS', companyName: 'De Nora India Ltd.' },
  { symbol: 'DEVYANI.NS', companyName: 'Devyani International Ltd.' },
  { symbol: 'DFMFOODS.NS', companyName: 'DFM Foods Ltd.' },
  { symbol: 'DGCONTENT.NS', companyName: 'Digicontent Ltd.' },
  { symbol: 'DHAMPURSUG.NS', companyName: 'Dhampur Sugar Mills Ltd.' },
  { symbol: 'DHANI.NS', companyName: 'Dhani Services Ltd.' },
  { symbol: 'DHANUKA.NS', companyName: 'Dhanuka Agritech Ltd.' },
  { symbol: 'DHARMAJ.NS', companyName: 'Dharmaj Crop Guard Ltd.' },
  { symbol: 'DHUNINV.NS', companyName: 'Dhunseri Investments Ltd.' },
  { symbol: 'DIAMONDYD.NS', companyName: 'Prataap Snacks Ltd.' },
  { symbol: 'DIAMONESYD.NS', companyName: 'Prataap Snacks' }, // check
  { symbol: 'DICIND.NS', companyName: 'DIC India Ltd.' },
  { symbol: 'DIGISPICE.NS', companyName: 'DiGiSPICE Technologies Ltd.' },
  { symbol: 'DIGJAMLTD.NS', companyName: 'Digjam Ltd.' },
  { symbol: 'DILIPBUILD.NS', companyName: 'Dilip Buildcon Ltd.' },
  { symbol: 'DISHTV.NS', companyName: 'Dish TV India Ltd.' },
  { symbol: 'DIVISLAB.NS', companyName: "Divi's Laboratories Ltd." },
  { symbol: 'DIXON.NS', companyName: 'Dixon Technologies (India) Ltd.' },
  { symbol: 'DJML.NS', companyName: 'DJ Mediaprint & Logistics Ltd.' },
  { symbol: 'DLF.NS', companyName: 'DLF Ltd.' },
  { symbol: 'DLINKINDIA.NS', companyName: 'D-Link (India) Ltd.' },
  { symbol: 'DMART.NS', companyName: 'Avenue Supermarts Ltd.' },
  { symbol: 'DOLAT.NS', companyName: 'Dolat Algotech Ltd.' },
  { symbol: 'DOLLAR.NS', companyName: 'Dollar Industries Ltd.' },
  {
    symbol: 'DOLPHINOFF.NS',
    companyName: 'Dolphin Offshore Enterprises (India) Ltd.',
  },
  { symbol: 'DOMS.NS', companyName: 'DOMS Industries Ltd.' },
  { symbol: 'DONEAR.NS', companyName: 'Donear Industries Ltd.' },
  { symbol: 'DPABHUSHAN.NS', companyName: 'D. P. Abhushan Ltd.' },
  { symbol: 'DPSCLTD.NS', companyName: 'DPSC Ltd.' },
  { symbol: 'DPWIRES.NS', companyName: 'D.P. Wires Ltd.' },
  { symbol: 'DRREDDY.NS', companyName: "Dr. Reddy's Laboratories Ltd." },
  { symbol: 'DREAMFOLKS.NS', companyName: 'Dreamfolks Services Ltd.' },
  {
    symbol: 'DREDGECORP.NS',
    companyName: 'Dredging Corporation of India Ltd.',
  },
  { symbol: 'DRCSYSTEMS.NS', companyName: 'DRC Systems India Ltd.' },
  { symbol: 'DREAMFOLKS.NS', companyName: 'Dreamfolks' }, // dup
  { symbol: 'DSKULKARNI.NS', companyName: 'D.S. Kulkarni Developers Ltd.' },
  { symbol: 'DSSL.NS', companyName: 'Dynacons Systems & Solutions Ltd.' },
  // A-D complete. Stopping here for size.
];
