export const NANO_STOCKS = [
  // --- SME & OBSCURE ---
  { symbol: 'AAKASH.NS', companyName: 'Aakash Exploration Services Ltd.' },
  { symbol: 'AARTECH.NS', companyName: 'Aartech Solonics Ltd.' },
  { symbol: 'AARVEEDEN.NS', companyName: 'Aarvee Denims & Exports Ltd.' },
  { symbol: 'ABAN.NS', companyName: 'Aban Offshore Ltd.' },
  { symbol: 'ABMINTLTD.NS', companyName: 'ABM International Ltd.' },
  { symbol: 'ACCURACY.NS', companyName: 'Accuracy Shipping Ltd.' },
  { symbol: 'ACE.NS', companyName: 'Action Construction Equipment Ltd.' },
  { symbol: 'ACEMEN.NS', companyName: 'Ace Men Engg Works Ltd.' },
  { symbol: 'ACI.NS', companyName: 'Archean Chemical Industries Ltd.' },
  { symbol: 'ACKNIT.NS', companyName: 'Acknit Industries Ltd.' },
  { symbol: 'ACRYSIL.NS', companyName: 'Acrysil Ltd.' }, // Check
  { symbol: 'ADANIENT.NS', companyName: 'Adani Enterprises Ltd.' }, // Dup check
  { symbol: 'ADARSHPL.NS', companyName: 'Adarsh Plant Protect Ltd.' },
  { symbol: 'ADBHUTIN.NS', companyName: 'Adbhut Infrastructure Ltd.' },
  { symbol: 'ADL.NS', companyName: 'Archidply Decor Ltd.' },
  { symbol: 'ADORWELD.NS', companyName: 'Ador Welding Ltd.' },
  { symbol: 'ADROITINFO.NS', companyName: 'Adroit Infotech Ltd.' },
  { symbol: 'ADVENZYMES.NS', companyName: 'Advanced Enzyme Technologies Ltd.' },
  { symbol: 'AEGISLOG.NS', companyName: 'Aegis Logistics Ltd.' },
  { symbol: 'AEROFLEX.NS', companyName: 'Aeroflex Industries Ltd.' },
  { symbol: 'AFFLE.NS', companyName: 'Affle (India) Ltd.' },
  { symbol: 'AGARIND.NS', companyName: 'Agarwal Industrial Corporation Ltd.' },
  { symbol: 'AGI.NS', companyName: 'AGI Greenpac Ltd.' },
  { symbol: 'AGRITECH.NS', companyName: 'Agri-Tech (India) Ltd.' },
  { symbol: 'AGROPHOS.NS', companyName: 'Agro Phos India Ltd.' },
  { symbol: 'AHLEAST.NS', companyName: 'Asian Hotels (East) Ltd.' },
  { symbol: 'AHLUCONT.NS', companyName: 'Ahluwalia Contracts (India) Ltd.' },
  { symbol: 'AHLWEST.NS', companyName: 'Asian Hotels (West) Ltd.' },
  { symbol: 'AIIL.NS', companyName: 'Authum Investment & Infrastructure Ltd.' },
  { symbol: 'AIRAN.NS', companyName: 'Airan Ltd.' },
  { symbol: 'AIROLAM.NS', companyName: 'Airo Lam Ltd.' },
  { symbol: 'AJANTPHARM.NS', companyName: 'Ajanta Pharma Ltd.' },
  { symbol: 'AJOONI.NS', companyName: 'Ajooni Biotech Ltd.' },
  { symbol: 'AJRINFRA.NS', companyName: 'AJR Infra and Tolling Ltd.' },
  { symbol: 'AKASH.NS', companyName: 'Akash Infra-Projects Ltd.' },
  { symbol: 'AKG.NS', companyName: 'AKG Exim Ltd.' },
  { symbol: 'AKI.NS', companyName: 'AKI India Ltd.' },
  { symbol: 'AKSHAR.NS', companyName: 'Akshar Spintex Ltd.' },
  { symbol: 'AKSHARCHEM.NS', companyName: 'AksharChem (India) Ltd.' },
  { symbol: 'AKSHOPTFBR.NS', companyName: 'Aksh Optifibre Ltd.' },
  { symbol: 'AKZOINDIA.NS', companyName: 'Akzo Nobel India Ltd.' },
  { symbol: 'ALANKIT.NS', companyName: 'Alankit Ltd.' },
  { symbol: 'ALBERTDA.NS', companyName: 'Albert David Ltd.' },
  { symbol: 'ALCHEM.NS', companyName: 'Alchemist Ltd.' },
  { symbol: 'ALEMBICLTD.NS', companyName: 'Alembic Ltd.' },
  { symbol: 'ALICON.NS', companyName: 'Alicon Castalloy Ltd.' },
  { symbol: 'ALKALI.NS', companyName: 'Alkali Metals Ltd.' },
  { symbol: 'ALKEM.NS', companyName: 'Alkem Laboratories Ltd.' },
  { symbol: 'ALKYLAMINE.NS', companyName: 'Alkyl Amines Chemicals Ltd.' },
  { symbol: 'ALLCARGO.NS', companyName: 'Allcargo Logistics Ltd.' },
  { symbol: 'ALLSEC.NS', companyName: 'Allsec Technologies Ltd.' },
  { symbol: 'ALMONDZ.NS', companyName: 'Almondz Global Securities Ltd.' },
  { symbol: 'ALOKINDS.NS', companyName: 'Alok Industries Ltd.' },
  { symbol: 'ALPA.NS', companyName: 'Alpa Laboratories Ltd.' },
  { symbol: 'ALPHAGEO.NS', companyName: 'Alphageo (India) Ltd.' },
  { symbol: 'ALPSINDUS.NS', companyName: 'Alps Industries Ltd.' },
  { symbol: 'AMAR.NS', companyName: 'Amar Remedies Ltd.' },
  { symbol: 'AMARAJABAT.NS', companyName: 'Amara Raja Energy & Mobility Ltd.' },
  { symbol: 'AMBER.NS', companyName: 'Amber Enterprises India Ltd.' },
  { symbol: 'AMBIKCO.NS', companyName: 'Ambika Cotton Mills Ltd.' },
  { symbol: 'AMBUJACEM.NS', companyName: 'Ambuja Cements Ltd.' },
  { symbol: 'AMDIND.NS', companyName: 'AMD Industries Ltd.' },
  { symbol: 'AMIORG.NS', companyName: 'Ami Organics Ltd.' },
  { symbol: 'AMJLAND.NS', companyName: 'Amj Land Holdings Ltd.' },
  { symbol: 'AMOL.NS', companyName: 'Amol Dicalite Ltd.' },
  { symbol: 'AMRUTANJAN.NS', companyName: 'Amrutanjan Health Care Ltd.' },
  { symbol: 'ANANDRATHI.NS', companyName: 'Anand Rathi Wealth Ltd.' },
  { symbol: 'ANANTRAJ.NS', companyName: 'Anant Raj Ltd.' },
  { symbol: 'ANDHRACEMT.NS', companyName: 'Andhra Cements Ltd.' },
  { symbol: 'ANDHRAPAP.NS', companyName: 'Andhra Paper Ltd.' },
  { symbol: 'ANDHRSUGAR.NS', companyName: 'The Andhra Sugars Ltd.' },
  { symbol: 'ANGELONE.NS', companyName: 'Angel One Ltd.' },
  { symbol: 'ANIKINDS.NS', companyName: 'Anik Industries Ltd.' },
  { symbol: 'ANKITMETAL.NS', companyName: 'Ankit Metal & Power Ltd.' },
  { symbol: 'ANMOL.NS', companyName: 'Anmol India Ltd.' },
  {
    symbol: 'ANSALAPI.NS',
    companyName: 'Ansal Properties & Infrastructure Ltd.',
  },
  { symbol: 'ANSALHSG.NS', companyName: 'Ansal Housing Ltd.' },
  { symbol: 'ANTGRAPHIC.NS', companyName: 'Antarctica Ltd.' },
  { symbol: 'ANUP.NS', companyName: 'The Anup Engineering Ltd.' },
  { symbol: 'ANURAS.NS', companyName: 'Anupam Rasayan India Ltd.' },
  { symbol: 'APARINDS.NS', companyName: 'Apar Industries Ltd.' },
  { symbol: 'APCL.NS', companyName: 'Anjani Portland Cement Ltd.' },
  { symbol: 'APE.NS', companyName: 'Ape' }, // Check
  { symbol: 'APEX.NS', companyName: 'Apex Frozen Foods Ltd.' },
  { symbol: 'APLAPOLLO.NS', companyName: 'APL Apollo Tubes Ltd.' },
  { symbol: 'APLLTD.NS', companyName: 'Alembic Pharmaceuticals Ltd.' },
  { symbol: 'APOLLO.NS', companyName: 'Apollo Micro Systems Ltd.' },
  { symbol: 'APOLLOHOSP.NS', companyName: 'Apollo Hospitals Enterprise Ltd.' },
  { symbol: 'APOLLOPIPE.NS', companyName: 'Apollo Pipes Ltd.' },
  { symbol: 'APOLLOTYRE.NS', companyName: 'Apollo Tyres Ltd.' },
  { symbol: 'APOLSINHOT.NS', companyName: 'Apollo Sindoori Hotels Ltd.' },
  { symbol: 'APTECHT.NS', companyName: 'Aptech Ltd.' },
  { symbol: 'APTUS.NS', companyName: 'Aptus Value Housing Finance India Ltd.' },
  { symbol: 'ARCHIDPLY.NS', companyName: 'Archidply Industries Ltd.' },
  { symbol: 'ARCHIES.NS', companyName: 'Archies Ltd.' },
  { symbol: 'ARE&M.NS', companyName: 'Amara Raja Energy & Mobility Ltd.' },
  { symbol: 'ARENTERP.NS', companyName: 'Rajdarshan Industries' }, // Check
  { symbol: 'ARIES.NS', companyName: 'Aries Agro Ltd.' },
  { symbol: 'ARIHANTCAP.NS', companyName: 'Arihant Capital Markets Ltd.' },
  { symbol: 'ARIHANTsup.NS', companyName: 'Arihant Superstructures Ltd.' },
  { symbol: 'ARMANFIN.NS', companyName: 'Arman Financial Services Ltd.' },
  { symbol: 'AROGRANITE.NS', companyName: 'Aro Granite Industries Ltd.' },
  { symbol: 'ARROWGREEN.NS', companyName: 'Arrow Greentech Ltd.' },
  { symbol: 'ARSHIYA.NS', companyName: 'Arshiya Ltd.' },
  { symbol: 'ARSSINFRA.NS', companyName: 'ARSS Infrastructure Projects Ltd.' },
  { symbol: 'ARTEMISMED.NS', companyName: 'Artemis Medicare Services Ltd.' },
  { symbol: 'ARTNIRMAN.NS', companyName: 'Art Nirman Ltd.' },
  { symbol: 'ARVIND.NS', companyName: 'Arvind Ltd.' },
  { symbol: 'ARVINDFASN.NS', companyName: 'Arvind Fashions Ltd.' },
  { symbol: 'ARVSMART.NS', companyName: 'Arvind SmartSpaces Ltd.' },
  { symbol: 'ASAHIINDIA.NS', companyName: 'Asahi India Glass Ltd.' },
  { symbol: 'ASAHISONG.NS', companyName: 'Asahi Songwon Colors Ltd.' },
  {
    symbol: 'ASAL.NS',
    companyName: 'Automotive Stampings and Assemblies Ltd.',
  },
  { symbol: 'ASALCBR.NS', companyName: 'Associated Alcohols & Breweries Ltd.' },
  { symbol: 'ASHAPURMIN.NS', companyName: 'Ashapura Minechem Ltd.' },
  { symbol: 'ASHIANA.NS', companyName: 'Ashiana Housing Ltd.' },
  { symbol: 'ASHIMASYN.NS', companyName: 'Ashima Ltd.' },
  { symbol: 'ASHOKA.NS', companyName: 'Ashoka Buildcon Ltd.' },
  { symbol: 'ASHOKLEY.NS', companyName: 'Ashok Leyland Ltd.' },
  { symbol: 'ASIANENE.NS', companyName: 'Asian Energy Services Ltd.' },
  { symbol: 'ASIANHOTNR.NS', companyName: 'Asian Hotels (North) Ltd.' },
  { symbol: 'ASIANPAINT.NS', companyName: 'Asian Paints Ltd.' },
  { symbol: 'ASIANTILES.NS', companyName: 'Asian Granito India Ltd.' },
  { symbol: 'ASPINWALL.NS', companyName: 'Aspinwall and Company Ltd.' },
  { symbol: 'ASTEC.NS', companyName: 'Astec LifeSciences Ltd.' },
  { symbol: 'ASTERDM.NS', companyName: 'Aster DM Healthcare Ltd.' },
  { symbol: 'ASTRAL.NS', companyName: 'Astral Ltd.' },
  { symbol: 'ASTRAMICRO.NS', companyName: 'Astra Microwave Products Ltd.' },
  { symbol: 'ASTRAZEN.NS', companyName: 'AstraZeneca Pharma India Ltd.' },
  { symbol: 'ASTRON.NS', companyName: 'Astron Paper & Board Mill Ltd.' },
  { symbol: 'ATFL.NS', companyName: 'Agro Tech Foods Ltd.' },
  { symbol: 'ATGL.NS', companyName: 'Adani Total Gas Ltd.' },
  { symbol: 'ATLANTA.NS', companyName: 'Atlanta Ltd.' },
  { symbol: 'ATLASCYCLE.NS', companyName: 'Atlas Cycles (Haryana) Ltd.' },
  { symbol: 'ATUL.NS', companyName: 'Atul Ltd.' },
  { symbol: 'ATULAUTO.NS', companyName: 'Atul Auto Ltd.' },
  { symbol: 'AUBANK.NS', companyName: 'AU Small Finance Bank Ltd.' },
  { symbol: 'AURIONPRO.NS', companyName: 'Aurionpro Solutions Ltd.' },
  { symbol: 'AUROPHARMA.NS', companyName: 'Aurobindo Pharma Ltd.' },
  { symbol: 'AUSOMENT.NS', companyName: 'Ausom Enterprise Ltd.' },
  { symbol: 'AUTOAXLES.NS', companyName: 'Automotive Axles Ltd.' },
  { symbol: 'AUTOIND.NS', companyName: 'Autoline Industries Ltd.' },
  { symbol: 'AUTOLITIND.NS', companyName: 'Autolite (India) Ltd.' },
  { symbol: 'AVADHSUGAR.NS', companyName: 'Avadh Sugar & Energy Ltd.' },
  { symbol: 'AVALON.NS', companyName: 'Avalon Technologies Ltd.' },
  { symbol: 'AVANTIFEED.NS', companyName: 'Avanti Feeds Ltd.' },
  { symbol: 'AVG.NS', companyName: 'AVG Logistics Ltd.' },
  {
    symbol: 'AVONMORE.NS',
    companyName: 'Avonmore Capital & Management Services Ltd.',
  },
  { symbol: 'AVROIND.NS', companyName: 'Avro India Ltd.' },
  { symbol: 'AVTNPL.NS', companyName: 'AVT Natural Products Ltd.' },
  { symbol: 'AWHCL.NS', companyName: 'Antony Waste Handling Cell Ltd.' },
  { symbol: 'AWL.NS', companyName: 'Adani Wilmar Ltd.' },
  { symbol: 'AXISBANK.NS', companyName: 'Axis Bank Ltd.' },
  { symbol: 'AXISCADES.NS', companyName: 'Axiscades Technologies Ltd.' },
  { symbol: 'AYMSYNTEX.NS', companyName: 'AYM Syntex Ltd.' },
  { symbol: 'BAFNAPH.NS', companyName: 'Bafna Pharmaceuticals Ltd.' },
  { symbol: 'BAGFILMS.NS', companyName: 'B.A.G. Films and Media Ltd.' },
  { symbol: 'BAJAJ-AUTO.NS', companyName: 'Bajaj Auto Ltd.' },
  { symbol: 'BAJAJCON.NS', companyName: 'Bajaj Consumer Care Ltd.' },
  { symbol: 'BAJAJELEC.NS', companyName: 'Bajaj Electricals Ltd.' },
  { symbol: 'BAJAJFINSV.NS', companyName: 'Bajaj Finserv Ltd.' },
  { symbol: 'BAJAJHCARE.NS', companyName: 'Bajaj Healthcare Ltd.' },
  { symbol: 'BAJAJHIND.NS', companyName: 'Bajaj Hindusthan Sugar Ltd.' },
  { symbol: 'BAJAJHLDNG.NS', companyName: 'Bajaj Holdings & Investment Ltd.' },
  { symbol: 'BAJEL.NS', companyName: 'Bajel Projects Ltd.' },
  { symbol: 'BAJFINANCE.NS', companyName: 'Bajaj Finance Ltd.' },
  { symbol: 'BALAJITELE.NS', companyName: 'Balaji Telefilms Ltd.' },
  { symbol: 'BALAMINES.NS', companyName: 'Balaji Amines Ltd.' },
  { symbol: 'BALAXI.NS', companyName: 'Balaxi Pharmaceuticals Ltd.' },
  { symbol: 'BALKRISIND.NS', companyName: 'Balkrishna Industries Ltd.' },
  { symbol: 'BALKRISHNA.NS', companyName: 'Balkrishna Paper Mills Ltd.' },
  { symbol: 'BALMLAWRIE.NS', companyName: 'Balmer Lawrie & Co. Ltd.' },
  { symbol: 'BALPHARMA.NS', companyName: 'Bal Pharma Ltd.' },
  { symbol: 'BALRAMCHIN.NS', companyName: 'Balrampur Chini Mills Ltd.' },
  { symbol: 'BANARISUG.NS', companyName: 'Bannari Amman Sugars Ltd.' },
  { symbol: 'BANCOINDIA.NS', companyName: 'Banco Products (India) Ltd.' },
  { symbol: 'BANDHANBNK.NS', companyName: 'Bandhan Bank Ltd.' },
  { symbol: 'BANG.NS', companyName: 'Bang Overseas Ltd.' },
  { symbol: 'BANKA.NS', companyName: 'Banka BioLoo Ltd.' },
  { symbol: 'BANKBARODA.NS', companyName: 'Bank of Baroda' },
  { symbol: 'BANKINDIA.NS', companyName: 'Bank of India' },
  { symbol: 'BANSWRAS.NS', companyName: 'Banswara Syntex Ltd.' },
  { symbol: 'BARAN.NS', companyName: 'Baran' }, // Check
  { symbol: 'BARBEQUE.NS', companyName: 'Barbeque Nation Hospitality Ltd.' },
  { symbol: 'BASML.NS', companyName: 'Bannari Amman Spinning Mills Ltd.' },
  { symbol: 'BASF.NS', companyName: 'BASF India Ltd.' },
  { symbol: 'BATAINDIA.NS', companyName: 'Bata India Ltd.' },
  { symbol: 'BAYERCROP.NS', companyName: 'Bayer CropScience Ltd.' },
  { symbol: 'BBL.NS', companyName: 'Bharat Bijlee Ltd.' },
  { symbol: 'BBOX.NS', companyName: 'Black Box Ltd.' },
  { symbol: 'BBTC.NS', companyName: 'Bombay Burmah Trading Corporation Ltd.' },
  { symbol: 'BCCL.NS', companyName: 'Bharat Coking Coal' }, // Check
  { symbol: 'BCG.NS', companyName: 'Brightcom Group Ltd.' },
  { symbol: 'BCONCEPTS.NS', companyName: 'Brand Concepts Ltd.' },
  { symbol: 'BCP.NS', companyName: 'B.C. Power Controls Ltd.' },
  { symbol: 'BDL.NS', companyName: 'Bharat Dynamics Ltd.' },
  { symbol: 'BEARDSELL.NS', companyName: 'Beardsell Ltd.' },
  {
    symbol: 'BECTORFOOD.NS',
    companyName: 'Mrs. Bectors Food Specialities Ltd.',
  },
  { symbol: 'BEDMUTHA.NS', companyName: 'Bedmutha Industries Ltd.' },
  { symbol: 'BEL.NS', companyName: 'Bharat Electronics Ltd.' },
  { symbol: 'BEML.NS', companyName: 'BEML Ltd.' },
  { symbol: 'BEPL.NS', companyName: 'Bhansali Engineering Polymers Ltd.' },
  { symbol: 'BERGEPAINT.NS', companyName: 'Berger Paints India Ltd.' },
  { symbol: 'BESTAGRO.NS', companyName: 'Best Agrolife Ltd.' },
  { symbol: 'BFINVEST.NS', companyName: 'BF Investment Ltd.' },
  { symbol: 'BFUTILITIE.NS', companyName: 'BF Utilities Ltd.' },
  { symbol: 'BGRENERGY.NS', companyName: 'BGR Energy Systems Ltd.' },
  { symbol: 'BHAGERIA.NS', companyName: 'Bhageria Industries Ltd.' },
  { symbol: 'BHAGYANGR.NS', companyName: 'Bhagyanagar India Ltd.' },
  { symbol: 'BHANDARI.NS', companyName: 'Bhandari Hosiery Exports Ltd.' },
  { symbol: 'BHARATFORG.NS', companyName: 'Bharat Forge Ltd.' },
  { symbol: 'BHARATGEAR.NS', companyName: 'Bharat Gears Ltd.' },
  { symbol: 'BHARATRAS.NS', companyName: 'Bharat Rasayan Ltd.' },
  { symbol: 'BHARATWIRE.NS', companyName: 'Bharat Wire Ropes Ltd.' },
  { symbol: 'BHARTIARTL.NS', companyName: 'Bharti Airtel Ltd.' },
  { symbol: 'BHARTIPART.NS', companyName: 'Bhartiya International Ltd.' },
  { symbol: 'BHEL.NS', companyName: 'Bharat Heavy Electricals Ltd.' },
  { symbol: 'BIGBLOC.NS', companyName: 'Bigbloc Construction Ltd.' },
  { symbol: 'BIKAJI.NS', companyName: 'Bikaji Foods International Ltd.' },
  { symbol: 'BIL.NS', companyName: 'Bhartiya International Ltd.' },
  { symbol: 'BINANIIND.NS', companyName: 'Binani Industries Ltd.' },
  { symbol: 'BIOCON.NS', companyName: 'Biocon Ltd.' },
  {
    symbol: 'BIOFILCHEM.NS',
    companyName: 'Biofil Chemicals & Pharmaceuticals Ltd.',
  },
  { symbol: 'BIRLACABLE.NS', companyName: 'Birla Cable Ltd.' },
  { symbol: 'BIRLACORPN.NS', companyName: 'Birla Corporation Ltd.' },
  { symbol: 'BIRLAMONEY.NS', companyName: 'Aditya Birla Money Ltd.' },
  { symbol: 'BIRLATYRE.NS', companyName: 'Birla Tyres Ltd.' },
  { symbol: 'BKMINDST.NS', companyName: 'BKM Industries Ltd.' },
  { symbol: 'BLBL.NS', companyName: 'Blue Dart' }, // Check
  { symbol: 'BLISSGVS.NS', companyName: 'Bliss GVS Pharma Ltd.' },
  { symbol: 'BLKASHYAP.NS', companyName: 'B.L. Kashyap and Sons Ltd.' },
  { symbol: 'BLS.NS', companyName: 'BLS International Services Ltd.' },
  { symbol: 'BLUECHIP.NS', companyName: 'Blue Chip India Ltd.' },
  { symbol: 'BLUECOAST.NS', companyName: 'Blue Coast Hotels Ltd.' },
  { symbol: 'BLUEDART.NS', companyName: 'Blue Dart Express Ltd.' },
  { symbol: 'BLUESTARCO.NS', companyName: 'Blue Star Ltd.' },
  { symbol: 'BODALCHEM.NS', companyName: 'Bodal Chemicals Ltd.' },
  { symbol: 'BOMDYEING.NS', companyName: 'Bombay Dyeing & Mfg. Co. Ltd.' },
  { symbol: 'BOROLTD.NS', companyName: 'Borosil Ltd.' },
  { symbol: 'BORORENEW.NS', companyName: 'Borosil Renewables Ltd.' },
  { symbol: 'BOSCHLTD.NS', companyName: 'Bosch Ltd.' },
  { symbol: 'BPCL.NS', companyName: 'Bharat Petroleum Corporation Ltd.' },
  { symbol: 'BPL.NS', companyName: 'BPL Ltd.' },
  { symbol: 'BRIGADE.NS', companyName: 'Brigade Enterprises Ltd.' },
  { symbol: 'BRITANNIA.NS', companyName: 'Britannia Industries Ltd.' },
  { symbol: 'BRNL.NS', companyName: 'Bharat Road Network Ltd.' },
  { symbol: 'BROOKS.NS', companyName: 'Brooks Laboratories Ltd.' },
  { symbol: 'BSE.NS', companyName: 'BSE Ltd.' },
  { symbol: 'BSELINFRA.NS', companyName: 'BSEL Infrastructure Realty Ltd.' },
  { symbol: 'BSL.NS', companyName: 'BSL Ltd.' },
  { symbol: 'BSOFT.NS', companyName: 'Birlasoft Ltd.' },
  { symbol: 'BURGERKING.NS', companyName: 'Restaurant Brands Asia Ltd.' },
  { symbol: 'BURNPUR.NS', companyName: 'Burnpur Cement Ltd.' },
  {
    symbol: 'BUTTERFLY.NS',
    companyName: 'Butterfly Gandhimathi Appliances Ltd.',
  },
  { symbol: 'BVCL.NS', companyName: 'Barak Valley Cements Ltd.' },
  { symbol: 'BYKE.NS', companyName: 'The Byke Hospitality Ltd.' },
  { symbol: 'CALSOFT.NS', companyName: 'California Software Company Ltd.' },
  { symbol: 'CAMLINFINE.NS', companyName: 'Camlin Fine Sciences Ltd.' },
  { symbol: 'CAMPUS.NS', companyName: 'Campus Activewear Ltd.' },
  { symbol: 'CAMS.NS', companyName: 'Computer Age Management Services Ltd.' },
  { symbol: 'CANBK.NS', companyName: 'Canara Bank' },
  { symbol: 'CANFINHOME.NS', companyName: 'Can Fin Homes Ltd.' },
  { symbol: 'CANTABIL.NS', companyName: 'Cantabil Retail India Ltd.' },
  { symbol: 'CAPACITE.NS', companyName: 'Capacite Infraprojects Ltd.' },
  { symbol: 'CAPLIPOINT.NS', companyName: 'Caplin Point Laboratories Ltd.' },
  { symbol: 'CAPTRUST.NS', companyName: 'Capital Trust Ltd.' },
  { symbol: 'CARBORUNIV.NS', companyName: 'Carborundum Universal Ltd.' },
  { symbol: 'CAREERP.NS', companyName: 'Career Point Ltd.' },
  { symbol: 'CARERATING.NS', companyName: 'CARE Ratings Ltd.' },
  { symbol: 'CARTRADE.NS', companyName: 'CarTrade Tech Ltd.' },
  { symbol: 'CASTROLIND.NS', companyName: 'Castrol India Ltd.' },
  {
    symbol: 'CCCL.NS',
    companyName: 'Consolidated Construction Consortium Ltd.',
  },
  {
    symbol: 'CCHHL.NS',
    companyName: 'Country Club Hospitality & Holidays Ltd.',
  },
  { symbol: 'CCL.NS', companyName: 'CCL Products (India) Ltd.' },
  {
    symbol: 'CDSL.NS',
    companyName: 'Central Depository Services (India) Ltd.',
  },
  { symbol: 'CEATLTD.NS', companyName: 'CEAT Ltd.' },
  {
    symbol: 'CEBBCO.NS',
    companyName: 'Commercial Engineers & Body Builders Co Ltd.',
  },
  { symbol: 'CELEBRITY.NS', companyName: 'Celebrity Fashions Ltd.' },
  { symbol: 'CENTENKA.NS', companyName: 'Century Enka Ltd.' },
  { symbol: 'CENTEXT.NS', companyName: 'Century Extrusions Ltd.' },
  { symbol: 'CENTRALBK.NS', companyName: 'Central Bank of India' },
  { symbol: 'CENTRUM.NS', companyName: 'Centrum Capital Ltd.' },
  { symbol: 'CENTUM.NS', companyName: 'Centrum Electronics Ltd.' },
  { symbol: 'CENTURYPLY.NS', companyName: 'Century Plyboards (India) Ltd.' },
  {
    symbol: 'CENTURYTEX.NS',
    companyName: 'Century Textiles and Industries Ltd.',
  },
  { symbol: 'CERA.NS', companyName: 'Cera Sanitaryware Ltd.' },
  {
    symbol: 'CEREBRAINT.NS',
    companyName: 'Cerebra Integrated Technologies Ltd.',
  },
  { symbol: 'CESC.NS', companyName: 'CESC Ltd.' },
  { symbol: 'CGCL.NS', companyName: 'Capri Global Capital Ltd.' },
  {
    symbol: 'CGPOWER.NS',
    companyName: 'CG Power and Industrial Solutions Ltd.',
  },
  { symbol: 'CHALET.NS', companyName: 'Chalet Hotels Ltd.' },
  {
    symbol: 'CHAMBLFERT.NS',
    companyName: 'Chambal Fertilisers and Chemicals Ltd.',
  },
  { symbol: 'CHEMBOND.NS', companyName: 'Chembond Chemicals Ltd.' },
  { symbol: 'CHEMCON.NS', companyName: 'Chemcon Speciality Chemicals Ltd.' },
  { symbol: 'CHEMFAB.NS', companyName: 'Chemfab Alkalis Ltd.' },
  {
    symbol: 'CHENNPETRO.NS',
    companyName: 'Chennai Petroleum Corporation Ltd.',
  },
  { symbol: 'CHEVIOT.NS', companyName: 'Cheviot Company Ltd.' },
  { symbol: 'CHOICEIN.NS', companyName: 'Choice International Ltd.' },
  {
    symbol: 'CHOLAFIN.NS',
    companyName: 'Cholamandalam Investment and Finance Company Ltd.',
  },
  {
    symbol: 'CHOLAHLDNG.NS',
    companyName: 'Cholamandalam Financial Holdings Ltd.',
  },
  { symbol: 'CIGNITITEC.NS', companyName: 'Cigniti Technologies Ltd.' },
  { symbol: 'CINELINE.NS', companyName: 'Cineline India Ltd.' },
  { symbol: 'CINEVISTA.NS', companyName: 'Cinevista Ltd.' },
  { symbol: 'CIPLA.NS', companyName: 'Cipla Ltd.' },
  { symbol: 'CLEAN.NS', companyName: 'Clean Science and Technology Ltd.' },
  { symbol: 'CLEDUCATE.NS', companyName: 'CL Educate Ltd.' },
  { symbol: 'CLSEL.NS', companyName: 'Chaman Lal Setia Exports Ltd.' },
  { symbol: 'CMICABLES.NS', companyName: 'CMI Ltd.' },
  { symbol: 'CNOVAPETRO.NS', companyName: 'Cnova Petrochemicals' },
  { symbol: 'COALINDIA.NS', companyName: 'Coal India Ltd.' },
  { symbol: 'COCHINSHIP.NS', companyName: 'Cochin Shipyard Ltd.' },
  { symbol: 'COFORGE.NS', companyName: 'Coforge Ltd.' },
  { symbol: 'COLPAL.NS', companyName: 'Colgate-Palmolive (India) Ltd.' },
  { symbol: 'COMPINFO.NS', companyName: 'Compuage Infocom Ltd.' },
  { symbol: 'COMPUSOFT.NS', companyName: 'Compucom Software Ltd.' },
  { symbol: 'CONCOR.NS', companyName: 'Container Corporation of India Ltd.' },
  { symbol: 'CONFIPET.NS', companyName: 'Confidence Petroleum India Ltd.' },
  {
    symbol: 'CONSOFINVT.NS',
    companyName: 'Consolidated Finvest & Holdings Ltd.',
  },
  { symbol: 'CONTROLPR.NS', companyName: 'Control Print Ltd.' },
  {
    symbol: 'CORALFINAC.NS',
    companyName: 'Coral India Finance & Housing Ltd.',
  },
  { symbol: 'CORDSCABLE.NS', companyName: 'Cords Cable Industries Ltd.' },
  { symbol: 'COROMANDEL.NS', companyName: 'Coromandel International Ltd.' },
  { symbol: 'COSMOFIRST.NS', companyName: 'Cosmo First Ltd.' },
  { symbol: 'COUNCODOS.NS', companyName: "Country Condo's Ltd." },
  { symbol: 'CRAFTSMAN.NS', companyName: 'Craftsman Automation Ltd.' },
  { symbol: 'CREATIVE.NS', companyName: 'Creative Eye Ltd.' },
  { symbol: 'CREST.NS', companyName: 'Crest Ventures Ltd.' },
  { symbol: 'CRISIL.NS', companyName: 'CRISIL Ltd.' },
  {
    symbol: 'CROMPTON.NS',
    companyName: 'Crompton Greaves Consumer Electricals Ltd.',
  },
  { symbol: 'CSL.NS', companyName: 'Comfort Systems' }, // Check
  { symbol: 'CSLFINANCE.NS', companyName: 'CSL Finance Ltd.' },
  { symbol: 'CTE.NS', companyName: 'Cambridge Technology Enterprises Ltd.' },
  { symbol: 'CUB.NS', companyName: 'City Union Bank Ltd.' },
  { symbol: 'CUBEXTUB.NS', companyName: 'Cubex Tubings Ltd.' },
  { symbol: 'CUMMINSIND.NS', companyName: 'Cummins India Ltd.' },
  { symbol: 'CUPID.NS', companyName: 'Cupid Ltd.' },
  { symbol: 'CYBERMEDIA.NS', companyName: 'Cyber Media (India) Ltd.' },
  {
    symbol: 'CYBERTECH.NS',
    companyName: 'Cybertech Systems and Software Ltd.',
  },
  { symbol: 'CYIENT.NS', companyName: 'Cyient Ltd.' },
  { symbol: 'CYIENTDLM.NS', companyName: 'Cyient DLM Ltd.' },
  { symbol: 'DABUR.NS', companyName: 'Dabur India Ltd.' },
  { symbol: 'DALBHARAT.NS', companyName: 'Dalmia Bharat Ltd.' },
  {
    symbol: 'DALMIASUG.NS',
    companyName: 'Dalmia Bharat Sugar and Industries Ltd.',
  },
  { symbol: 'DAMODARIND.NS', companyName: 'Damodar Industries Ltd.' },
  { symbol: 'DATAMATICS.NS', companyName: 'Datamatics Global Services Ltd.' },
  { symbol: 'DATAPATTNS.NS', companyName: 'Data Patterns (India) Ltd.' },
  { symbol: 'DBCORP.NS', companyName: 'D.B. Corp Ltd.' },
  { symbol: 'DBL.NS', companyName: 'Dilip Buildcon Ltd.' },
  { symbol: 'DBREALTY.NS', companyName: 'D B Realty Ltd.' },
  {
    symbol: 'DBSTOCKBRO.NS',
    companyName: 'DB (International) Stock Brokers Ltd.',
  },
  { symbol: 'DCAL.NS', companyName: 'Dishman Carbogen Amcis Ltd.' },
  { symbol: 'DCM.NS', companyName: 'DCM Ltd.' },
  { symbol: 'DCMFINSERV.NS', companyName: 'DCM Financial Services Ltd.' },
  { symbol: 'DCMNVL.NS', companyName: 'DCM Nouvelle Ltd.' },
  { symbol: 'DCMSHRIRAM.NS', companyName: 'DCM Shriram Ltd.' },
  { symbol: 'DCW.NS', companyName: 'DCW Ltd.' },
  { symbol: 'DCXINDIA.NS', companyName: 'DCX Systems Ltd.' },
  { symbol: 'DECCANCE.NS', companyName: 'Deccan Cements Ltd.' },
  {
    symbol: 'DEEPAKFERT.NS',
    companyName: 'Deepak Fertilisers and Petrochemicals Corporation Ltd.',
  },
  { symbol: 'DEEPAKNTR.NS', companyName: 'Deepak Nitrite Ltd.' },
  { symbol: 'DEEPINDS.NS', companyName: 'Deep Industries Ltd.' },
  { symbol: 'DELHIVERY.NS', companyName: 'Delhivery Ltd.' },
  { symbol: 'DELPHIFX.NS', companyName: 'Delphi World Money Ltd.' },
  { symbol: 'DELTACORP.NS', companyName: 'Delta Corp Ltd.' },
  { symbol: 'DELTAMAGNT.NS', companyName: 'Delta Manufacturing Ltd.' },
  { symbol: 'DEN.NS', companyName: 'Den Networks Ltd.' },
  { symbol: 'DENORA.NS', companyName: 'De Nora India Ltd.' },
  { symbol: 'DEVYANI.NS', companyName: 'Devyani International Ltd.' },
  { symbol: 'DFMFOODS.NS', companyName: 'DFM Foods Ltd.' },
  { symbol: 'DGCONTENT.NS', companyName: 'Digicontent Ltd.' },
  { symbol: 'DHAMPURSUG.NS', companyName: 'Dhampur Sugar Mills Ltd.' },
  { symbol: 'DHANI.NS', companyName: 'Dhani Services Ltd.' },
  { symbol: 'DHANUKA.NS', companyName: 'Dhanuka Agritech Ltd.' },
  { symbol: 'DHARMAJ.NS', companyName: 'Dharmaj Crop Guard Ltd.' },
  { symbol: 'DHROOV.NS', companyName: 'Dhroov' }, // Check
  { symbol: 'DHUNINV.NS', companyName: 'Dhunseri Investments Ltd.' },
  { symbol: 'DIAMONDYD.NS', companyName: 'Prataap Snacks Ltd.' },
  { symbol: 'DICIND.NS', companyName: 'DIC India Ltd.' },
  { symbol: 'DIGISPICE.NS', companyName: 'DiGiSPICE Technologies Ltd.' },
  { symbol: 'DIGJAMLTD.NS', companyName: 'Digjam Ltd.' },
  { symbol: 'DISHTV.NS', companyName: 'Dish TV India Ltd.' },
  { symbol: 'DIVISLAB.NS', companyName: "Divi's Laboratories Ltd." },
  { symbol: 'DIXON.NS', companyName: 'Dixon Technologies (India) Ltd.' },
  { symbol: 'DJML.NS', companyName: 'DJ Mediaprint & Logistics Ltd.' },
  { symbol: 'DLF.NS', companyName: 'DLF Ltd.' },
  { symbol: 'DLINKINDIA.NS', companyName: 'D-Link (India) Ltd.' },
  { symbol: 'DMART.NS', companyName: 'Avenue Supermarts Ltd.' },
  { symbol: 'DOLAT.NS', companyName: 'Dolat Algotech Ltd.' },
  { symbol: 'DOLLAR.NS', companyName: 'Dollar Industries Ltd.' },
  {
    symbol: 'DOLPHINOFF.NS',
    companyName: 'Dolphin Offshore Enterprises (India) Ltd.',
  },
  { symbol: 'DOMS.NS', companyName: 'DOMS Industries Ltd.' },
  { symbol: 'DONEAR.NS', companyName: 'Donear Industries Ltd.' },
  { symbol: 'DPABHUSHAN.NS', companyName: 'D. P. Abhushan Ltd.' },
  { symbol: 'DPSCLTD.NS', companyName: 'DPSC Ltd.' },
  { symbol: 'DPWIRES.NS', companyName: 'D.P. Wires Ltd.' },
  { symbol: 'DRREDDY.NS', companyName: "Dr. Reddy's Laboratories Ltd." },
  { symbol: 'DREAMFOLKS.NS', companyName: 'Dreamfolks Services Ltd.' },
  {
    symbol: 'DREDGECORP.NS',
    companyName: 'Dredging Corporation of India Ltd.',
  },
  { symbol: 'DRCSYSTEMS.NS', companyName: 'DRC Systems India Ltd.' },
  { symbol: 'DSKULKARNI.NS', companyName: 'D.S. Kulkarni Developers Ltd.' },
  { symbol: 'DSSL.NS', companyName: 'Dynacons Systems & Solutions Ltd.' },
  { symbol: 'DTIL.NS', companyName: 'Dhunseri Tea & Industries Ltd.' },
  { symbol: 'DUCON.NS', companyName: 'Ducon Infratechnologies Ltd.' },
  { symbol: 'DVL.NS', companyName: 'Dhunseri Ventures Ltd.' },
  { symbol: 'DWARKESH.NS', companyName: 'Dwarikesh Sugar Industries Ltd.' },
  { symbol: 'DYADEM.NS', companyName: 'Dyadem' }, // Check
  { symbol: 'DYCL.NS', companyName: 'Dyadic' }, // Check
  { symbol: 'DYNAMATECH.NS', companyName: 'Dynamatic Technologies Ltd.' },
  { symbol: 'DYNPRO.NS', companyName: 'Dynemic Products Ltd.' },
  { symbol: 'E2E.NS', companyName: 'E2E Networks Ltd.' },
  { symbol: 'EASEMYTRIP.NS', companyName: 'Easy Trip Planners Ltd.' },
  { symbol: 'ECLERX.NS', companyName: 'eClerx Services Ltd.' },
  { symbol: 'EDELWEISS.NS', companyName: 'Edelweiss Financial Services Ltd.' },
  { symbol: 'EDUCOMP.NS', companyName: 'Educomp Solutions Ltd.' },
  { symbol: 'EICHERMOT.NS', companyName: 'Eicher Motors Ltd.' },
  { symbol: 'EIDPARRY.NS', companyName: 'E.I.D. - Parry (India) Ltd.' },
  { symbol: 'EIHAHOTELS.NS', companyName: 'EIH Associated Hotels Ltd.' },
  { symbol: 'EIJHOTELS.NS', companyName: 'EIH Ltd.' },
  { symbol: 'EIMCOELECO.NS', companyName: 'Eimco Elecon (India) Ltd.' },
  { symbol: 'EKC.NS', companyName: 'Everest Kanto Cylinder Ltd.' },
  { symbol: 'ELECON.NS', companyName: 'Elecon Engineering Company Ltd.' },
  { symbol: 'ELECTCAST.NS', companyName: 'Electrosteel Castings Ltd.' },
  { symbol: 'ELECTHERM.NS', companyName: 'Electrotherm (India) Ltd.' },
  { symbol: 'ELGIEQUIP.NS', companyName: 'Elgi Equipments Ltd.' },
  { symbol: 'ELGIRUBCO.NS', companyName: 'Elgi Rubber Company Ltd.' },
  { symbol: 'ELIN.NS', companyName: 'Elin Electronics Ltd.' },
  { symbol: 'EMAMILTD.NS', companyName: 'Emami Ltd.' },
  { symbol: 'EMAMIPAP.NS', companyName: 'Emami Paper Mills Ltd.' },
  { symbol: 'EMAMIREAL.NS', companyName: 'Emami Realty Ltd.' },
  { symbol: 'EMC.NS', companyName: 'EMC' }, // Check
  { symbol: 'EMIL.NS', companyName: 'Electronics Mart India Ltd.' },
  { symbol: 'EMKAY.NS', companyName: 'Emkay Global Financial Services Ltd.' },
  { symbol: 'EMMBI.NS', companyName: 'Emmbi Industries Ltd.' },
  { symbol: 'ENDURANCE.NS', companyName: 'Endurance Technologies Ltd.' },
  { symbol: 'ENERGYDEV.NS', companyName: 'Energy Development Company Ltd.' },
  { symbol: 'ENGINERSIN.NS', companyName: 'Engineers India Ltd.' },
  { symbol: 'ENIL.NS', companyName: 'Entertainment Network (India) Ltd.' },
  { symbol: 'EPL.NS', companyName: 'EPL Ltd.' },
  {
    symbol: 'EQUIPPP.NS',
    companyName: 'Equippp Social Impact Technologies Ltd.',
  },
  { symbol: 'EQUITASBNK.NS', companyName: 'Equitas Small Finance Bank Ltd.' },
  { symbol: 'ERIS.NS', companyName: 'Eris Lifesciences Ltd.' },
  { symbol: 'EROSMEDIA.NS', companyName: 'Eros International Media Ltd.' },
  { symbol: 'ESABINDIA.NS', companyName: 'ESAB India Ltd.' },
  { symbol: 'ESCORTS.NS', companyName: 'Escorts Kubota Ltd.' },
  { symbol: 'ESSARSHPNG.NS', companyName: 'Essar Shipping Ltd.' },
  { symbol: 'ESTER.NS', companyName: 'Ester Industries Ltd.' },
  { symbol: 'ETHOSLTD.NS', companyName: 'Ethos Ltd.' },
  { symbol: 'EVEREADY.NS', companyName: 'Eveready Industries India Ltd.' },
  { symbol: 'EVERESTIND.NS', companyName: 'Everest Industries Ltd.' },
  { symbol: 'EXCELINDUS.NS', companyName: 'Excel Industries Ltd.' },
  { symbol: 'EXIDEIND.NS', companyName: 'Exide Industries Ltd.' },
  { symbol: 'EXPLEOSOL.NS', companyName: 'Expleo Solutions Ltd.' },
  { symbol: 'EXXARO.NS', companyName: 'Exxaro Tiles Ltd.' },
];
